project_id = "eorqadkulqtneqjbsblk"

[api]
  max_rows = 10000

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.enviar-cotizacion-email]
    verify_jwt = true
  [functions.handle-email-events]
    verify_jwt = false
  [functions.facturapi-webhook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.sentry-tunnel]
    verify_jwt = false
