// Auto-generated barrel for hooks/crm
export * from './useActividades';
export * from './useAutomatizacionesEtapa';
export * from './useCliente360';
export * from './useComentariosOportunidad';
export * from './useCrearCotizacionDesdeOportunidad';
export * from './useCrmDashboard';
export * from './useCrmNotificaciones';
export * from './useEtapasPipeline';
export * from './useForecastReportes';
export * from './useLeadEditForm';
export * from './useLeaderboardVendedores';
export * from './useLeads';
export * from './useLineage';
export * from './useOportunidadCotizaciones';
export * from './useOportunidadForm';
export * from './useOportunidades';
export * from './usePlantillasMensaje';
export * from './useProximasActividades';
