import type { ChangelogEntry } from "../../../changelogData";

export const chunk0: ChangelogEntry[] = [
  {
    version: "8.166.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.3 (cont.) — Idempotencia en upload de documentos",
    summary: "Re-subir el mismo archivo a un documento no duplica filas ni reescribe el registro: el path incluye el hash SHA-256 del contenido.",
    description: "uploadDocumentoEmbarque (src/services/embarque/documentos.ts) reescrito como idempotente por contenido: 1) calcula SHA-256 del File con crypto.subtle, 2) construye un path determinístico embarques/{embarqueId}/{docId}/{hash12}-{filename}, 3) si documentos_embarque.archivo ya apunta al mismo path devuelve {cached:true} sin tocar storage ni DB, 4) reclama idempotency_claim con clave UUID derivada del hash y fn='upload_documento_embarque' para registrar el intento en /idempotencia (cuenta reintentos vía columna hits), 5) hace upload (upsert) + update de la fila sólo si el contenido cambió, 6) llama idempotency_store con {path, fileName} para que un reintento concurrente desde otra pestaña obtenga la respuesta cacheada. Resultado: nunca se duplican registros de documentos_embarque ni se hacen updates redundantes ante reintentos del mismo archivo. Vista /idempotencia ampliada con filtro 'Subir documento'. APP_VERSION 8.166.0."
  },
  {
    version: "8.165.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.3 (cont.) — Idempotencia en mutaciones de actualización",
    summary: "Editar embarque, avanzar estado y editar costos de cotización ahora aceptan p_request_id: reintentos no reescriben conceptos ni duplican notas/eventos.",
    description: "actualizar_embarque_completo reescrito con p_request_id uuid opcional + idempotency_claim/store (evita doble delete/re-insert de conceptos_venta y conceptos_costo). Nueva RPC avanzar_estado_embarque(p_embarque_id, p_nuevo_estado, p_usuario_email, p_tipo_evento, p_descripcion_evento, p_request_id) que ejecuta atómicamente UPDATE estado + INSERT nota cambio_estado + INSERT evento_embarque; reemplaza la cadena de 3 awaits del cliente en useAvanzarEstadoEmbarque (eliminadas notas/eventos duplicados ante reintentos). Nueva RPC actualizar_cotizacion_costos(p_cotizacion_id, p_costos, p_request_id) que sustituye el delete+insert client-side de upsertCotizacionCostos. Servicios actualizados: actualizarEmbarqueRpc, avanzarEstadoEmbarqueRpc, upsertCotizacionCostos. Hooks que generan automáticamente requestId (newRequestId) si el caller no lo provee: useUpdateEmbarque, useAvanzarEstadoEmbarque, useUpsertCotizacionCostos. Vista /idempotencia ampliada con filtros para las nuevas operaciones (Editar embarque, Avanzar estado, Editar costos cotización). APP_VERSION 8.165.0."
  },
  {
    version: "8.164.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.3 (cont.) — Vista de auditoría de idempotencia",
    summary: "Nueva página /idempotencia (admin) que muestra requestId, operación y si la respuesta fue creada o cacheada.",
    description: "Migración: columna hits int default 0 en idempotency_keys + rewrite de idempotency_claim que incrementa hits en cada reintento usando el truco xmax=0 para distinguir insert nuevo de update por conflicto. Nueva RPC SECURITY DEFINER list_idempotency_log(_limit,_offset) restringida a admin/super_admin: devuelve key, fn, hits, created_at, user_id, user_email (join a auth.users), has_response y pending. Nueva página src/pages/dashboard/Idempotencia.tsx con filtro por operación (crear/duplicar/consolidar/facturar), 3 KPIs (creados / cacheados / duplicados bloqueados) y tabla con columnas Fecha, Operación, requestId (con copy-to-clipboard), Usuario, Reintentos y Resultado (badge: Creado = hits=0, Respuesta cacheada = hits>=1, Pendiente). Ruta /idempotencia protegida por ProtectedRoute admin/super_admin y enlace en SIDEBAR_ADMIN_ITEMS. APP_VERSION 8.164.0."
  },
  {
    version: "8.163.0",
    date: "2026-05-16",
    type: "patch",
    title: "Ola A.3 (cont.) — Retry explícito reusa requestId",
    summary: "Reintentar desde la UI tras un error reusa el mismo requestId hasta que la operación tenga éxito, evitando duplicados.",
    description: "Nuevo helper useStableRequestId() en src/lib/idempotency.ts: mantiene un UUID por intento del usuario (get()) y sólo lo regenera tras éxito (reset()). Cableado en los 3 puntos críticos de UI: DialogDuplicarEmbarque (handleDuplicar), useEmbarqueSubmitOrchestrator (submit, fase 3 crear embarque) y useTabProformasPendientesController (handleConsolidar). Si una mutación falla por red, validación o RPC, el siguiente click reutiliza el mismo p_request_id y la RPC devuelve la respuesta cacheada por idempotency_claim/store en vez de crear un registro nuevo. Sólo se descarta el id cuando la operación retorna OK. APP_VERSION 8.163.0."
  },
  {
    version: "8.162.0",
    date: "2026-05-16",
    type: "patch",
    title: "Ola A.3 (cont.) — requestId conectado end-to-end",
    summary: "useCreateEmbarque, useDuplicarEmbarque y useConsolidarProformas generan automáticamente un requestId UUID por intento y lo envían al backend.",
    description: "Cierre de A.3: los tres hooks de mutación (useCreateEmbarque, useDuplicarEmbarque, useConsolidarProformas) ahora invocan newRequestId() cuando el caller no provee uno explícito y propagan el valor al servicio (crearEmbarqueRpc, duplicarEmbarqueRpc, consolidarProformas) y por tanto a p_request_id en las RPCs. Resultado: doble-click en 'Crear Embarque', 'Crear N Embarque(s)' del diálogo de duplicación y 'Consolidar' en proformas pendientes ya NO produce registros duplicados; el segundo intento recibe la respuesta cacheada. Interfaz de los hooks extendida con requestId?: string opcional para casos donde el caller quiera controlar la clave (por ejemplo, persistirla en estado para retries explícitos). APP_VERSION 8.162.0."
  },
  {
    version: "8.161.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.3 — Idempotencia en mutaciones críticas",
    summary: "Crear/duplicar embarques, consolidar proformas y marcar proforma facturada ya no se duplican por doble-click o reintentos de red.",
    description: "Nueva tabla idempotency_keys (key uuid PK, organization_id, user_id, fn, response jsonb) con RLS (cada usuario ve y registra sólo sus propias claves; super_admin ve todo). Helpers SECURITY DEFINER idempotency_claim(_key,_fn) (insert ON CONFLICT DO NOTHING; devuelve respuesta cacheada si ya existía) y idempotency_store(_key,_response). Las 4 RPCs críticas se re-crearon con parámetro opcional p_request_id uuid: crear_embarque_completo, duplicar_embarque_completo, consolidar_proformas y marcar_proforma_facturada. Si llega el mismo request_id dos veces, la RPC devuelve la respuesta original (jsonb cacheado, o el registro re-leído en consolidar_proformas) sin re-ejecutar inserts. Helper frontend src/lib/idempotency.ts newRequestId() (crypto.randomUUID con fallback). Servicios actualizados a aceptar requestId opcional: crearEmbarqueRpc, duplicarEmbarqueRpc y consolidarProformas. APP_VERSION 8.161.0."
  },
  {
    version: "8.160.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.2.3 — Página de Papelera",
    summary: "Nueva sección /papelera (solo admin/super_admin) para ver, restaurar o purgar registros borrados de las 14 tablas con soft delete. Muestra etiqueta legible, fecha/hora de eliminación y correo del usuario que borró.",
    description: "Nueva página src/pages/dashboard/Papelera.tsx con selector de tabla (Embarques, Cotizaciones, Clientes, Contactos, Documentos/Eventos/Notas de embarque, Facturas, Conceptos de factura/costo/venta, Cotización costos, Proformas y conceptos de proforma) que consume list_trash(_table,_limit,_offset). RPC list_trash ampliada (DROP + CREATE) para devolver una etiqueta legible por tabla (folio para cotizaciones, expediente para embarques, nombre para clientes/contactos/documentos, número para facturas/proformas, descripción/concepto/contenido en el resto) y el correo del usuario que eliminó vía join SECURITY DEFINER a auth.users. Acciones por fila: Restaurar (restore_record) y Purgar (purge_record, con confirm window). Acceso protegido por ProtectedRoute allowedRoles=admin/super_admin y enlace en SIDEBAR_ADMIN_ITEMS. APP_VERSION 8.160.0."
  },
  {
    version: "8.159.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.2.2 — Soft delete activo (papelera)",
    summary: "Eliminar cotizaciones, contactos y documentos de embarque ahora envía a papelera en vez de borrar definitivamente. Listados y RLS ocultan los registros borrados.",
    description: "Política RESTRICTIVE deleted_at IS NULL aplicada a las 14 tablas operativas: los registros marcados quedan invisibles para SELECT/UPDATE/DELETE normales. Nuevas funciones RPC SECURITY DEFINER con whitelist de tablas: soft_delete_record(tabla,id) (admin/operador, marca deleted_at/deleted_by), restore_record(tabla,id) (restaura), purge_record(tabla,id) (borrado definitivo, sólo admin/super_admin) y list_trash(tabla,limit,offset) para papelera por organización. Servicios refactoreados a RPC: deleteCotizacion, deleteDocumentoEmbarque y deleteContacto. Mantenidos como hard delete los borrados internos del patrón delete/re-insert (proformas y cotizacion_costos durante edición) y las tablas fuera del scope (proveedores, navieras, puertos, etc.). APP_VERSION 8.159.0."
  },
  {
    version: "8.158.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.2.1 — Preparación de soft delete (esquema)",
    summary: "Nuevas columnas deleted_at/deleted_by + índices parciales en 14 tablas operativas. Sin impacto funcional: la app sigue comportándose igual hasta que A.2.2 conecte la papelera.",
    description: "Agregadas columnas deleted_at (timestamptz) y deleted_by (uuid) en clientes, contactos_cliente, embarques, documentos_embarque, eventos_embarque, notas_embarque, cotizaciones, cotizacion_costos, facturas, conceptos_factura, proformas, proforma_conceptos_consolidados, conceptos_costo y conceptos_venta. Índices parciales idx_<tabla>_deleted_at sólo sobre registros marcados, para que las consultas a la papelera sean rápidas sin penalizar listados normales. Ajustes en PORTAL_EVENTO_COLUMNS, PORTAL_DOCUMENTO_COLUMNS y CONTACTO_COLUMNS para incluir las nuevas columnas y mantener la compatibilidad de tipos en el portal y el detalle de cliente. APP_VERSION 8.158.0."
  },
  {
    version: "8.157.0",
    date: "2026-05-16",
    type: "minor",
    title: "Ola A.1 — Integridad referencial, reglas de dominio e índices",
    summary: "FKs faltantes, CHECKs anti-captura inválida e índices de apoyo en tablas operativas. Previamente se corrigieron 5 embarques con datos negativos/ETD inválida y 1 cotización huérfana.",
    description: "Pre-migración: se corrigieron 5 registros en embarques (ELIMP00163 piezas -15→15, ELIMP00154 volumen -1→1, ELIMP00140 peso -17→17, ELIMP00114 peso -11→11, ELIMP00077 etd 20226→2026) y 1 cotización COT-2026-0007 con embarque_id huérfano (set NULL), todos registrados en bitácora con acciones correccion_datos_auditoria_a1 / limpieza_huerfano_a1. Migración: FKs nuevas en proformas.organization_id, proforma_conceptos_consolidados (embarque_id SET NULL, organization_id RESTRICT), cotizaciones (cliente_id RESTRICT, embarque_id SET NULL), auditoria_revisiones (embarque_id CASCADE, organization_id RESTRICT) y auditoria_comentarios.organization_id. CHECKs de dominio: embarques (peso/volumen/piezas ≥0, eta≥etd, tipos de cambio >0), conceptos_costo (monto≥0), conceptos_venta/factura (precio≥0, cantidad≥1, total≥0), facturas (subtotal/iva/total≥0, tipo_cambio>0, vencimiento≥emision), proformas (totales USD/MXN ≥0), cotizaciones (peso/volumen/piezas/subtotal≥0), cotizacion_costos (cantidad≥1, costo_unitario/precio_venta≥0). Índices nuevos en columnas FK más usadas (cliente_id, embarque_id, organization_id, estado, etd/eta, bitacora_org_created_at). APP_VERSION 8.157.0."
  },
  {
    version: "8.156.2",
    date: "2026-05-16",
    type: "patch",
    title: "Limpieza Ola 3 final — 6 huérfanos en cascada eliminados",
    summary: "Removidas las 6 funciones de servicio sin consumidores detectadas por knip strict. Cero findings.",
    description: "Eliminadas: fetchActividadReciente (services/bitacora), fetchClientes (services/cliente/crud — el listado paginado fetchClientesPaginados sigue vigente), updateConfiguracionItems (services/configuracion), y las 3 queries colaterales fetchEmbarqueDocumentos/fetchEmbarqueNotas/fetchEmbarqueFacturas. Archivo services/embarque/queries/colaterales.ts borrado y desregistrado del barrel queries/index.ts. Typecheck + build verdes, knip --strict sin findings de exports/types/files. APP_VERSION 8.156.2.",
  },
  {
    version: "8.156.1",
    date: "2026-05-16",
    type: "patch",
    title: "Limpieza Ola 3 — exports y tipos sin uso eliminados",
    summary: "Retirados 19 exports y 4 tipos confirmados muertos por knip strict (constantes, hooks y helpers sin consumidores).",
    description: "Eliminados: APP_ROLES, ESTADOS_INACTIVOS, TIPOS_CARGA, fetchProfitPorEmbarque (+ tipo ProfitPorEmbarqueRow), getCarriersForPrefix, getFileUrl, kpiSolidClasses, reglaLabel, useActividadReciente, useClientes, useConfigCategoria, useConfigGlobalValue, useUpdateConfiguracionOrg, useTrackingLinks, useDeleteTrackingLink, y los 4 hooks dead-letter de useEmbarqueQueries (useEmbarques, useEmbarqueDocumentos, useEmbarqueNotas, useEmbarqueFacturas) más sus re-exports en el barrel useEmbarques.ts. Tipos: EmbarqueFormState, EmbarqueFormMethods, StaticErrorKey, CotizacionCostoLookupSanitizado. Imports huérfanos limpiados en cada archivo. knip --strict ahora pasa sin findings. APP_VERSION 8.156.1.",
  },
  {
    version: "8.156.0",
    date: "2026-05-16",
    type: "minor",
    title: "CI — chequeo automático de código no utilizado con knip",
    summary: "Nuevo workflow .github/workflows/ci.yml corre ESLint, knip, tests y build en cada PR. Falla si hay archivos huérfanos, dependencias sin uso, deps no listadas o exports duplicados.",
    description: "Agregado knip 6.14 como devDependency con configuración en knip.json (entries: main.tsx, configs y scripts; ignore: integrations/supabase, components/ui, supabase/, docs/). Scripts nuevos en package.json: 'lint:unused' (gating de PR, falla en files/dependencies/unlisted/duplicates) y 'lint:unused:strict' (incluye exports/types, hoy informational hasta cerrar la Ola 3 de limpieza). Workflow CI: setup-bun + bun install --frozen-lockfile, luego lint → lint:unused (bloqueante) → lint:unused:strict (continue-on-error) → test → build. Concurrency cancela jobs viejos del mismo branch. APP_VERSION 8.156.0.",
  },
  {
    version: "8.155.2",
    date: "2026-05-16",
    type: "patch",
    title: "Limpieza — código y dependencias no utilizadas",
    summary: "Eliminados archivos huérfanos, edge functions sin uso, deps Radix/next-themes y barriles muertos detectados con knip + verificación manual.",
    description: "Auditoría con knip y verificación con rg. Archivos eliminados: src/App.css, scripts/audit-power10.ts, src/components/admin/TabPlataforma.tsx, src/components/operaciones/OperacionesWidgets.tsx, src/hooks/embarque/useProfitMaps.ts. Edge functions huérfanas removidas: supabase/functions/jsoncargo-bol-lookup y jsoncargo-track-batch (ningún cliente las invocaba). Barriles index.ts eliminados (no se importaban): hooks/{admin,catalogos,cliente,configuracion,cotizacion,dashboard,embarque,facturacion,operaciones,portal,proveedor,reportes,shared,usuario}, lib/{financial,ui}. Dependencias removidas: next-themes, @tailwindcss/typography, @radix-ui/{react-aspect-ratio,react-context-menu,react-hover-card,react-menubar,react-navigation-menu,react-scroll-area,react-slider,react-toggle} (toggle-group sigue funcionando vía @radix-ui/react-toggle-group). Duplicado eliminado: export 'changelog' alias en changelogData.ts (los consumidores usan recentChangelog / loadChangelogMajor). APP_VERSION 8.155.2.",
  },
  {
    version: "8.155.1",
    date: "2026-05-16",
    type: "patch",
    title: "Seguridad — guard org en proformas y lectura de auditoría restringida a staff",
    summary: "generar_numero_proforma valida que la organización solicitada coincida con la del usuario; las políticas SELECT de auditoria_comentarios y auditoria_revisiones quedan restringidas a admin/operador/super_admin.",
    description: "1) public.generar_numero_proforma(p_org_id) ahora lanza 'Forbidden: organization mismatch' si p_org_id es NULL o difiere de current_user_org_id() y el caller no es super_admin. Cierra la fuga donde cualquier autenticado podía deducir el conteo anual de proformas de otra organización vía PRO-YYYY-NNNN. 2) Reemplazadas 'Tenant read auditoria_comentarios' y 'Tenant read auditoria_revisiones' por nuevas políticas 'Staff read …' que exigen has_role admin/operador/super_admin además del match de organization_id. Los viewers ya no ven comentarios internos ni emails de staff (responsable_email, asignado_por_email, revisado_por_email). APP_VERSION 8.155.1.",
  },
  {
    version: "8.155.0",
    date: "2026-05-16",
    type: "minor",
    title: "Seguridad — endurecimiento multi-tenant en storage, user_roles y edge functions",
    summary: "Bucket documentos exige path con organization_id, user_roles deja de filtrar roles cross-tenant a admins, parse-csf requiere JWT y valida tipo/tamaño, y create/list/delete-user usan CORS con whitelist.",
    description: "1) storage.objects: políticas Admin/operador upload/update/delete documentos ahora exigen (storage.foldername(name))[1] = current_user_org_id()::text, igual que el bucket facturas. 2) public.user_roles: política SELECT 'Users can view own roles' restringe la rama de admin a usuarios que comparten organization_member con el caller (vía organization_members JOIN); super_admin mantiene acceso global, viewers/operadores siguen viendo solo el propio. 3) supabase/functions/parse-csf: añadido authenticate(req) (JWT obligatorio), validación file.type === 'application/pdf' y MAX_BYTES = 5 MB, con respuestas envueltas en buildCors. Eliminado bloque [functions.parse-csf] verify_jwt = false (la validación vive en código). src/services/csf bloquea la llamada si no hay sesión activa. 4) supabase/functions/create-user, delete-user, list-users: handlePreflight wildcard reemplazado por handlePreflightStrict + buildCors(req); todos los jsonResponse/errorResponse propagan el header con whitelist (mismo patrón que invite-client-user). APP_VERSION 8.155.0.",
  },
  {
    version: "8.154.0",
    date: "2026-05-16",
    type: "minor",
    title: "Seguridad — aislamiento multi-tenant en facturas, documentos y digest",
    summary: "Bucket facturas pasa a privado con políticas por organization_id, lectura de documentos exige join a embarques del mismo tenant, y el digest semanal de auditoría filtra por organización para evitar fugas cross-tenant.",
    description: "1) storage.buckets.facturas: public=false. Nuevas políticas SELECT/INSERT/UPDATE/DELETE en storage.objects que validan que el primer segmento del path coincida con current_user_org_id() y exigen rol admin/operador/super_admin para escritura. Front: nuevo helper src/services/storage/facturas.ts genera URLs firmadas on-demand (1h) con compatibilidad hacia atrás para URLs públicas heredadas; nuevo componente FacturaDownloadButton sustituye los <a target='_blank'> en Facturacion.tsx, HistorialFacturas.tsx, HistorialProformas.tsx y proformasColumns.tsx. facturar.ts guarda paths relativos en factura_pdf/factura_xml. 2) storage.objects policy 'Tenant scoped read documentos' ahora hace EXISTS con JOIN a embarques y verifica que tanto documentos_embarque.organization_id como embarques.organization_id coincidan con el tenant del caller (defensa en profundidad ante colisiones de nombre). 3) auditoria_embarques_org(p_organization_id uuid): nuevo overload SECURITY DEFINER con filtro WHERE organization_id = p_organization_id en todas las CTEs; GRANT EXECUTE solo a service_role. supabase/functions/auditoria-weekly-digest invoca el RPC con { p_organization_id: org.id } por iteración, eliminando la fuga donde cada admin recibía datos financieros de todos los tenants. 4) RPCs actualizar/duplicar/crear_embarque_completo: confirmado que ya tienen guardas current_user_org_id() vs organization_id del embarque; sin cambios. APP_VERSION 8.154.0.",
  },
  {
    version: "8.153.3",
    date: "2026-05-16",
    type: "patch",
    title: "Embarques — estado por UTC para cuadrar con el dashboard",
    summary: "calcularEstadoEmbarque ahora compara fechas en UTC, igual que el backend. Resuelve el desfase en zonas UTC-N donde Arribo del dashboard mostraba 4 y el listado solo 2.",
    description: "El backend (dashboard_details / dashboard_summary) calcula el estado real con current_date de Postgres, que corre en UTC. El frontend usaba new Date() en hora local del navegador, por lo que en México (UTC-6) un embarque con ETA = hoy-UTC quedaba como 'En Tránsito' aunque el servidor ya lo contaba como 'Arribo'. Resultado visible: dashboard mostraba 4 contenedores en Arribo y /embarques?estado=Arribo solo 2 contenedores en 2 expedientes (ELIMP00097 y ELIMP00194), perdiendo ELIMP00111 y ELIMP00112. Fix: calcularEstadoEmbarque en src/lib/domain/embarque.ts construye 'hoy' como medianoche UTC y parsea etd/eta con sufijo 'T00:00:00Z'. Sin cambios de schema ni de RPC. Los estados manuales (Arribo, En Aduana, Entregado, EIR, Cerrado) siguen ganando sobre el cálculo automático.",
  },
  {
    version: "8.153.2",
    date: "2026-05-16",
    type: "patch",
    title: "Embarques — filtro por estado: conteos correctos y fix de paginación",
    summary: "Al filtrar por estado, ahora se trae el set completo y se filtra/agrupa/pagina client-side. Resuelve el bug donde cambiar a 10/pág hacía desaparecer el expediente y los conteos no cuadraban con el dashboard.",
    description: "useEmbarquesPageState ahora detecta cuando filterEstado !== 'todos' y dispara fetchEmbarquesParaExport (todos los embarques que cumplen los demás filtros, sin paginar). Sobre ese set se aplica calcularEstadoEmbarque, se deduplica por expediente, se ordena y se pagina en memoria. Con filterEstado='todos' se mantiene la paginación server-side original. contenedoresCount y expedientesCount ahora reflejan el conteo real del set filtrado, por lo que '4 en Arribo' en el dashboard cuadra con '4 contenedores en 1 expediente' en /embarques?estado=Arribo. Fix adicional: la paginación ya no descarta el expediente al cambiar pageSize porque las páginas se calculan después de filtrar.",
  },
  {
    version: "8.153.1",
    date: "2026-05-16",
    type: "patch",
    title: "Embarques — encabezado muestra contenedores y expedientes",
    summary: "El header del listado ahora muestra 'N contenedores en M expedientes' para alinear el conteo con el dashboard (que cuenta contenedores).",
    description: "Antes el header decía 'N embarques encontrados' usando expedientes deduplicados, lo que contradecía al dashboard que cuenta contenedores (una fila por contenedor en BD). Ahora useEmbarquesPageState expone `expedientesCount` y `contenedoresCount` (suma de contenedoresPorExpediente para los expedientes filtrados, o totalCount cuando no hay filtro de estado) y Embarques.tsx los usa en el PageHeader. Sin cambios en RPC.",
  },
  {
    version: "8.153.0",
    date: "2026-05-16",
    type: "minor",
    title: "Dashboard — los círculos de estado ahora navegan a Embarques filtrado",
    summary: "Hacer clic en un nodo de la línea de tiempo (Confirmado, En Tránsito, Arribo, En Aduana, Entregado) lleva a /embarques?estado=<Estado>, aprovechando el sync con la URL del listado.",
    description: "Antes los círculos eran un toggle visual que solo cambiaba `filtroEstado` interno sin consumidor — confundían al usuario porque parecían accionables sin efecto. Ahora cada botón hace navigate(`/embarques?estado=${encodeURIComponent(estado)}`) y muestra `cursor-pointer` + tooltip 'Ver embarques en estado X (N)'. Se eliminó la prop `filtroEstado/onFiltroChange` de DashboardStatusCards y el useState huérfano de useDashboardData. Sin cambios en RPC ni schema; el listado lee `?estado` vía useEmbarquesPageState (nuqs).",
  },
  {
    version: "8.152.4",
    date: "2026-05-16",
    type: "patch",
    title: "Sidebar — tooltips legibles cuando está colapsado",
    summary: "Los tooltips de los items del sidebar colapsado (Embarques, Cotizaciones, etc.) ahora usan fondo oscuro del sidebar, borde y sombra fuerte para no mezclarse con las cards del dashboard que quedan detrás.",
    description: "SidebarGroupBlock pasa la prop `tooltip` como objeto al SidebarMenuButton con className 'bg-sidebar text-sidebar-foreground border-sidebar-border shadow-xl font-medium' y sideOffset=8. Antes el tooltip usaba bg-popover blanco sin sombra fuerte y se solapaba visualmente con el texto de las cards del contenido principal. Sin cambios en el componente shadcn sidebar.tsx ni en la lógica.",
  },
  {
    version: "8.152.3",
    date: "2026-05-15",
    type: "patch",
    title: "Dashboard — fix posición tooltip 'Cargas activas por cliente'",
    summary: "El tooltip se desplegaba en `side='left'` y quedaba truncado contra el borde izquierdo del viewport (sobre el sidebar). Ahora se muestra arriba de la fila con `align='end'` y `collisionPadding=16`.",
    description: "TooltipContent en CargasActivasClienteCard cambia de side='left' a side='top' align='end' collisionPadding={16}, evitando que el contenido se corte cuando el contenedor del card está cerca del borde izquierdo. Sin cambios funcionales.",
  },
  {
    version: "8.152.2",
    date: "2026-05-15",
    type: "patch",
    title: "Dashboard — tooltip y subtítulo explícitos en 'Cargas activas por cliente'",
    summary: "El header ahora explica qué estados se cuentan y cómo se calcula el %. Tooltip enriquecido por fila con desglose y nota '% del total de tu organización'.",
    description: "(1) Subtítulo en el header: 'Suma de embarques en En Tránsito · Confirmado · Arribo · En Aduana · Entregado. El % de cada fila indica qué porción del total activo de tu organización representa ese cliente.' (2) Tooltip nativo (`title=`) reemplazado por shadcn Tooltip con nombre del cliente, totales, % entre paréntesis y línea 'Incluye embarques en: ...'. (3) Etiqueta de la barra cambia de '45%' a '45% del total' en viewports ≥md (en sm se mantiene '45%' por espacio). (4) Cuando totalActivosGlobal=0 la barra queda vacía y la etiqueta muestra '—' en lugar de 0% para evitar confusión. (5) Aria-label por fila para lectores de pantalla. Sin cambios en RPC, parsers ni hooks.",
  },
  {
    version: "8.152.1",
    date: "2026-05-15",
    type: "patch",
    title: "Dashboard — corrección de totales y barra de proporción en 'Cargas activas por cliente'",
    summary: "El número grande ahora coincide siempre con la suma de los chips visibles, y la barra/porcentaje representa la concentración real del cliente sobre el total activo de TODOS los clientes (ya no respecto al #1 del top).",
    description: "(1) RPC dashboard_details() agrega el escalar cargasActivasTotal con el conteo global de embarques activos cuyo estado_real ∈ {Confirmado, En Tránsito, Arribo, En Aduana, Entregado}. (2) CargasActivasClienteCard ya no lee `total` crudo del payload — recalcula localmente la suma de los 5 estados visibles, eliminando el desajuste cuando un embarque tenía un estado fuera de la lista de chips. Filas con suma 0 se omiten. (3) La barra ahora se dimensiona como (totalCliente / totalActivosGlobal) * 100, con un mínimo visual de 4px para clientes pequeños. La etiqueta de % ya no es relativa al líder del top 10. Tooltip añade contexto: 'N de M cargas activas'. (4) Nuevo parser parseCargasActivasTotal y nuevo campo expuesto desde useDashboardData.",
  },
  {
    version: "8.152.0",
    date: "2026-05-15",
    type: "minor",
    title: "Filtros y paginación sincronizados a la URL — adopción de nuqs + libphonenumber-js",
    summary: "Los listados (Embarques, Cotizaciones, Pre-Facturación, Clientes, Proveedores) ahora reflejan search/filtros/página/orden en la URL, lo que los hace compartibles y persistentes al refresh. Teléfonos se formatean con libphonenumber-js para soportar todas las ladas MX correctamente.",
    description: "Migración de código custom a dependencias maduras según plan de auditoría. (1) `nuqs@2.8.9` integrado vía NuqsAdapter en App.tsx (adapter react-router/v6). useListPageState reescrito sobre useQueryState/useQueryStates manteniendo la misma API pública (search, filters, page, pageSize, setters, paginate) — los 4 consumidores (Clientes, Proveedores, useCotizacionesPageController, useFacturacionPageController) heredan el sync URL sin cambios. Los valores en su default no se serializan, manteniendo la URL limpia (`/clientes` en vez de `/clientes?q=&page=0`). (2) useEmbarquesPageState reescrito para que los 7 filtros + fechas + sort + page se reflejen en query params (reemplaza el patrón anterior de useState + useSearchParams unidireccional). Beneficio inmediato: comparte links pre-filtrados entre operadores ('mis embarques en Confirmado en CDMX para Q1 2026') y el botón Atrás del navegador funciona correctamente. (3) `libphonenumber-js@1.13.2` (build /min, ~35KB gzip) reemplaza el set hardcodeado LADAS_2_DIGITOS de formatPhoneMx — ahora la longitud de lada (2 vs 3 dígitos) se determina contra la metadata oficial mexicana, corrigiendo edge cases en ciudades fuera de CDMX/MTY/GDL/Tijuana. Se preserva el estilo visual histórico '(LADA) NNNN-NNNN' y se soporta correctamente prefijo +52 e internacional (devuelve formato canónico para no-MX). (4) Tests de useListPageState envueltos en withNuqsTestingAdapter. (5) Quedan fuera del alcance (decisión del usuario): PDFs siguen vía window.print() del navegador, exportar CSV/Excel se hará en Google Sheets, y @tanstack/react-table se difiere hasta requerir column resize/virtualización.",
  },
  {
    version: "8.151.0",
    date: "2026-05-15",
    type: "patch",
    title: "Seguridad — RPCs de embarque, user_roles y storage de documentos",
    summary: "Cierre de 3 hallazgos del scanner: ownership check en RPCs de embarque, user_roles solo super_admin, y bucket 'documentos' con scope por organización.",
    description: "(1) actualizar_embarque_completo y duplicar_embarque_completo ahora validan que el embarque pertenece a la organización del caller (o super_admin); de lo contrario, RAISE 'Forbidden'. (2) crear_embarque_completo ignora el organization_id del payload y siempre usa current_user_org_id() para evitar inyección cross-tenant. (3) Eliminada la policy 'Admins manage non-super-admin roles' sobre public.user_roles — solo super_admin puede modificar roles globales; los roles de organización siguen gestionándose vía organization_members. (4) Reemplazada la policy SELECT del bucket 'documentos' (storage.objects) por una scoped a la organización del caller mediante EXISTS sobre documentos_embarque (con fallback para clientes del portal sobre sus propios embarques).",
  },
  {
    version: "8.150.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 4: cierre de Regla #4 (0 componentes >200 líneas)",
    summary: "Últimos 5 componentes >200 líneas reducidos: PortalEmbarqueDetalle (239→184), CotizacionDetalle (219→181), TabProyeccion (216→150), cotizacionesColumns (208→117), ClienteDetalle (206→194). Baseline Regla #4: 5 → 0.",
    description: "Sexta iteración de la Fase 4 (ARCHITECTURE.md §20.4). (1) PortalEmbarqueDetalle: extraído PortalEmbarqueResumenTab (cards Datos de Ruta + Datos Generales) en components/portal/embarqueDetalle/. (2) CotizacionDetalle: nuevo CotizacionDatosGeneralesCard en components/cotizacion/detalle/. (3) TabProyeccion: bloque 'Cierre [Mes Año]' (3 CierreCard + Progress + KPIs) movido a components/facturacion/proyeccion/ProyeccionCierreSection. (4) cotizacionesColumns: helpers renderEstadoVigencia y renderAcciones movidos a components/cotizacion/columnsParts/. (5) ClienteDetalle: tres diálogos (DialogContacto + DialogEditarCliente + DoubleConfirmDeleteDialog) agrupados en components/cliente/detalle/ClienteDetalleDialogs. Tests: 314 verdes. Auditoría power-of-10: 0 hallazgos en Regla #4. Sin cambios de UI ni de comportamiento.",
  },
  {
    version: "8.149.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 4: refactor AdminUsuarios, AsignarResponsableDialog, CotizacionWizardLayout, Embarques y Cotizaciones",
    summary: "Cinco componentes >200 líneas reducidos a shells: AdminUsuarios (221→72), AsignarResponsableDialog (218→146), CotizacionWizardLayout (228→133), Embarques (208→157), Cotizaciones (215→176). Componentes >200 líneas: 10 → 5.",
    description: "Quinta iteración de la Fase 4 (ARCHITECTURE.md §20.4). (1) src/pages/admin/AdminUsuarios.tsx pasa de 221 a 72 líneas: nuevos componentes AdminUsuariosFilters.tsx (search + selects), adminUsuariosColumns.tsx (build con ROLE_BADGE) y hooks/admin/useAdminUsuariosController.ts (filtros + delete). (2) src/components/auditoria/AsignarResponsableDialog.tsx pasa de 218 a 146 líneas: subcomponentes AsignacionExistenteInfo.tsx (panel de meta del responsable actual) y FechaLimitePicker.tsx (Popover + Calendar) en components/auditoria/asignarResponsable/. (3) src/components/cotizacion/CotizacionWizardLayout.tsx pasa de 228 a 133 líneas: PasoDatosGenerales.tsx (Paso 1 con destinatario, mercancía FCL/LCL/Aérea/General y accordion) y CotizacionWizardFooter.tsx (botones Cancelar/Anterior + Siguiente/Guardar) en components/cotizacion/wizard/. (4) src/pages/embarques/Embarques.tsx pasa de 208 a 157 líneas: EmbarquesEmptyState.tsx (CTA de primer embarque) y EmbarquesSortIndicator.tsx (banner de orden global). (5) src/pages/cotizaciones/Cotizaciones.tsx pasa de 215 a 176 líneas: CotizacionesMobileFilters.tsx (Sheet móvil con search + filtros + clear). Tests: 314 verdes. Sin cambios de UI ni de comportamiento. Quedan 5 componentes >200 líneas.",
  },
  {
    version: "8.148.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 4: refactor DataTable, AppSidebar y AdminOrganizaciones",
    summary: "Tres componentes >200 líneas reducidos a shells delgados: DataTable (336 → 130), AppSidebar (216 → 107), AdminOrganizaciones (225 → 64). Componentes >200 líneas: 13 → 10.",
    description: "Cuarta iteración de la Fase 4 (ARCHITECTURE.md §20.4). (1) src/components/shared/DataTable.tsx pasa de 336 a 130 líneas: nuevos módulos en src/components/shared/dataTable/ — types.ts (DataTableColumn, DataTablePagination, ColumnAlign, TableDensity, SortDir, ALIGN_CLASS, DENSITY_CELL), useDataTableSort.ts (estado interno o externo del sort + ordenamiento client), DataTableHeaderRow.tsx (headers con sort indicators) y DataTableBody.tsx (skeletons, empty state y filas). API pública 100% retro-compatible (tipos re-exportados desde el barrel). (2) src/components/layout/AppSidebar.tsx pasa de 216 a 107 líneas: configuración de items movida a sidebarItems.ts (SIDEBAR_DASHBOARD/GESTION/REPORTES/DIRECTORIO/SISTEMA/ADMIN/SUPER_ADMIN_ITEMS); el footer con avatar + dropdown de usuario extraído a SidebarUserMenu.tsx. (3) src/pages/admin/AdminOrganizaciones.tsx pasa de 225 a 64 líneas: lógica de filtros/creación a hooks/admin/useAdminOrganizacionesController.ts; UI partida en AdminOrganizacionesFilters.tsx, NuevaOrganizacionDialog.tsx y adminOrganizacionesColumns.tsx. Tests: 314 verdes. Sin cambios de UI ni de comportamiento. Quedan 10 componentes >200 líneas (próximos: AdminUsuarios 222, CotizacionWizardLayout 229, PortalEmbarqueDetalle 239, AsignarResponsableDialog 219, etc.).",
  },
  {
    version: "8.147.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 4: refactor PortalLayout, Changelog, TabTracking y DialogBolContainers",
    summary: "Cuatro componentes >200 líneas reducidos a shells: PortalLayout (266 → 60), Changelog page (261 → 76), TabTracking (252 → 88), DialogBolContainers (246 → 95). Componentes >200 líneas: 17 → 13.",
    description: "Tercera iteración de la Fase 4 (ARCHITECTURE.md §20.4). (1) src/components/portal/PortalLayout.tsx pasa de 266 a 60 líneas: nuevos módulos en src/components/portal/layout/ — portalNav.ts (constantes y helpers PORTAL_NAV_ITEMS, breadcrumbMap, getActiveSectionLabel, isPortalNavItemActive), PortalMobileNav.tsx (Sheet + nav móvil + signOut), PortalUserMenu.tsx (Avatar + DropdownMenu de usuario), PortalHeader.tsx (header completo con brand, nav desktop, theme toggle), PortalBreadcrumbsBar.tsx (barra de migas) y usePortalBreadcrumbs.ts (memo de migas a partir del pathname). (2) src/pages/dashboard/Changelog.tsx pasa de 261 a 76 líneas: lógica de paginación/filtros/anclas/expand movida a hooks/dashboard/useChangelogController.ts; cada tarjeta vive en components/dashboard/ChangelogEntryCard.tsx. (3) src/components/embarque/TabTracking.tsx pasa de 252 a 88 líneas: nuevos subcomponentes en components/embarque/tracking/ — TrackingEventTimeline.tsx (línea de tiempo con íconos por tipo) y TrackingNuevoEventoForm.tsx (Card + react-hook-form + zod + mutación). (4) src/components/embarque/DialogBolContainers.tsx pasa de 246 a 95 líneas: lógica BL + sync + persistencia movida a hooks/embarque/useDialogBolContainers.ts; render del resultado en components/embarque/dialogBol/BolContainersResult.tsx. Tests: 314 verdes. Sin cambios de UI ni de comportamiento. Quedan 13 componentes >200 líneas (próximos: DataTable 336, AppSidebar 216, AdminOrganizaciones 225, etc.).",
  },
  {
    version: "8.146.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 4: refactor MarcarRevisadoDialog y TrackingLiveCard",
    summary: "MarcarRevisadoDialog (306 → 100 líneas) y TrackingLiveCard (281 → 56 líneas) se parten en subcomponentes por sección. Componentes >200 líneas: 19 → 17.",
    description: "Segunda iteración de la Fase 4 del plan The Power of 10 (ARCHITECTURE.md §20.4). (1) src/components/auditoria/MarcarRevisadoDialog.tsx pasa de 306 a 100 líneas: queda como shell que orquesta tabs y footer. Nuevos subcomponentes en src/components/auditoria/marcarRevisado/: AccionTab.tsx (acción tomada + meta de revisado, exporta también AccionButton para el footer), ComentariosTab.tsx (lista scrollable + composer), SnoozeTab.tsx (fecha + motivo + botones), HallazgoSummary.tsx (encabezado con expediente, cliente, detalle, badges de docs faltantes y banner de snooze activo). El controller useMarcarRevisadoController sigue siendo único punto de lógica. (2) src/components/embarque/TrackingLiveCard.tsx pasa de 281 a 56 líneas: shell de Card + delegación. Nuevos subcomponentes en src/components/embarque/trackingLive/: TrackingActions.tsx (botones Buscar BL Master + Sincronizar con tooltip de blMaster), TrackingWarnings.tsx (sinContenedor, naviera no soportada con CTA externo, prefix mismatch con sugerencias, sin sync previo, error JSONCargo), TrackingFechasPropuestas.tsx (banner de diff ETD/ETA/ATA con CTA Aplicar/Ignorar) y TrackingSummaryGrid.tsx (grid 2 columnas con Field interno). El hook useTrackingLiveCard mantiene toda la lógica. Tests: 314 verdes. Sin cambios visibles ni de comportamiento. Quedan 17 componentes >200 líneas; próximos objetivos: PortalLayout (266), Changelog page (261), TabTracking (252), DialogBolContainers (246).",
  },
  {
    version: "8.145.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 4: refactor Auditoria.tsx (297 → 87 líneas)",
    summary: "La página Auditoria queda como shell delgado: extraídos AuditoriaHallazgosTab, AuditoriaPorReglaTab y helper puro lib/domain/auditoriaCsv. Componentes >200 líneas: 20 → 19.",
    description: "Primer dominio de la Fase 4 del plan The Power of 10 (ARCHITECTURE.md §20.4 — componentes ≤200 líneas). (1) src/pages/Auditoria.tsx pasa de 297 a 87 líneas: se elimina la lógica de renderHallazgosTab/renderPorReglaTab y la construcción de filas para CSV; queda solo el shell con PageHeader, Tabs, drill-down y delegación a subcomponentes. (2) Nuevo src/components/auditoria/AuditoriaHallazgosTab.tsx (118 líneas): KPIs por severidad, banner de revisados con toggle Ver/Ocultar, filtros de severidad/modo, contador y HallazgosTablaPaginada. (3) Nuevo src/components/auditoria/AuditoriaPorReglaTab.tsx (47 líneas): Accordion por regla con badge de conteo y HallazgoTabla embebida. (4) Nuevo src/lib/domain/auditoriaCsv.ts (37 líneas): función pura exportHallazgosCsv() sin dependencias de React, con la constante COLUMNS y el mapeo de filas — testable y reutilizable. (5) scripts/audit-power10.ts también ignora src/content/changelogData.ts (las descripciones del changelog contienen literales como 'as any' que son strings, no `any` de TypeScript). Tests: 314 verdes. Sin cambios visibles ni de comportamiento; sólo reorganización interna. Pendientes Fase 4 (próxima iteración): MarcarRevisadoDialog (306), TrackingLiveCard (281), PortalLayout (266), Changelog page (261), TabTracking (252), DialogBolContainers (246).",
  },
  {
    version: "8.144.0",
    date: "2026-05-14",
    type: "minor",
    title: "Power of 10 — Fase 3: ESLint endurecido (no-explicit-any error)",
    summary: "`@typescript-eslint/no-explicit-any` pasa a `error`, `max-lines-per-function` sube a 200 para alinear con §20.4. TabResumen elimina su `any` casteando a tipo Partial; quedan 0 `any` reales en src/.",
    description: "Cierre de la Fase 3 del plan The Power of 10 (ARCHITECTURE.md §20). (1) eslint.config.js: `@typescript-eslint/no-explicit-any` elevado a `error` con override puntual mediante `// eslint-disable-next-line` en los 2 únicos casos legítimos (src/lib/ui/appFeedback.ts línea 19 — adaptador genérico de toasts; src/services/embarque/queries/listado.ts línea 118 — applyFilters interno). `max-lines-per-function` sube de 150 a 200 para alinear con regla §20.4 (componentes ≤200 líneas). Se agrega exempción para `src/content/changelog/**` (los chunks contienen entradas largas por diseño). (2) src/components/embarque/TabResumen.tsx: los dos `(embarque as any).etd_original/eta_original` se reemplazan por un IIFE local que castea a `Partial<{ etd_original: string | null; eta_original: string | null }>` — el tipo de dominio Embarque no expone esos campos pero la fila de Supabase sí los trae. (3) scripts/audit-power10.ts: el detector de `any` ahora ignora `src/content/changelog/**` (descripciones son strings, no `any` de TS) y respeta `// eslint-disable-next-line @typescript-eslint/no-explicit-any` en la línea anterior. Resultado del baseline: pasa de 17 hallazgos de `any` a **0** en código ejecutable. (4) APP_VERSION 8.144.0. Próxima fase (4): refactors por dominio — extraer controllers + subcomponentes en los 20 archivos >200 líneas y agregar paginación explícita a queries de listas.",
  },
  {
    version: "8.143.0",
    date: "2026-05-14",
    type: "minor",
    title: "Adopción de The Power of 10 (estándar de generación) — Fases 1 y 2",
    summary: "Se incorporan 10 reglas inspiradas en NASA Power of 10, adaptadas a React + Supabase + TS, como estándar obligatorio para todo código nuevo. Documentadas en ARCHITECTURE.md §20 y memorizadas en mem://principles/power-of-10. Baseline read-only generado por scripts/audit-power10.ts en docs/power10-baseline.md.",
    description: "Fase 1 (documentación + memoria): nueva sección §20 en ARCHITECTURE.md con las 10 reglas adaptadas (early returns y sin ternario anidado en JSX; paginación obligatoria en listas visibles pero no `.limit(20)` ciego en KPIs/exports; cleanup en useEffect con suscripciones/timers/listeners; componentes ≤200 líneas con extracción a use<X>Controller + subcomponentes, exentos shadcn vendored, tests y migraciones; tipos generados de Supabase y prohibición de `any`; estado local primero; manejo explícito de `error` de Supabase con useToast + errorCatalog; stack fija Vite+Tailwind+shadcn+React Query; prop-drilling ≥3 niveles dispara revisión; cero warnings TS/ESLint en build). Memoria mem://principles/power-of-10 condensa las reglas y se referencia desde mem://index.md (Core) para que la IA generadora la aplique por defecto. Fase 2 (baseline read-only): scripts/audit-power10.ts (TS, dependency-free, ejecutable con bunx tsx) recorre src/ con heurísticas conservadoras y genera docs/power10-baseline.md agrupado por dominio. Hallazgos iniciales: 20 componentes >200 líneas, 17 usos de `any`, 1 useEffect potencialmente sin cleanup, 68 queries de listado sin paginar (algunas falsos positivos por queries agregadas). No se modifica código de aplicación. Fases 3 (endurecer eslint.config.js) y 4 (limpieza por dominio) quedan pendientes para iteraciones siguientes para no bloquear desarrollo. APP_VERSION 8.143.0.",
  },
  {
    version: "8.142.0",
    date: "2026-05-14",
    type: "minor",
    title: "lib/domain/auditoria — reglas puras testables + ARCHITECTURE actualizado",
    summary: "Se extraen las reglas puras de auditoría (snooze, conteo por severidad, agrupación por regla, filtros) a src/lib/domain/auditoria.ts con tests, y ARCHITECTURE.md documenta la convención queries + mutations + subdominios.",
    description: "Cierre de los pasos 2 y 3 opcionales de la auditoría arquitectónica. (1) Nuevo módulo src/lib/domain/auditoria.ts expone funciones puras sin dependencias de React/Supabase: isoDate, minSnoozeDate (día siguiente al `from`), isSnoozeActivo (snoozedUntil >= today, tolera null/undefined), contarPorSeveridad (siempre devuelve {critico,alto,medio}), agruparPorRegla (garantiza un array por cada ReglaAuditoria) y filtrarHallazgos ('todas'/'todos' no filtran). Se acompaña de src/lib/domain/__tests__/auditoria.test.ts con 15 casos cubriendo fin de mes, snooze nulo y combinación de filtros. (2) useAuditoriaPageController y useMarcarRevisadoController consumen las funciones puras eliminando la lógica inline. (3) ARCHITECTURE.md gana la subsección 5.1 documentando que un dominio crecido se parte en queries.ts + mutations.ts + subdominios, con el barrel re-exportando todo. APP_VERSION 8.142.0. Tests: 45 verdes en hooks/auditoria + lib/domain/auditoria.",
  },
  {
    version: "8.141.0",
    date: "2026-05-14",
    type: "minor",
    title: "services/cotizacion estandarizado a queries + mutations",
    summary: "El service de cotizaciones adopta la convención `queries.ts` (lecturas) + `mutations.ts` (escrituras); el archivo legacy `crud.ts` desaparece y el barrel se actualiza.",
    description: "Paso 4 de la auditoría arquitectónica. services/cotizacion/crud.ts (172 líneas mezclando lecturas y escrituras) se partió en queries.ts (COTIZACION_LIST_COLUMNS, COTIZACION_ACEPTADA_COLUMNS, generarFolioCotizacion, fetchCotizaciones, fetchCotizacionesAceptadas, fetchCotizacionById, fetchEmbarquesVinculados) y mutations.ts (crearCotizacion, updateCotizacion, deleteCotizacion, updateEstadoCotizacion). El barrel index.ts mantiene la API pública intacta y documenta la convención `queries + mutations + subdominios (costos, conversiones, wizard)`. conversiones/duplicar.ts ahora importa generarFolioCotizacion desde ../queries. Los 13+ consumidores existentes no requieren cambios.",
  },
  {
    version: "8.140.1",
    date: "2026-05-14",
    type: "patch",
    title: "Rotación del chunk0 del changelog v8",
    summary: "v8/chunks/0.ts (1086 líneas, 145 entradas) se redujo a 20 entradas; las 125 entradas anteriores se trasladaron a v8/chunks/6.ts y se registraron en v8.ts.",
    description: "Cierre del paso 3 de la auditoría arquitectónica. v8/chunks/0.ts crecía sin límite y empezaba a impactar el lazy-chunk de Changelog. Se extrajeron las entradas 21-145 (desde 8.132.1 hasta 8.64.0) al nuevo archivo v8/chunks/6.ts y se incorporó al barrel src/content/changelog/v8.ts. El orden cronológico descendente se preserva al concatenar chunk0 → … → chunk6. APP_VERSION 8.140.1.",
  },
  {
    version: "8.140.0",
    date: "2026-05-14",
    type: "minor",
    title: "Auditoría arquitectónica: controllers de auditoría + RHF en TabTracking",
    summary: "MarcarRevisadoDialog y AsignarResponsableDialog quedan como UI pura sobre nuevos hooks controller, y TabTracking migra su formulario a react-hook-form + zod.",
    description: "Pasos 6 y 7 de la auditoría. (1) Nuevos hooks hooks/auditoria/useMarcarRevisadoController y useAsignarResponsableController concentran estado local, sincronización con la revisión existente y handlers (guardar/eliminar/snooze/quitarSnooze/comentario en el primero; submit con 'tomarlo yo' en el segundo). Los diálogos respectivos quedaron como componentes de presentación que sólo orquestan ctrl.* sin tocar mutations directamente. (2) src/components/embarque/TabTracking.tsx migra el formulario inline (4 useState ad-hoc) a react-hook-form + zodResolver con eventoSchema (tipo requerido, fecha requerida, ubicación ≤120, descripción ≤500). Errores se muestran inline; el botón 'Guardar Evento' se deshabilita por isValid en lugar de chequeo manual. Pendientes: rotar v8/chunks/0.ts a v8/chunks/6.ts (~1078 líneas), documentar convenciones en ARCHITECTURE.md y considerar lib/domain/auditoria.ts con reglas puras testables.",
  },
  {
    version: "8.139.0",
    date: "2026-05-14",
    type: "minor",
    title: "Auditoría arquitectónica: split queries + controller TrackingLiveCard",
    summary: "services/embarque/queries.ts (355 líneas) partido en 6 submódulos por subdominio y TrackingLiveCard consume hook controller.",
    description: "Pasos 4 y 5 de la auditoría arquitectónica. (1) services/embarque/queries.ts ahora es una carpeta queries/ con archivos por subdominio: listado.ts (fetchEmbarques, fetchEmbarquesPaginados con SORTABLE_EMBARQUE_COLUMNS y filtros, fetchEmbarquesParaExport con paginación interna, fetchEmbarquesRelacionados, fetchEmbarquesListExtras vía RPC), detalle.ts (fetchEmbarqueById + fetchEmbarqueFull con resolución por UUID o expediente), conceptos.ts (venta + costo), colaterales.ts (documentos + notas + facturas), expedientes.ts (agrupación por folio) y proveedores.ts. El barrel queries/index.ts re-exporta todo el API público, por lo que los 13+ consumidores que importan vía services/embarque no requieren cambios. (2) Componente TrackingLiveCard reducido a render puro: nuevo hook hooks/embarque/useTrackingLiveCard encapsula queries/mutations de JSONCargo (useJsonCargoTracking, useSyncJsonCargo, useApplyJsonCargoFechas), estado local (bolDialogOpen, fechasDismissed), reglas derivadas (mapNavieraToJsonCargo, validatePrefixMatchesNaviera, summary, fechasPropuestas, showPrefixWarning, suggestions) y handlers onSync / onAplicarFechas con feedback de toasts. La función pura jsoncargoDateToYmd queda exportada del hook. Pendientes (próxima iteración): crear lib/domain/auditoria.ts con tests y extraer controllers desde MarcarRevisadoDialog (409) y AsignarResponsableDialog (242); migrar el form de TabTracking a react-hook-form. Tests: 298 verdes.",
  },
  {
    version: "8.138.0",
    date: "2026-05-14",
    type: "minor",
    title: "Auditoría arquitectónica: limpieza de capas (paso 1)",
    summary: "Unificado useToast (eliminado duplicado), DialogBolContainers ya no llama Supabase directamente, y los tipos de fila de embarque viven en types/embarque.ts.",
    description: "Resultado de la auditoría de arquitectura solicitada. (1) Se eliminó src/hooks/shared/use-toast.ts, un re-export huérfano que abría la puerta a duplicar el singleton de toasts. Todos los imports usan ahora @/hooks/use-toast (convención shadcn). (2) DialogBolContainers ya no importa @/integrations/supabase/client: se creó services/embarque/contenedor.ts con actualizarContenedorEmbarque y el hook hooks/embarque/mutations/useActualizarContenedorEmbarque que invalida queryKeys.embarques.detail. Los componentes recuperan así la regla 'no tocar Supabase desde la capa de UI'. (3) Los aliases EmbarqueRow, ConceptoVentaRow, ConceptoCostoRow, DocumentoEmbarqueRow y NotaEmbarqueRow se centralizaron en src/types/embarque.ts; el barrel hooks/embarque/useEmbarques.ts los re-exporta para conservar la API pública sin tocar 13+ consumidores. Pasos restantes de la auditoría (próximas iteraciones): partir services/embarque/queries.ts en submódulos por subdominio, extraer hooks controller en TrackingLiveCard, MarcarRevisadoDialog y AsignarResponsableDialog, crear lib/domain/auditoria.ts con tests, migrar TabTracking de useState ad-hoc a react-hook-form y rotar el chunk obeso v8/chunks/0.ts a un nuevo v8/chunks/6.ts. Tests: 298 verdes (la falla pre-existente de 'recentChangelog ≤10 entradas' no es regresión).",
  },
  {
    version: "8.137.0",
    date: "2026-05-14",
    type: "minor",
    title: "Bitácora más descriptiva con filtros",
    summary: "Cada entrada describe en lenguaje natural lo que sucedió (estado anterior → nuevo, cliente, modo, documento, etc.) y se agregaron filtros por acción y rango de fechas.",
    description: "Nuevo helper puro src/lib/domain/bitacoraDescripcion.ts que aprovecha el JSONB de detalles ya guardado para generar títulos descriptivos por accion+modulo (cambio de estado con badges Arribo → En Aduana, creación/edición de embarques con modo/tipo/cliente, subida/eliminación de documentos con tipo_documento, notas con preview de 80 caracteres, facturas con folio y monto). BitacoraActividad rediseñado: usuario · tiempo arriba, título descriptivo en foreground, módulo + link a entidad debajo. Página de Bitácora agrega filtros por acción (Crear/Editar/Eliminar/Cambio de estado/Documentos/Notas/Facturas) y rango (Hoy / 7 días / 30 días / Todo). El servicio fetchBitacora acepta el filtro acciones (in) sin tocar RLS. Tests unitarios cubren cada rama de describirEntrada.",
  },
  {
    version: "8.136.0",
    date: "2026-05-14",
    type: "minor",
    title: "Tracking: línea de tiempo de fases del embarque",
    summary: "El tab Tracking ahora muestra un stepper visual con las 5 fases canónicas del ciclo (Cotización → Confirmado → En Tránsito → Llegada → Cerrado) y las notas del embarque en la misma vista.",
    description: "Nuevo componente TrackingFasesTimeline que renderiza un stepper horizontal en desktop y vertical en móvil, indicando para cada fase su estado (completada / actual / pendiente) y la fecha asociada (cotizacion_id, fecha_creacion, etd, fecha_llegada_real ?? eta, updated_at en Cerrado). La fase actual se calcula reutilizando calcularEstadoEmbarque del dominio. Toda la lógica vive en src/lib/domain/embarqueFases.ts (con tests unitarios) sin tocar Supabase. Adicionalmente, TabTracking ahora muestra TabNotas al final para tener actividad y notas a un click del avance del embarque.",
  },
  {
    version: "8.135.6",
    date: "2026-05-14",
    type: "patch",
    title: "Refactor UI: early returns para estados de carga",
    summary: "Tarjetas y páginas con loading/empty/contenido extraen un helper renderBody() con early returns; el JSX principal queda plano y legible.",
    description: "Refactorizados AuditoriaTendenciaChart, ReportesTopChart, ProximosArribosCard, AlertasDemoraCard, CargasActivasClienteCard, TablaContactos, TabTracking (timeline), TabProformasPendientes, Bitacora, Operaciones (chart de tendencia) y Auditoria (tabs Hallazgos y Por regla). Se eliminó el patrón ternario anidado isLoading ? ... : empty ? ... : (...) reemplazándolo por funciones renderXxx() con if/return. Sin cambios visuales ni de comportamiento.",
  },
  {
    version: "8.135.5",
    date: "2026-05-14",
    type: "patch",
    title: "Refactor UI: ternarios anidados reemplazados por helpers nombrados",
    summary: "18 puntos en componentes y páginas dejan de usar ternarios encadenados; ahora usan helpers reutilizables (pluralS, formatDiasCredito, getModoLucideIcon, etc.) o funciones locales con if/else claro.",
    description: "Se agregaron pluralS y formatDiasCredito a src/lib/formatters y getNotaTipoColorClass, getDocEstadoColorClass, getStepIndicatorCircleClass, getDiasVencidosTone, getProfitToneClass a src/lib/ui/uiMappings. Refactorizados PortalEstadoEmbarquesCard, SidebarGroupBlock, Auditoria.tsx, PasoConfirmacionProforma, HistorialProformas, proformasColumns, PortalCotizacionConfirmDialog, EmbarqueCard (carrier icon), TabNotas, TabDocumentos, StepIndicator, DialogDuplicarEmbarque, huecoFacturacionColumns, TabProyeccion, ConceptoRowUSD/MXN, TablaCostosLocal y admin-org/Configuracion. Sin cambios visuales ni de comportamiento.",
  },
  {
    version: "8.135.4",
    date: "2026-05-14",
    type: "patch",
    title: "Optimización: queries de DB lineales y en paralelo",
    summary: "Se eliminaron loops secuenciales con await en exportación de embarques, configuración y portal — ahora las páginas y actualizaciones se piden en una sola ola paralela.",
    description: "fetchEmbarquesParaExport reemplaza el while(true) con await secuencial por un conteo exacto + Promise.all sobre todas las páginas necesarias. useEmbarquesPageController paraleliza los chunks de fetchEmbarquesListExtras al exportar CSV. updateConfiguracionItems y updateConfiguracionGlobalItems pasan a Promise.all (mismo patrón que updateConfiguracionByCategoriaClave). fetchPortalCotizacion usa join embebido (embarques(expediente)) para traer el expediente en la misma query, eliminando un round-trip condicional. Sin cambios funcionales ni de UI.",
  },
  {
    version: "8.135.3",
    date: "2026-05-12",
    type: "patch",
    title: "Embarques: avance automático a 'Arribo' al registrar la fecha real de llegada",
    summary: "Cuando se aplica una ATA (fecha_llegada_real) y el embarque está en 'Confirmado' o 'En Tránsito', su estado pasa automáticamente a 'Arribo' y se registra el evento 'Arribo a Puerto' en la línea de tiempo.",
    description: "useApplyJsonCargoFechas ahora lee el estado actual del embarque antes de actualizar y, si se está aplicando ATA y el estado es 'Confirmado' o 'En Tránsito', agrega estado='Arribo' al mismo UPDATE — nunca retrocede ni sobreescribe estados posteriores ('En Aduana', 'Entregado', 'EIR', 'Cerrado'). Además inserta un evento de tipo 'Arribo a Puerto' con la fecha ATA y descripción 'Estado cambiado a Arribo (arribo real registrado)', evitando duplicados si ya existe uno para esa fecha. Se invalida la caché de eventos del embarque junto con detalle y RPC unificado para que el tab Resumen y el tracking reflejen el cambio sin recargar.",
  },
  {
    version: "8.135.2",
    date: "2026-05-12",
    type: "patch",
    title: "Tracking: ATA inferida también actualiza el ETA del embarque",
    summary: "Cuando JSONCargo infiere la fecha real de llegada (ATA) y no hay un ETA nuevo explícito, la acción 'Actualizar embarque' ahora alinea también el ETA a esa fecha para que el tab Resumen refleje la realidad operativa.",
    description: "useApplyJsonCargoFechas: si se aplica ata sin un eta explícito, también se escribe embarques.eta = ata. Esto resuelve el caso en que el contenedor ya fue descargado en puerto destino y JSONCargo no expone un nuevo eta_final_destination — antes el resumen mostraba un ETA viejo (p.ej. 2026-05-17) mientras 'Llegada Real' ya tenía la fecha correcta (2026-05-03). Además se invalida la caché unificada del detalle (['embarques','full', id]) tras actualizar fechas, para que TabResumen se refresque sin recargar la página. TrackingLiveCard indica en el preview '(también se aplicará como ETA)' junto a la propuesta de ATA cuando no hay un cambio de ETA por separado.",
  },
  {
    version: "8.135.1",
    date: "2026-05-12",
    type: "patch",
    title: "Tracking: Actualizar embarque ahora valida que el cambio persista e infiere ATA aún sin discharging_port",
    summary: "El botón 'Actualizar embarque' del panel JSONCargo verifica que el UPDATE realmente se aplicó y la heurística de ATA cubre el caso en que JSONCargo no reporta discharging_port pero el estado indica descarga en puerto.",
    description: "useApplyJsonCargoFechas ahora ejecuta supabase.from('embarques').update(...).eq('id', ...).select('id') y lanza error si data.length === 0, evitando falsos éxitos cuando RLS bloquea el UPDATE o el registro no existe — el toast pasa a mostrar error en vez de 'Fechas actualizadas'. Adicionalmente, extractSummary (frontend) y pickEffectiveAta (edge) amplían la inferencia de ATA: además de la regla original (last_location coincide con discharging_port + estado descargado), si discharging_port viene vacío pero el container_status menciona 'Port of Discharge', 'from vessel', 'at port' o 'at terminal' junto a un patrón de descarga, también se toma timestamp_of_last_location como ATA. Caso real: TEMU7687933 / ZIM en ELIMP00203, status 'Import Gate-Out from Port of Discharge to Customer' con discharging_port nulo — ahora se propone ATA = 2026-05-03 y se aplica al embarque.",
  },
  {
    version: "8.135.0",
    date: "2026-05-11",
    type: "minor",
    title: "Tracking: ATA inferida cuando la naviera no la reporta",
    summary: "Si JSONCargo no entrega un ATA explícito pero el contenedor ya está descargado/disponible en el puerto destino, se propone la fecha del último movimiento como ATA del embarque (fecha_llegada_real).",
    description: "Se agrega pickEffectiveAta en supabase/functions/_shared/jsoncargo.ts: cuando last_location coincide con discharging_port y container_status indica discharged/unloaded/available/gate out/delivered/at yard/empty returned/released/on rail, toma timestamp_of_last_location (preferido) o last_movement_timestamp como ATA. Si solo está 'on vessel' en el puerto destino no se propone, para no adelantar la fecha real de descarga. jsoncargo-track devuelve ata_propuesta, ata_actual, ata_difiere y ata_is_inferred en el summary. extractSummary del hook aplica la misma heurística sobre raw_payload. useApplyJsonCargoFechas acepta ata y escribe embarques.fecha_llegada_real. TrackingLiveCard muestra la propuesta de ATA junto a ETD/ETA con un badge 'Inferida del último movimiento' cuando aplica, y la acción Actualizar embarque sincroniza las tres fechas con un clic. La misma forma de summary será reutilizada por los adaptadores de tracking AI a futuro.",
  },
  {
    version: "8.134.1",
    date: "2026-05-11",
    type: "patch",
    title: "JSONCargo: prefixes de leasing pool aceptan todas las navieras",
    summary: "Contenedores con prefix de leasing pool (TEMU, TCLU, TGBU, BEAU, etc.) ya no se bloquean al sincronizar con navieras como ZIM, COSCO, HMM, Yang Ming o PIL.",
    description: "El catálogo local de prefixes en src/lib/jsoncargo/containerPrefixes.ts y supabase/functions/_shared/jsoncargo.ts limitaba los prefixes de leasing pool (Triton TEMU/TGBU/TGCU/TGHU/TRHU/TRIU, Textainer TCLU/TCNU, Beacon BEAU/BMOU, Genstar GLDU/GESU, SeaCo SEGU, UES UESU, Florens CAXU/CRXU, Wan Hai WHLU, ONE TLLU) a un subset de 6 navieras (Maersk, MSC, Hapag, ONE, Evergreen, CMA CGM). Esto provocaba que embarques reales con contenedor TEMU bajo ZIM (caso ELIMP00203) mostraran 'El prefix TEMU no coincide con la naviera ZIMU' y bloqueaba el botón Sincronizar antes de llamar al API. Ahora estos prefixes mapean a las 11 navieras soportadas por JSONCargo y la validación final la hace el API. Se elimina el estado fallido cacheado en tracking_externo del embarque afectado.",
  },
  {
    version: "8.134.0",
    date: "2026-05-09",
    type: "minor",
    title: "Embarques: ETD/ETA original (cotizado) vs actual",
    summary: "El resumen del embarque ahora muestra el ETD/ETA original (con el que se cotizó al cliente) junto al actual, indicando la diferencia en días cuando han cambiado.",
    description: "Se agregan columnas etd_original y eta_original a embarques con backfill desde los valores actuales y un trigger BEFORE INSERT que copia automáticamente etd/eta al original cuando no se especifican, manteniéndolos inmutables ante actualizaciones posteriores (manuales o desde JSONCargo). En TabResumen, ETD y ETA muestran la fecha vigente y un badge 'Original: dd MMM yyyy (+/-Nd)' cuando difieren, con tooltip explicativo. Permite comparar fácilmente el plan cotizado contra la realidad operativa del embarque.",
  },
  {
    version: "8.133.1",
    date: "2026-05-09",
    type: "patch",
    title: "Tracking: ETD estimado cuando JSONCargo no reporta atd_origin",
    summary: "Si JSONCargo no devuelve atd_origin pero el contenedor ya está cargado en el buque, se infiere el ETD desde el último movimiento y se muestra como '(estimado)' en el panel de tracking en vivo.",
    description: "Se agrega pickEffectiveEtd en supabase/functions/_shared/jsoncargo.ts que toma atd_origin o, como fallback, last_movement_timestamp/timestamp_of_last_location cuando container_status indica 'Loaded on vessel', 'On vessel', 'Departed', 'In transit' o 'Sail'. jsoncargo-track devuelve además etd_origin_effective y etd_origin_is_estimated en el summary. extractSummary del hook useJsonCargoTracking aplica la misma heurística sobre raw_payload para que el panel persista la propuesta tras refresh. TrackingLiveCard muestra el ETD efectivo en el campo 'ETD origen (JSONCargo)' con un sufijo '(estimado)' y tooltip explicativo, y la propuesta de actualizar embarques.etd usa este valor.",
  },
  {
    version: "8.133.0",
    date: "2026-05-09",
    type: "minor",
    title: "JSONCargo: sincronización de ETA/ETD con confirmación",
    summary: "Al sincronizar el tracking, si JSONCargo reporta fechas distintas (atd_origin/eta_final_destination) se muestra una propuesta para actualizar ETD/ETA del embarque con un clic; antes se actualizaba la ETA en silencio.",
    description: "jsoncargo-track ya no actualiza la ETA del embarque automáticamente: ahora calcula etd_propuesta/eta_propuesta a partir de atd_origin y eta_final_destination, las compara con embarques.etd/eta y devuelve los flags etd_difiere/eta_difiere en el summary. El cron jsoncargo-track-batch también dejó de sobreescribir la ETA. TrackingLiveCard muestra un bloque azul con la propuesta de cambios y botones 'Actualizar embarque' / 'Ignorar'; al confirmar usa la nueva mutación useApplyJsonCargoFechas para escribir embarques.etd/eta vía RLS. Se añade el campo 'ETD origen (JSONCargo)' al panel de tracking en vivo.",
  },
  {
    version: "8.132.5",
    date: "2026-05-09",
    type: "patch",
    title: "JSONCargo: prefixes de leasing pool no bloquean tracking",
    summary: "Contenedores con prefix de pool de leasing (BEAU, TEMU, TCLU, TRHU, GLDU, etc.) ya no son bloqueados por mismatch con la naviera; se permite cualquier naviera soportada por JSONCargo.",
    description: "src/lib/jsoncargo/containerPrefixes.ts y supabase/functions/_shared/jsoncargo.ts: los prefixes de pools de leasing (Beacon BEAU/BMOU, Triton TEMU/TCLU/TCNU/TRHU/TRIU, Genstar GLDU/GESU/SEGU, TGBU, TGCU, UESU) ahora aceptan MAERSK, MSC, EVERGREEN, ONE, CMA_CGM y HAPAG_LLOYD en lugar de listas restringidas. Antes un contenedor BEAU6309761 con naviera EGLV (Evergreen) era bloqueado por el validador local aunque la API de JSONCargo sí lo encuentra bajo EVERGREEN. Los prefixes propietarios (MAEU, MSCU, COSU, EGHU, ZIMU, etc.) siguen validándose estrictamente.",
  },
  {
    version: "8.132.4",
    date: "2026-05-09",
    type: "patch",
    title: "JSONCargo: reconocer SCAC EGLV como Evergreen",
    summary: "Embarques con naviera 'EGLV' ahora se mapean correctamente a Evergreen en JSONCargo y permiten sincronización de tracking.",
    description: "mapNavieraToJsonCargo (frontend) y NAVIERA_MAP (_shared/jsoncargo.ts) reconocen 'eglv' (SCAC de Evergreen Marine) y lo mapean a EVERGREEN. Antes embarques capturados con naviera='EGLV' caían como 'naviera no soportada' aunque sí lo está vía Evergreen.",
  },
  {
    version: "8.132.3",
    date: "2026-05-09",
    type: "patch",
    title: "WHLC: actualizar URL de tracking externo",
    summary: "El link 'Abrir tracking en Wan Hai Lines' ahora apunta a la página oficial de consulta tracking_query.xhtml.",
    description: "src/lib/jsoncargo/externalTracking.ts: WHLC/Wan Hai ahora abre https://www.wanhai.com/views/cargo_track_v2/tracking_query.xhtml en lugar de la URL anterior con file_num.",
  },
  {
    version: "8.132.2",
    date: "2026-05-09",
    type: "patch",
    title: "Tracking externo para navieras no soportadas por JSONCargo",
    summary: "Cuando la naviera no es compatible con JSONCargo (WHLC/Wan Hai, ANL, SITC, Heung-A, Pan Ocean, Sinokor, T.S. Lines, KMTC), el tab Tracking ofrece un link directo al sitio oficial del transportista o un fallback a Track-Trace.",
    description: "Nuevo catálogo src/lib/jsoncargo/externalTracking.ts con URLs de tracking público por naviera (Wan Hai, ANL→CMA CGM, SITC, Heung-A, Pan Ocean, Sinokor, T.S. Lines, KMTC). TrackingLiveCard ahora, en el bloque 'naviera no soportada', muestra un botón 'Abrir tracking en {Naviera}' que abre el sitio oficial en nueva pestaña priorizando contenedor sobre BL. Si no hay match conocido pero existe contenedor, ofrece fallback genérico a track-trace.com. No se modifica la lógica de mapeo a JSONCargo.",
  },
];
