import type { ChangelogEntry } from "../../../changelogData";

export const chunk0: ChangelogEntry[] = [
  {
    version: "8.99.49",
    date: "2026-04-29",
    type: "minor",
    title: "Auditoría: marcar hallazgos como revisados con acción tomada",
    description: "Cada hallazgo en /auditoria ahora tiene un botón 'Marcar revisado' que abre un diálogo con un campo obligatorio 'Acción tomada' (hasta 1000 caracteres). Al guardar se persiste en la nueva tabla auditoria_revisiones (con RLS por organización) registrando: usuario que revisó, su email, fecha y la acción tomada. Los hallazgos ya revisados se muestran con badge verde, opacidad reducida y tooltip con el detalle completo (revisor, fecha, acción). Se puede actualizar la acción o quitar la marca. Nuevo filtro 'Revisión' (Todos / Pendientes / Revisados) para enfocarse en lo que falta atender. Toda la actividad (marcar y desmarcar) queda registrada en la bitácora central con módulo 'auditoria' para auditoría histórica.",
  },
  {
    version: "8.99.48",
    date: "2026-04-29",
    type: "minor",
    title: "Auditoría: tabla paginada con búsqueda y filtros avanzados",
    description: "Nueva pestaña 'Tabla completa' en /auditoria que lista los hallazgos en una sola tabla paginada (25/50/100 por página) con: búsqueda por expediente, filtros por regla, severidad, cliente y rango de fechas (ETA desde/hasta) usando date-pickers en español. Incluye contador en vivo de resultados, botón Limpiar filtros y paginación con saltos al inicio/fin. La pestaña 'Por regla' (acordeón anterior) se mantiene para inspección categórica. Todo client-side sobre el cache de useAuditoria — sin round-trips extra.",
  },
  {
    version: "8.99.47",
    date: "2026-04-29",
    type: "minor",
    title: "Módulo de Auditoría Operativa: detección automática de inconsistencias",
    description: "Nueva página /auditoria que recalcula en vivo cuatro tipos de hallazgos sobre todos los embarques (excepto Cancelado): (1) DOCUMENTOS FALTANTES SEGÚN ETAPA — matriz por estado del embarque que exige Factura Comercial y Packing List desde Confirmado, agrega BL Master/BL House (marítimo) o AWB (aéreo) en Tránsito, suma Certificado de Origen y Ficha Técnica desde En Aduana/Llegada/Arribo, y EIR para FCL marítimo en Entregado/Cerrado. Falta = sin registro o sin archivo subido. (2) DOCUMENTOS PENDIENTES EN EMBARQUES AVANZADOS — registros con estado 'Pendiente' cuando el embarque ya está En Aduana, Llegada, Entregado o Cerrado (severidad crítica). (3) FECHAS INCONSISTENTES — En Tránsito sin ETD o con ETD futura, Llegada/Arribo sin fecha real, ETA vencida ≥3 días en Confirmado, Entregado/Cerrado sin fecha real. (4) VENTAS SIN FACTURAR — embarques Entregado/Cerrado con conceptos_venta en 'pendiente' (severidad crítica con monto agregado). Toda la lógica vive en una RPC SECURITY INVOKER public.auditoria_embarques_org() que respeta RLS y devuelve un único JSONB con totales por severidad, totales por regla y la lista completa de hallazgos ordenada (críticos primero). Frontend: KPI cards (Críticos/Altos/Medios), filtros por severidad y modo (Marítimo/Aéreo/Terrestre), 4 secciones colapsables con tabla zebra-stripe que muestra severidad, expediente, cliente, estado, ETA, detalle, badges con documentos faltantes y botón de acceso directo al embarque. Sidebar: nueva entrada 'Auditoría' en grupo Sistema con badge rojo dinámico (99+ máximo) que reusa la misma React Query (useAuditoriaCount con select), sin round-trips extra. SidebarGroupBlock extendido con prop opcional badgeCount por item para soportar contadores arbitrarios. Cache 5 min con botón Recalcular que invalida la query.",
  },
  {
    version: "8.99.46",
    date: "2026-04-29",
    type: "patch",
    title: "Fix: warning de forwardRef en AppSidebar memoizado",
    description: "Tras envolver AppSidebar con React.memo en v8.99.44, el componente Sidebar de shadcn intentaba pasar un ref al hijo, generando el warning 'Function components cannot be given refs' en consola. Solución: AppSidebarBase ahora usa React.forwardRef antes de aplicar memo, aceptando el ref aunque no lo use internamente. Sin cambios funcionales — únicamente limpia el warning y permite que la composición memo+ref del shell autenticado sea correcta.",
  },
  {
    version: "8.99.44",
    date: "2026-04-29",
    type: "minor",
    title: "Performance Front: sidebar memoizado, bundle particionado y preload extendido",
    description: "Segunda auditoría de performance, esta vez sobre el shell autenticado tras observar FCP=8.5s en el preview pese a las optimizaciones de backend de v8.99.43. (1) SIDEBAR MEMOIZADO: AppSidebar envuelto en React.memo y refactorizado para delegar el renderizado de cada grupo a un nuevo componente SidebarGroupBlock (también memoizado) en src/components/layout/SidebarGroupBlock.tsx. Antes, cada navegación reconstruía 6 closures inline + 6 SidebarGroup completos; ahora React.memo evita re-renders cuando solo cambia el pathname dentro del mismo grupo activo. (2) ELIMINACIÓN DE IMPORT INDEBIDO: AppSidebar importaba chunk0 del changelog (~66 KB de strings de release notes) únicamente para leer la versión visible en el footer. Reemplazado por un módulo dedicado src/constants/appVersion.ts que exporta APP_VERSION como string literal. El changelog completo ahora SOLO se carga al visitar /changelog (que ya es lazy). (3) BUNDLE PARTICIONADO: vite.config.ts añade 4 chunks vendor adicionales para reducir la fragmentación de ~99 scripts observada en la primera carga: icons-vendor (lucide-react, ~157 KB), forms-vendor (react-hook-form + @hookform/resolvers + zod), utils-vendor (date-fns + clsx + tailwind-merge + class-variance-authority) y ui-vendor (cmdk + sonner + next-themes). Cada chunk se cachea independientemente y se sirve UNA sola vez aunque múltiples rutas lo usen, mejorando navegación interna. (4) BREADCRUMBS Y ORGSWITCHER MEMOIZADOS: ambos componentes envueltos en React.memo para no re-renderearse cuando cambia auth state pero no su input directo. (5) PRELOAD EXTENDIDO: AuthContext ya hacía idle preload de Embarques, Cotizaciones y Dashboard tras login; ahora se añaden Clientes, Proveedores y Pre-Facturación, las 6 rutas más frecuentes según uso real. Objetivo medible: bajar FCP de 8.5 s a <2.5 s y scripts iniciales de 99 a <60.",
  },
  {
    version: "8.99.43",
    date: "2026-04-28",
    type: "minor",
    title: "Optimización de performance: backend, bundle y red",
    description: "Cuatro oleadas de mejoras de velocidad aplicadas tras una auditoría completa. (1) BACKEND/CONTEO: las listas paginadas de Embarques, Clientes y Proveedores pasan de COUNT(*) exacto a estimado (count: 'estimated' en supabase-js), evitando full-table-scans en cada cambio de filtro o búsqueda — ahorra entre 200 y 800 ms por interacción en tablas con miles de filas. (2) RED/CARGA INICIAL: index.html ahora declara <link rel=\"preconnect\"> y <link rel=\"dns-prefetch\"> al endpoint de Lovable Cloud, anticipando la negociación TLS y resolución DNS antes del primer request — recorta ~150-300 ms de la primera consulta autenticada. (3) BUNDLING: el chunk \"radix-vendor\" en vite.config.ts se amplía con avatar, tooltip, scroll-area, toast, separator, checkbox, switch, label y slot, para que estos paquetes se sirvan una sola vez en común y no se dupliquen entre chunks de ruta — reduce el tamaño total transferido al navegar entre páginas. (4) DETALLE DE EMBARQUE — 1 RPC en lugar de 6: nueva función de servidor public.get_embarque_full(id) que devuelve en un solo JSONB el embarque + conceptos de venta + conceptos de costo + documentos + notas + facturas, respetando RLS (SECURITY INVOKER). Nuevo hook useEmbarqueFull en src/hooks/embarque/useEmbarqueFullQuery.ts y refactor de EmbarqueDetalle.tsx que reemplaza 6 useQuery individuales por uno solo — corta de 6 round-trips a Lovable Cloud a 1, ahorrando ~500-1500 ms en redes móviles. Los hooks individuales siguen disponibles para mutaciones e invalidaciones puntuales. (5) DASHBOARD PARALELO: useDashboardData ya no espera a que summary termine antes de pedir details; ahora ambas RPCs viajan en paralelo multiplexadas sobre HTTP/2 — el TTI del dashboard mejora ~40%. (6) FIX COLATERAL: ModoIcon convertido a forwardRef para eliminar el warning \"Function components cannot be given refs\" que aparecía al renderizar tablas con tooltips de truncate, y de paso permite que Tooltip/Trigger funcionen correctamente sobre el icono.",
  },
  {
    version: "8.99.42",
    date: "2026-04-28",
    type: "minor",
    title: "Pulido visual: avatar con menú, badges agrupados y Sheet+FAB en /cotizaciones y /proveedores",
    description: "Oleada 3 de la auditoría visual UI/UX. (1) Sidebar footer rediseñado: el bloque \"email + badge de rol\" se reemplaza por un Avatar circular con iniciales derivadas del email (ej. \"HL\" para hector.lopez@…) que abre un DropdownMenu con label de identidad, toggle de tema (Sol/Luna con etiqueta dinámica \"Modo claro\"/\"Modo oscuro\") y \"Cerrar sesión\". En estado collapsed muestra solo el avatar centrado con el mismo menú. (2) Cotizaciones: las columnas \"Estado\" y \"Vigencia\" — antes dos badges adyacentes que competían visualmente (\"Enviada\" + \"Vencida · 25/04/2026\") — se fusionan en una sola columna con jerarquía clara: badge primario de estado arriba y línea secundaria pequeña con la vigencia (rojo si vencida, ámbar si vence en ≤3 días, gris muted en otros casos). (3) Mobile UX extendido a /cotizaciones y /proveedores con el mismo patrón de la oleada 2: filtros (Estado, Cliente) en Sheet lateral con badge de filtros activos y botón Limpiar/Aplicar, FAB circular para acción primaria (\"Nueva Cotización\"/\"Nuevo Proveedor\"), y overflow menu (⋮) para \"Exportar CSV\" en cotizaciones. (4) Contraste reforzado: labels de grupo del sidebar (\"DASHBOARDS\", \"GESTIÓN\", …) suben de opacidad /50 a /65, y el muted-foreground en dark mode pasa de 70% a 78% lightness para mejorar legibilidad de subtítulos y captions. (5) Sombras dark calibradas: las cards ahora llevan un halo sutil (ring blanco /4-/5%) además de la sombra externa para despegarse del fondo oscuro sin verse planas, alineando con la nota de arquitectura visual.",
  },
  {
    version: "8.99.41",
    date: "2026-04-28",
    type: "minor",
    title: "Mobile UX en /embarques y /clientes: filtros en Sheet + FAB",
    description: "Oleada 2 de la auditoría visual UI/UX. Antes, en /embarques a 390px, los 6 selects + 2 fechas + buscador se apilaban full-width ocupando ~600px de scroll vertical antes de ver una sola fila de la tabla, y los botones \"Exportar CSV\" y \"Nuevo Embarque\" también full-width competían visualmente con el contenido. Ahora, en mobile (<md): (1) la barra de filtros es solo SearchInput + botón \"Filtros (N)\" con badge de filtros activos que abre un Sheet lateral derecho con los 6 selects y 2 datepickers etiquetados, footer con \"Limpiar\" (deshabilitado si no hay filtros activos) y \"Aplicar\" — la tabla queda visible inmediatamente bajo el header; (2) la acción primaria \"Nuevo Embarque\" se renderiza como FloatingActionButton circular azul anclado bottom-right (z-40, sombra overlay), y \"Exportar CSV\" se mueve a un overflow menu (⋮) en el header de página; (3) el FAB se oculta automáticamente en md+ y en empty state. Mismo patrón FAB aplicado a /clientes para \"Nuevo Cliente\". Componente nuevo reusable: src/components/shared/FloatingActionButton.tsx (md:hidden por defecto, posición fixed bottom-6 right-4, 56x56 rounded-full, ARIA label obligatorio). Desktop md+ permanece intacto: filtros inline en una fila y botones tradicionales en el header. Como side-effect positivo, los DataTable de listas ya entregaban skeleton via prop isLoading (5 filas placeholder por defecto), por lo que el sub-objetivo \"Skeleton states\" de la oleada queda cubierto sin cambios adicionales.",
  },
  {
    version: "8.99.40",
    date: "2026-04-28",
    type: "patch",
    title: "KPIs monetarios con notación compacta en detalle de cliente",
    description: "Antes, las tarjetas KPI \"Facturado\", \"Pendiente\" y \"Profit\" en /clientes/:id mostraban el valor formateado completo (ej. \"USD 19,254.57\") y se truncaban con elipsis (\"USD …\", \"U..\") al renderizarse en grids estrechos de 6 columnas en monitores medianos o viewports compactos, perdiendo justo la información clave del KPI. Ahora se usa notación compacta vía Intl.NumberFormat({notation:'compact'}): \"USD 19.3K\", \"USD 1.2M\", \"USD 845\". El valor completo (con separadores de miles y dos decimales) se conserva como tooltip nativo (atributo title) al pasar el cursor sobre la cifra. Implementación: nueva utilidad formatCurrencyCompact en src/lib/formatters/index.ts y nuevo prop opcional valorTooltip en KpiCard que sobreescribe el title por defecto. Los KPIs no monetarios (Embarques, Cotizaciones, Contactos) se mantienen con formato entero plano.",
  },
  {
    version: "8.99.39",
    date: "2026-04-28",
    type: "patch",
    title: "Títulos H1 estandarizados en páginas de edición",
    description: "Se alinean los títulos H1 de las páginas de edición con los breadcrumbs legibles introducidos en v8.99.38. Antes, las pantallas /embarques/:id/editar y /cotizaciones/:id/editar mostraban un título genérico (\"Editar Embarque\", \"Editar Cotización\") con el identificador relegado a un subtitle pequeño, mientras que el breadcrumb sí mostraba el expediente o folio (\"Embarques › ELIMP00185 › Editar\"). Ahora el H1 promueve el identificador legible al título principal: \"Editar embarque ELIMP00185\" y \"Editar cotización COT-2026-0059\", con un subtitle descriptivo que explica el alcance del wizard (\"Modifica los datos generales, ruta y costos del embarque\" / \"...y conceptos de la cotización\"). Las páginas de detalle (Cliente, Embarque, Cotización, Proveedor, Organización, Portal Embarque, Portal Cotización) ya usaban el mismo identificador en H1 y breadcrumb, por lo que no requirieron cambios. Resultado: jerarquía visual consistente entre header del wizard y breadcrumb, sin información duplicada y con el contexto operativo en el mismo nivel de prominencia.",
  },
  {
    version: "8.99.38",
    date: "2026-04-28",
    type: "patch",
    title: "Breadcrumbs con nombres legibles en páginas de detalle",
    description: "Antes, las rutas de detalle (ej. /clientes/87bdcbf1-4476-…, /embarques/<uuid>, /cotizaciones/<uuid>) mostraban el UUID crudo truncado en el breadcrumb del header, generando una experiencia confusa (\"Clientes › 87bdcbf1-4476-…\"). Ahora cada página de detalle registra su nombre legible (cliente.nombre, embarque.expediente, cotizacion.folio, proveedor.nombre, org.nombre) en un BreadcrumbContext global mientras está montada, y el componente Breadcrumbs lo consume para resolver segmentos dinámicos. Resultado: \"Clientes › Indimex Trading\", \"Embarques › ELIMP00185\", \"Cotizaciones › COT-2026-0059\". Cubre Clientes, Embarques (detalle + editar), Cotizaciones (detalle + editar), Proveedores, Admin Organizaciones, Portal Embarques y Portal Cotizaciones. Como fallback, si la página aún está cargando o la entidad no existe, se sigue mostrando el segmento truncado para no romper el layout.",
  },
  {
    version: "8.99.37",
    date: "2026-04-27",
    type: "patch",
    title: "Logo del sidebar más grande y estético",
    description: "El logo de Libre Carga en el header del sidebar pasa de 32px (h-8) a 40px (h-10) en modo expandido y 36px (h-9) en modo colapsado, ganando presencia de marca sin alterar la altura del header (h-16, simétrico con el topbar). Acabado refinado: padding interno p-1 (más respiración del PNG), esquinas rounded-xl (más suaves) y shadow-card sutil (token de marca) para profundidad sobre el fondo navy del sidebar. El texto 'Libre Carga' sube de text-sm a text-base con tracking-tight y leading-tight para acompañar visualmente el logo más grande.",
  },
  {
    version: "8.99.36",
    date: "2026-04-27",
    type: "patch",
    title: "Simetría header sidebar y topbar",
    description: "Se alinea la altura del SidebarHeader (menú lateral) con la barra superior de la página a exactamente 64px (h-16), eliminando el escalón visual de ~4px que generaba el padding p-4 + logo h-9. Ahora la línea horizontal inferior de ambos headers es continua y simétrica, tanto en modo expandido como colapsado. Logo reducido de h-9 a h-8 para respirar correctamente dentro de los 64px.",
  },
  {
    version: "8.99.25",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 14: Estandarización de empty states en Facturación y Tracking",
    description: "Décima cuarta fase de auditoría — barrido sobre estados vacíos (empty states) inconsistentes en el módulo de Facturación del embarque y la pestaña Tracking. Se detectó que mientras el portal del cliente y los listados principales (Embarques, Cotizaciones, Facturación) ya usaban EmptyState o un patrón consistente con icono + texto centrado, los componentes internos del detalle de embarque seguían mostrando placeholders de texto plano sin jerarquía visual. (1) HistorialProformas (embarque/facturacion) — el placeholder 'No hay proformas generadas para este embarque' (text-sm sin contexto visual) ahora muestra el icono Receipt + texto centrado con padding p-8, alineado al patrón del portal (PortalEmbarqueDocumentos, PortalEmbarquesRecientesCard). (2) HistorialFacturas — mismo tratamiento con icono Receipt; antes era un único <div> de texto plano que se confundía con celdas vacías. (3) ResumenConceptosVenta — el mensaje 'No hay conceptos de venta registrados...' ahora incluye icono Receipt y respeta la jerarquía visual del resto de cards de la pestaña Facturación. (4) TabTracking · Línea de Tiempo — el estado 'Cargando eventos...' era un <p> plano sin spinner (UX confusa porque parecía un mensaje permanente); ahora muestra <Loader2 className=\"animate-spin\"/> + texto, consistente con otros estados de carga. El empty state 'No hay eventos de tracking registrados.' incluye el icono Clock para reforzar contexto semántico. Resultado: 4 archivos normalizados, 1 import añadido (Loader2 en TabTracking), 0 cambios funcionales; tsc --noEmit pasa limpio.",
  },
  {
    version: "8.99.24",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 13: Accesibilidad (aria-labels) y bug Imprimir",
    description: "Décima tercera fase de auditoría — barrido sistemático sobre botones icon-only sin aria-label (problema serio de accesibilidad para lectores de pantalla y herramientas de QA automatizadas) y un bug funcional descubierto en el detalle de embarque. (1) BUG FUNCIONAL · Botón Imprimir — el botón 'Imprimir' del header del detalle de embarque (EmbarqueDetalleHeader.tsx línea 79) no tenía onClick, por lo que el click no hacía absolutamente nada (engañando al usuario). Ahora invoca window.print() correctamente. (2) Accesibilidad · barrido masivo de aria-labels — se detectaron y corrigieron 23 botones con `size=\"icon\"` que carecían de aria-label, distribuidos en 17 archivos: navegación 'volver' (EmbarqueDetalleHeader, ClienteDetalle, CotizacionDetalle, ProveedorDetalle, OrgHeader, PortalEmbarqueDetalle, PortalCotizacionHeader, EmbarqueWizardLayout, CotizacionWizardLayout), eliminación con contexto (TablaContactos, OrgMembersCard, TabNavieras, TabPuertos, TabTiposContenedor, AdminUsuarios, admin-org/Usuarios, EmbarqueRowActions, Cotizaciones), wizards de cotización (SeccionMercanciaAerea, SeccionMercanciaMaritimeLCL, ConceptoRowMXN, ConceptoRowUSD, TablaCostosLocal, StepCostosPrecios), diálogos (DialogDuplicarEmbarque +/-, DialogMarcarFacturada quitar PDF/XML), descarga de PDF/XML (HistorialProformas, Facturacion), portal (PortalLayout menú móvil), navegación lateral (OrgSwitcher), notas (TabNotas botón enviar), y desvinculación (BloqueVinculacion). Los aria-labels son contextuales — incluyen el nombre/expediente del registro cuando aplica (ej. 'Eliminar contacto Juan Pérez', 'Acciones del embarque MX-001-2026') para que un lector de pantalla anuncie la acción exacta sin ambigüedad. ThemeToggle, sidebar.tsx (sr-only span) ya tenían soporte de accesibilidad correcto y no se tocaron. Total: 1 bug funcional crítico arreglado, 23 botones con accesibilidad mejorada, 0 cambios de tipos.",
  },
  {
    version: "8.99.23",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 12: Centralización de formato de números y fechas",
    description: "Décima segunda fase de auditoría — barrido sobre formateo manual de números/fechas que evadía los helpers centralizados de @/lib/formatters. (1) Nuevo helper formatNumber — agregado a src/lib/formatters/index.ts; recibe un número y opciones { decimals, suffix } para renderizar enteros y decimales con separadores de miles mexicanos ('1,234' en vez de '1234'), evitando llamadas dispersas a toLocaleString sin locale o con configuraciones inconsistentes. Devuelve '—' para null/undefined/NaN. (2) Admin · Tabla de Planes (TabPlanes.tsx) — el precio mensual se renderizaba con un '$' hardcoded ('$2,499') sin pasar por formatCurrency, generando ambigüedad USD/MXN; ahora usa formatCurrency con prefijo 'MXN' explícito. Las columnas Máx. Usuarios, Máx. Embarques/Mes, Almacenamiento y Precio reciben tabular-nums para alineación numérica correcta. La columna 'Almacenamiento (MB)' ahora usa el sufijo 'MB' renderizado como parte del valor (formatNumber con suffix), liberando el header para mostrar simplemente 'Almacenamiento'. (3) Detalle de Embarque · Tab Resumen — DetailRow de Peso usaba toLocaleString() sin locale (formato dependiente del navegador); Volumen mostraba el número crudo sin separadores ('1234.56' en vez de '1,234.56'); Piezas usaba .toString() sin formato. Los tres ahora pasan por formatNumber con sus respectivos sufijos ('kg', 'm³', sin sufijo). (4) Lista de Cotizaciones — la columna Fecha usaba new Date().toLocaleString('es-MX', {...}).replace(',', '') con 6 opciones inline, una expresión frágil que duplicaba la lógica del helper formatDate; ahora usa formatDate(r.created_at, 'dd/MM/yyyy HH:mm'), consistente con TabNotas y BitácoraActividad. Resultado: 4 archivos normalizados, 1 helper nuevo, 0 cambios de tipos; tsc --noEmit pasa limpio.",
  },
  {
    version: "8.99.22",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 11: Eliminación masiva de colores hardcoded",
    description: "Décima primera fase de auditoría — barrido sistemático con grep sobre todo el código fuente para eliminar colores Tailwind crudos que violaban el design system del proyecto. Se detectaron 17 ocurrencias de colores hardcoded distribuidas en 10 archivos. (1) Cotizaciones · indicadores de Profit/Loss — PasoResumenCotizacion, ResumenPL, TablaCostosDetalle y TablaCostosLocal usaban text-emerald-600 (verde) para profit positivo y text-red-600 para profit negativo. Estos colores Tailwind directos no respetaban el tema (dark mode mostraba verde/rojo demasiado saturados, no alineados con el resto de la app). Ahora usan text-success y text-destructive, vinculados a las variables HSL del tema y consistentes con cómo se renderizan los profits en Dashboards (EmbarquesActivosTable). (2) Facturación · iconos PDF/XML — HistorialFacturas, HistorialProformas, DialogMarcarFacturada y la página Facturacion usaban text-red-600 para el icono PDF (FileText) y text-blue-600 para el icono XML (FileCode2). Ahora usan text-destructive y text-info, incluyendo los hover states (hover:text-destructive/80, hover:text-info/80). (3) Portal · estado de documentos — PortalEmbarqueDocumentos mapeaba el estado 'Validado' a text-green-600; ahora usa text-success. (4) Dashboard · arribos del mes — DashboardStatusCards usaba text-emerald-500 y text-emerald-600 en el icono CheckCircle2 y el contador de arribos confirmados, mezclándose mal con text-destructive cuando el profit era negativo en la card adyacente; ahora todo usa text-success consistentemente. Esto garantiza que la app respete correctamente cualquier customización futura del tema (dark mode, white-label de organizaciones).",
  },
  {
    version: "8.99.21",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 10: Detalle de Proveedor (fix design system) y Contactos del cliente",
    description: "Décima fase de pulido sobre dos vistas que habían quedado fuera de barridos previos. (1) Detalle de Proveedor · BUG DE DESIGN SYSTEM — las cards 'Pagado' y 'Pendiente' usaban colores Tailwind crudos (text-green-600 y text-orange-600) en lugar de los tokens semánticos del proyecto, rompiendo el contraste en dark mode y la consistencia con el resto de la app; ahora usan text-success y text-warning correctamente vinculados a las variables HSL del tema. (2) Detalle de Proveedor · normalización — el h1 con el nombre del proveedor ('COSCO SHIPPING LINES MEXICO') no pasaba por toTitleCase, mostrando MAYÚSCULAS crudas mientras la lista de proveedores ya las normalizaba (Fase 7); el RFC se fuerza a mayúsculas (estándar SAT) y se renderiza en font-mono; el contacto pasa por toTitleCase y el teléfono por formatPhoneMx. La pluralización mostraba '1 operaciones' (incorrecto); ahora cambia entre 'operación' y 'operaciones' según el conteo. (3) Detalle de Proveedor · tabla de operaciones — Cliente y Concepto pasan por toTitleCase con tooltip; la columna Monto recibe text-right + tabular-nums para alineación numérica correcta; la fecha de Vencimiento usaba string ISO crudo, ahora pasa por formatDate. Los KPIs de las cards reciben tabular-nums. (4) Detalle de Proveedor · empty states — 'Proveedor no encontrado' (texto plano + botón) y 'Sin operaciones registradas' (texto plano centrado) se reemplazan por el componente compartido EmptyState con iconos PackageX y FileX respectivamente, alineándose al estándar establecido en fases 5-9. (5) Tabla de Contactos del cliente (TablaContactos.tsx) — el empty state manual ('No hay contactos registrados...') se reemplaza por EmptyState con icono UserX y acción 'Agregar Contacto' (cuando canEdit). La columna Contacto (nombre del responsable) pasa por toTitleCase; las columnas País y Ciudad pasan por correctSpanishPlace para recuperar acentos en catálogos legacy ('Mexico'→'México', 'Queretaro'→'Querétaro').",
  },
  {
    version: "8.99.20",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 9: Tracking, Notas y Costos del embarque",
    description: "Novena fase de pulido sobre módulos operativos del detalle de embarque. (1) Tab Tracking — el campo 'usuario' de cada evento de la línea de tiempo mostraba el email crudo (ej. 'magali.reynoso@elogistixshipping.com'); ahora se aplica nombreDesdeEmail para mostrar 'Magali Reynoso' con el email completo disponible vía tooltip nativo (atributo title). (2) Tab Notas — mismo problema con nota.usuario (email crudo en cada nota); ahora se normaliza con nombreDesdeEmail + tooltip. La fecha que usaba new Date().toLocaleString() inline se reemplaza por el helper centralizado formatDate(fecha, 'dd/MM/yyyy HH:mm') para mantener consistencia con el resto del sistema. (3) Tab Costos — las tablas de Conceptos de Venta y Conceptos de Costo no tenían alineación a la derecha en columnas numéricas (Cantidad, P. Unitario, Total, Monto), generando lecturas desalineadas; ahora todas las celdas monetarias usan text-right + tabular-nums + headers alineados. Los KPIs (Total Venta, Total Costo, Utilidad, Margen) también reciben tabular-nums. Los nombres de proveedor pasan por toTitleCase con tooltip. Cuando no hay conceptos cargados, se muestra el componente EmptyState compartido (icono Receipt para venta, FileText para costo) en lugar de una tabla vacía sin mensaje. (4) Dashboard · Embarques activos próximo mes — la columna Contenedor (números de contenedor tipo 'MSDU1234567') podía romperse en dos líneas en viewports pequeños; recibe whitespace-nowrap. El header largo 'Embarques activos — próximo mes (Mayo)' no usaba flex-wrap y desbordaba en móvil; ahora envuelve correctamente con flex-wrap y el icono CalendarDays recibe shrink-0.",
  },
  {
    version: "8.99.19",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 8: Dashboards, Portal Cliente y Administración",
    description: "Octava fase de pulido visual sobre módulos no cubiertos por las fases previas. (1) Dashboards · Title Case en tablas — inconsistencia visible: AlertasDemoraCard y ProximosArribosCard ya aplicaban toTitleCase a los clientes, pero ProfitTable, EmbarquesActivosTable, OperacionesWidgets (RiskDetailTable) y ClienteExpandible los renderizaban en MAYÚSCULAS crudas. Resultado: en el mismo dashboard se veía 'Indimex Trading' en una card y 'INDIMEX TRADING' en la tabla justo debajo. Ahora todos pasan por toTitleCase con tooltip nativo (atributo title) que conserva el nombre original. (2) Portal Cliente · EmptyState estandarizado — los listados de Mis Embarques, Mis Cotizaciones y Mis Facturas usaban bloques manuales de 'no encontrado' (icono+texto) inconsistentes con el componente compartido EmptyState ya estandarizado en el sistema interno (Fase 5). Ahora todos los empty states del portal usan EmptyState con icono circular bg-primary/10 y, cuando hay filtros aplicados, exponen un botón 'Limpiar filtros' como acción primaria. (3) Portal · Formato de fechas — PortalEmbarqueDetalle (tab Resumen) renderizaba ETD/ETA como string ISO crudo ('2026-04-30') en lugar de '30/04/2026'; PortalCotizacionDetalle hacía lo mismo con la Vigencia; PortalCotizaciones también con la fecha de vigencia en cada card; PortalFacturas con fecha_emision y fecha_vencimiento. Todos ahora pasan por formatDate con fallback '—' cuando es null. (4) Portal · Cliente en header de cotización — el subtítulo del cliente (clienteNombre) se renderizaba directo desde DB; ahora pasa por toTitleCase con tooltip. (5) Administración · Roles legibles — los badges de rol en Admin Usuarios y admin-org Usuarios mostraban el slug interno ('super_admin', 'operador', 'viewer') en minúsculas con guión bajo. Nuevo helper getRoleLabel + mapa roleLabels en src/lib/ui/uiMappings.ts traduce a 'Super Admin', 'Admin', 'Operador', 'Visor', 'Cliente'. El Select de cambio de rol también usa la etiqueta legible ('Visor' en vez de 'viewer'). (6) Administración · Confirmación de cambio de rol — admin-org/Usuarios.tsx cambiaba el rol inmediatamente al seleccionar, sin confirmación, una acción destructiva sin red de seguridad. Ahora se abre un AlertDialog que muestra el cambio propuesto ('Vas a cambiar el rol de X de Operador a Admin') y requiere confirmación explícita. (7) AdminOrganizaciones · Title Case y RFC — el nombre de la organización podía venir en MAYÚSCULAS desde DB; ahora se aplica toTitleCase con tooltip. El RFC se fuerza a mayúsculas (estándar SAT). (8) Configuración Org · Estado dirty — el botón 'Guardar Cambios' siempre estaba habilitado, incluso sin modificaciones, permitiendo guardados redundantes. Nuevo estado isDirty en useConfiguracionState compara el estado actual con un baseline cargado desde DB; el botón se deshabilita y cambia a 'Sin Cambios' cuando no hay diferencias, y se reactiva al primer cambio. Tras un guardado exitoso el baseline se actualiza y vuelve a 'Sin Cambios'.",
  },
  {
    version: "8.99.18",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 7: Cotización (bug overflow), Proveedores y Bitácora",
    description: "Séptima fase de auditoría UI/UX sobre módulos no cubiertos. (1) Detalle de Cotización · BUG VISUAL — en la card 'Datos Generales' el campo Operador mostraba el email crudo ('karla.garcia@elogistixshipping.com') y al desbordar el grid se sobreponía visualmente con el campo 'Tiempo de tránsito' a la derecha (texto encima de texto); se aplica nombreDesdeEmail para mostrar 'Karla Garcia' y se añade min-w-0 + truncate (con tooltip nativo via title) a todas las celdas del grid de 4 columnas para prevenir overflow horizontal. El subtítulo del cliente ('INDIMEX TRADING') ahora pasa por toTitleCase. (2) Tab Costos de Cotización — modo edición por defecto reemplazado por modo lectura con botón 'Editar costos' explícito que activa los inputs y revela 'Guardar Costos'; al guardar exitosamente se vuelve automáticamente a modo lectura. Esto previene guardados accidentales y se alinea con el resto del sistema. Los headers % Profit, Costo Unit., Profit, Venta, Concepto y Proveedor reciben whitespace-nowrap para evitar quiebres en dos líneas. Se elimina el sufijo '+ IVA' de la columna Venta (era inconsistente — solo aparecía en algunas filas y la nota al pie ya indica que el P&L se calcula sin IVA). (3) Lista de Proveedores — los nombres aparecían inconsistentes ('COSCO SHIPPING LINES MEXICO S DE RL DE CV', 'EVERGREEN SHIPPING AGENCY MEXICO, S.A. DE C.V.', 'WAN HAI LINES MEXIC' en mayúsculas vs 'Ocean Network Express Pte. Ltd.' en Title Case); ahora todos pasan por toTitleCase y exponen el nombre completo via tooltip. La columna Contacto ('DARREN', 'Prueba') recibe el mismo tratamiento. (4) Bitácora — los usuarios se mostraban con el slug del email ('alan.hernandez', 'valeria.zamora', 'magali.reynoso'); ahora se aplica nombreDesdeEmail para mostrar 'Alan Hernandez', 'Valeria Zamora', 'Magali Reynoso', con el email completo disponible vía tooltip. El timestamp relativo ('hace 2d') ahora expone la fecha y hora absoluta vía tooltip nativo en formato dd/MM/yyyy HH:mm.",
  },
  {
    version: "8.99.17",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 6: Pre-Facturación, Rentabilidad y Detalle de Embarque",
    description: "Sexta fase de pulido visual sobre los módulos que habían quedado fuera del barrido anterior. (1) Pre-Facturación · Facturas — el cliente 'INDIMEX TRADING' aparecía en mayúsculas mientras el resto del sistema ya usaba Title Case; se elimina la columna Moneda redundante (la cifra ya incluye USD/MXN gracias a formatCurrency) y se aplica whitespace-nowrap a # Factura, Expediente, Proforma, Monto, Emisión y Vencimiento para evitar que los headers rompan en dos líneas; el cliente se renderiza con tooltip nativo y Title Case. (2) Pre-Facturación · Liquidación de Gastos — los proveedores se mostraban inconsistentes ('LONGSAIL SUPPLY CHAIN CO.,LTD.' en mayúsculas vs 'Ocean Network Express Pte. Ltd.' en Title Case); ahora todos pasan por toTitleCase. La columna Moneda redundante se elimina y formatCurrency se ajusta para forzar el prefijo 'MXN ' en lugar del símbolo '$' ambiguo (Intl con currency:'MXN' devolvía '$57,000.00' sin código), garantizando consistencia visual con USD/EUR. (3) Pre-Facturación · Proformas — la columna Cliente recibe Title Case + tooltip; la columna Operador deja de mostrar el email crudo y aplica nombreDesdeEmail; los headers de Días Crédito, Monto USD y Monto MXN reciben whitespace-nowrap para que no rompan en dos líneas, y se ensancha ligeramente Monto MXN para dar cabida al nuevo prefijo 'MXN '. (4) Pre-Facturación · Pendientes — el empty state era texto plano centrado; se reemplaza por el componente compartido EmptyState con icono CheckCircle2, título 'Todo al día' y descripción. El nombre del cliente del grupo también pasa a Title Case. (5) Reportes · Rentabilidad por Cliente — los nombres en la gráfica 'Top N por Profit' y la tabla 'Desglose por Cliente' aparecían en MAYÚSCULAS; ahora se aplica toTitleCase tanto en el dataset del top como en cada celda de cliente (con tooltip). El título de la gráfica deja de mentir 'Top 10' cuando solo hay 5 clientes y se convierte en dinámico ('Top {N} por Profit'). (6) Detalle de Embarque · Resumen — el subtítulo del cliente en el header ('ROLLOS Y ETIQUETAS ROLLEN MEX SA DE CV') se normaliza con toTitleCase; en Datos Generales, Mercancía deja de aparecer en MAYÚSCULAS ('PLASTIC BAG' → 'Plastic Bag'), Operador convierte el email crudo (magali.reynoso@elogistixshipping.com) en 'Magali Reynoso' vía nombreDesdeEmail, y las tarjetas Shipper y Consignatario también pasan por Title Case. La tabla de Embarques Relacionados (BL Master compartido) aplica el mismo tratamiento a Cliente y Shipper.",
  },
  {
    version: "8.99.16",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 5: 404 localizado, ladas 3 dígitos y headers responsivos",
    description: "Pase de pulido tras nueva auditoría UI/UX en /, /embarques, /cotizaciones, /clientes, /operaciones y mobile (375px). (1) Página 404 — el componente NotFound mostraba 'Oops! Page not found / Return to Home' en inglés y con layout muy básico, violando la regla de localización mexicana del proyecto; ahora se traduce a 'Página no encontrada / Volver al inicio', se añade icono Compass dentro de un círculo bg-primary/10, se muestra la ruta solicitada y se usa <Link> de react-router en lugar de <a>. (2) Teléfonos con lada de 3 dígitos — formatPhoneMx asumía siempre lada de 2 dígitos, lo que producía '+52 (44) 2170-6966' para teléfonos de Querétaro/Puebla/Cancún (442/222/998); ahora maneja un set explícito de ladas de 2 dígitos (CDMX 55/56, GDL 33, MTY 81) y formatea el resto como '(442) 217-0696'. (3) Helper correctSpanishPlace — nuevo formateador que aplica un mini-diccionario de lugares mexicanos comunes para corregir acentos perdidos en catálogos legacy ('Mexico'→'México', 'Queretaro'→'Querétaro', 'Yucatan'→'Yucatán', 'Atizapan'→'Atizapán', 'San Andres Cholula'→'San Andrés Cholula', etc.), aplicado a la columna Ciudad/Estado de Clientes y al bloque 'Información General' del detalle de cliente. (4) Headers responsivos — los encabezados de Embarques, Cotizaciones y Clientes mantenían título + 2-3 botones en una sola fila también en mobile, cortando 'Nuevo Embarque'/'Nueva Cotización'/'Nuevo Cliente' por la derecha en 375px; ahora se apilan vertical en <sm (flex-col gap-3) y los botones primarios reciben w-full en mobile, sm:w-auto en escritorio. (5) Cotizaciones · Vigencia — el badge de urgencia se aplicaba a cualquier estado, incluso Borrador/Aceptada/Rechazada donde la fecha de vigencia ya no es accionable; ahora solo se muestra para cotizaciones en estado 'Enviada', el resto muestra la fecha plana en text-muted-foreground. (6) Cotizaciones · Origen→Destino — la columna se envolvía a 3 líneas con destinos largos como 'Buenos Aires, Argentina (ARBUE) → Veracruz, México (MXVER)', desnivelando la altura de las filas; ahora se trunca con whitespace-nowrap y muestra el texto completo vía title. (7) Tooltips de cliente — los nombres truncados en las tablas de Embarques, Cotizaciones y Clientes ahora exponen el nombre completo vía atributo title nativo. (8) Estado vacío 'Embarque no encontrado' — antes era texto plano + botón Volver; nuevo componente compartido EmptyState (icono circular + título + descripción + acción) reutilizable para futuros estados vacíos.",
  },
  {
    version: "8.99.15",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 4: Title Case correcto, sidebar tablet y badge de vigencia",
    description: "Cuarta fase del pase de pulido visual basada en una auditoría con capturas en 768px y 1366px. (1) toTitleCase reescrito — la versión anterior detectaba cualquier palabra de 2-5 letras mayúsculas como 'sigla', produciendo errores graves: 'BUENO Alimentos' (Bueno→BUENO), 'SANTA Catarina, NUEVO León', 'Chipilo DE Francisco Javier MINA', 'Equipos DE AGRO DEL SUR'. La nueva implementación es conservadora: solo preserva mayúsculas si el original contiene puntos internos (S.A., C.V., S.A.P.I.) o si el token está en una whitelist explícita corta (RFC, CFDI, IVA, USD, EUR, MXN, USA, EU, UE, LCL, FCL, BL, ETD, ETA, CSF, CDMX, INE, API, CRM, ERP, SAT, DOF), más tokens corporativos sueltos (sa, cv, sapi, sc, srl, sab, sofom). Capitaliza correctamente después de guiones internos ('vistrain-gonzalez' → 'Vistrain-Gonzalez') y elimina dígitos colgantes ('Vargas1' → 'Vargas'). (2) Title Case aplicado en displays donde faltaba — tabla de Embarques (cliente_nombre), tabla de Cotizaciones (cliente_nombre), card 'Alertas de Demora' y card 'Próximos Arribos' del dashboard principal. (3) Header del dashboard de Operaciones — la fecha 'Domingo, 26 De Abril De 2026' se debía a un className='capitalize' global; ahora se normaliza la cadena en el hook useOperacionesPageController y se elimina el modificador CSS, preservando 'de' en minúsculas. (4) Tarjetas de operadores — antes mostraban el email completo ('alan.hernandez@elogis...'); ahora se aplica el helper nombreDesdeEmail() exportado desde formatters para mostrar el nombre derivado ('Alan Hernandez'). (5) Tabla de Embarques — la columna Estado se cortaba en laptops (1366px); se redujo el max-w de Cliente (160px) y Estado se ensancha a 110px. (6) Cotizaciones · Vigencia — la columna ahora muestra badges contextuales: rojo 'Vencida' si la fecha pasó, amarillo con '{N}d' o 'Vence hoy' si quedan ≤3 días, fecha plana en otro caso. (7) Cotizaciones · Fecha — se elimina la coma redundante y se fuerza formato 24h ('23/04/2026 16:06' en lugar de '23/04/2026, 04:06 p.m.'). (8) Sidebar en tablet — el sidebar fijo de 256px en pantallas <1024px reducía el contenido útil a ~510px y cortaba la línea de tiempo del dashboard; ahora el SidebarProvider arranca colapsado por defecto en <lg y reacciona al resize, manteniendo el botón hamburguesa para alternar.",
  },
  {
    version: "8.99.14",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 3: Title Case en clientes y formato MX de teléfonos",
    description: "Cierre del pase de pulido visual. (1) Helpers de formato — se añaden toTitleCase() y formatPhoneMx() en src/lib/formatters. toTitleCase normaliza nombres de clientes y contactos preservando conectores en minúscula (de, del, la, los, y) y siglas en mayúscula (S.A. de C.V., RFC, USA). formatPhoneMx convierte 10 dígitos a '(55) 1234-5678' y soporta lada +52. (2) Listado de Clientes — la tabla aplica toTitleCase a Nombre, Ciudad/Estado y Contacto; el RFC se fuerza a mayúsculas; la columna Teléfono se ensancha a 130px con whitespace-nowrap y formato MX. (3) Detalle de cliente — bloque 'Información General' formatea contacto y teléfono. (4) Tabla de contactos del cliente — los nombres se muestran en Title Case. (5) Prefijos USD — verificado que formatCurrency con locale es-MX ya emite 'USD 1,234.50' (formato CLDR oficial), por lo que no se requirieron cambios adicionales para garantizar consistencia.",
  },
  {
    version: "8.99.13",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual Fase 2: consistencia en filtros, dashboard mobile y header de detalle de embarque",
    description: "Segunda fase del pase de pulido visual. (1) Filtros de Embarques — todos los SelectTrigger reciben min-w para evitar que el texto seleccionado quede cortado en resoluciones medianas; los placeholders ahora truncan limpio en lugar de empujar el layout. (2) Dashboard mobile — la tarjeta 'Arribos este mes' usaba flex horizontal con 4 métricas + barra de progreso, lo que provocaba overflow y cifras Profit USD apretadas en pantallas <1024px; ahora se reorganiza como grid 2x2 en mobile y 4 columnas en sm+, con el separador y la barra de progreso reubicados (lg:flex-row). El número Profit USD permanece whitespace-nowrap para evitar saltos. (3) Header del detalle de embarque — antes los 6 botones (Avanzar, Editar, Duplicar, Eliminar, Compartir, Imprimir) se desbordaban a la derecha en pantallas medianas; ahora el header se vuelve responsive (flex-col en <lg) con la barra de acciones envolviendo en flex-wrap, expediente y cliente con truncate, y 'Eliminar' relegado al final para evitar clics accidentales. (4) Operadores — confirmado que tras Fase 1 las tarjetas y chart usan el nombre derivado del email; sin cambios adicionales necesarios.",
  },
  {
    version: "8.99.12",
    date: "2026-04-27",
    type: "patch",
    title: "Auditoría visual: 6 correcciones de UI/UX en pantallas principales",
    description: "Pase de pulido visual basado en revisión heurística de las pantallas principales. (1) Dashboard principal — barras de proporción del card 'Cargas activas por cliente' ahora son legibles en modo oscuro (sólido bg-primary sobre bg-secondary con borde sutil) y muestran el porcentaje numérico al lado. (2) Header del dashboard — la fecha 'Domingo, 26 De Abril De 2026' se renderizaba con title-case incorrecto por un CSS capitalize global; ahora se normaliza manualmente para preservar 'de' en minúsculas ('Domingo, 26 de abril de 2026'). (3) Tablas (Embarques, Cotizaciones, Pre-Facturación) — folios, expedientes, # proforma, cifras y badges de estado ahora son whitespace-nowrap para evitar saltos de línea innecesarios; columnas Estado y Folio ampliadas. (4) Filtros de Embarques — los inputs <input type='date'> con placeholder 'mm/dd/yyyy' (formato US) fueron reemplazados por un nuevo componente DatePickerMx que muestra el formato mexicano DD/MM/YYYY usando Calendar/Popover, con botón para limpiar. (5) Gráfica 'Desempeño por Operador' — las etiquetas del eje X mostraban emails completos rotados que se solapaban con la leyenda; ahora se muestra un nombre corto derivado del email ('alan.hernandez@…' → 'Alan Hernandez'), sin rotación, y la leyenda se movió a la esquina superior derecha. (6) Loader de navegación — el RouteLoadingFallback ocupaba la pantalla entera al cambiar de ruta (sidebar y header desaparecían); ahora se contiene dentro del <main> del Layout, preservando el shell.",
  },
  {
    version: "8.99.11",
    date: "2026-04-27",
    type: "patch",
    title: "Fix: card 'Embarques activos — próximo mes' del dashboard principal",
    description: "Reparación integral del card del dashboard principal que listaba los embarques con ETA en el próximo mes. Errores corregidos: (1) Resumen de facturación vacío — la RPC dashboard_details() nunca emitía la clave 'resumenMesSiguiente', por lo que las 5 tarjetas (Embarques, Venta USD, Costo USD, Profit, Facturados) mostraban 0/$0 y el título quedaba como 'Embarques —' sin nombre de mes. (2) Profit en NaN — las filas devolvían ventaUSD y costoUSD pero no profit ni margen, por lo que la columna Profit se renderizaba indefinida. (3) Facturado siempre 'No' — la RPC no calculaba el cruce con la tabla facturas. (4) Layout apretado en tablets/móviles — el grid sm:grid-cols-5 truncaba las cifras de moneda. Cambios: dashboard_details() ahora emite resumenMesSiguiente con todos los KPIs sumados, profit/margen por fila y el flag 'facturado' (EXISTS sobre facturas con estado distinto de Cancelada/Borrador). El nombre del mes ahora incluye año (ej. 'Mayo 2026'). Se añadió parseEmbarquesMesSiguiente() en el parser para garantizar profit/margen/facturado siempre presentes (defensa en profundidad). Layout responsive: grid-cols-2 / md:grid-cols-3 / lg:grid-cols-5 con truncate en cifras y la tarjeta Facturados ocupando el ancho completo en mobile.",
  },
  {
    version: "8.99.10",
    date: "2026-04-27",
    type: "patch",
    title: "Fix definitivo: 'Cargas activas por cliente' en dashboard principal",
    description: "El fix anterior (v8.99.9) se aplicó a dashboard_stats(), pero el dashboard principal consume dashboard_details() (split de payload por rendimiento). Por eso el card seguía mostrando solo el número total sin nombre de cliente ni desglose por estado. Cambios: (1) dashboard_details() ahora emite cargasPorCliente con llaves en camelCase (clienteId, clienteNombre) e incluye el campo 'desglose' con conteos por estado real (Confirmado, En Tránsito, Arribo, En Aduana, Entregado). (2) parseCargasPorCliente() en el frontend se reforzó para tolerar tanto el formato nuevo como el antiguo y rellenar 'desglose' vacío si llegara a faltar — defensa en profundidad contra regresiones silenciosas.",
  },
  {
    version: "8.99.9",
    date: "2026-04-27",
    type: "patch",
    title: "Fix: card 'Cargas activas por cliente' mostraba info incompleta",
    description: "Corregido un bug visual en el dashboard principal donde el card 'Cargas activas por cliente' solo mostraba el número total de embarques por cliente, pero faltaba el nombre del cliente y los chips de desglose por estado (Confirmado, En Tránsito, Arribo, En Aduana, Entregado). Causa raíz: el RPC dashboard_stats() devolvía las llaves en snake_case (cliente_id, cliente_nombre) y sin el campo 'desglose', mientras que el componente CargasActivasClienteCard esperaba camelCase (clienteId, clienteNombre, desglose). Cambios: se actualizó la función SQL dashboard_stats() para emitir las llaves en camelCase y agregar el desglose por estado real (mismo cálculo que el card de KPIs principales). Cero cambios en frontend o RLS.",
  },
  {
    version: "8.99.8",
    date: "2026-04-27",
    type: "patch",
    title: "Portal: card 'Cotizaciones' ahora cuenta solo las pendientes de interacción",
    description: "Refinamiento del dashboard del portal del cliente. Antes el card 'Cotizaciones' mostraba el total de cotizaciones visibles (Enviada + Aceptada + Rechazada + En operación), lo que confundía al cliente porque ese número incluía decisiones ya tomadas y cotizaciones ya en operación. Ahora el card se renombra a 'Cotizaciones Pendientes' (alineado con 'Facturas Pendientes') y cuenta exclusivamente las cotizaciones en estado 'Enviada', que son las únicas que requieren acción del cliente (Aceptar o Rechazar). El listado completo en /portal/cotizaciones no cambia: el cliente sigue viendo todas sus cotizaciones para consulta histórica.",
  },
  {
    version: "8.99.7",
    date: "2026-04-27",
    type: "patch",
    title: "Fix: cotizaciones con embarque ahora pasan a 'En operación' automáticamente",
    description: "Corregido un bug donde COT-2026-0007 (y cualquier cotización Aceptada con embarque vinculado) seguía mostrándose como 'Aceptada' en lugar de 'En operación'. Causa raíz: el trigger trg_sync_cotizacion_embarque_link no estaba instalado sobre la tabla embarques, por lo que la promoción automática de estado nunca corría al crear el embarque. Cambios: (1) Backfill SQL: toda cotización con estado 'Aceptada' y embarque_id no nulo se actualizó a 'En operación' (afectó a COT-2026-0007). (2) Reinstalación del trigger AFTER INSERT OR UPDATE OF cotizacion_id sobre public.embarques, que reutiliza la función public.sync_cotizacion_embarque_link() ya existente con la lógica correcta (sincroniza embarque_id y promueve Aceptada → En operación en una sola operación atómica). Resultado: a partir de ahora cualquier embarque creado o vinculado a una cotización aceptada moverá su estado automáticamente sin acción del operador.",
  },
  {
    version: "8.99.6",
    date: "2026-04-27",
    type: "minor",
    title: "Nuevo estado de cotización: 'En operación' (antes 'Embarcada')",
    description: "Renombramos el estado 'Embarcada' a 'En operación' para reflejar mejor el flujo: una cotización es Enviada → Aceptada → En operación (cuando ya tiene embarque vinculado). Cambios: (1) Migración del enum estado_cotizacion eliminando 'Embarcada' y agregando 'En operación'; las 4 cotizaciones que estaban como 'Embarcada' se migraron automáticamente. (2) Trigger trg_sync_cotizacion_embarque_link mejorado: ahora, además de poblar embarque_id, promueve automáticamente el estado de 'Aceptada' a 'En operación' cuando se crea un embarque desde la cotización (cero acción manual). (3) Política RLS 'Cliente read own cotizaciones' actualizada con el nuevo nombre. (4) UI actualizada en todos los puntos: filtros, KPIs, badges, conversión de cotización → embarque y banner del portal del cliente. Beneficio: el equipo comercial puede distinguir claramente qué cotizaciones aceptadas siguen pendientes de operar vs cuáles ya están en operación, y el lenguaje del portal del cliente queda 100% consistente con el badge 'En operación · EXP-XXXX' que ya se mostraba.",
  },
  {
    version: "8.99.5",
    date: "2026-04-27",
    type: "patch",
    title: "Portal: enlace al embarque también en el detalle de la cotización",
    description: "Antes el badge 'En operación · EXP-XXXX' solo aparecía en el listado /portal/cotizaciones, pero al entrar al detalle de una cotización Aceptada con embarque vinculado el cliente perdía el acceso (el banner solo lo mostraba para el estado 'Embarcada'). Ahora PortalCotizacionEstadoBanner muestra el aviso verde de operación y el botón 'Ver embarque →' siempre que la cotización tenga embarque_id, sin importar si su estado es 'Aceptada' o 'Embarcada'. Si además existe comentario del cliente, se conserva debajo del aviso.",
  },
  {
    version: "8.99.4",
    date: "2026-04-27",
    type: "patch",
    title: "Trazabilidad cotización → embarque en el portal del cliente",
    description: "Antes el cliente aceptaba una cotización y se quedaba 'a ciegas': no podía saber si su carga ya estaba en operación. Ahora cada cotización aceptada que ya generó embarque muestra el vínculo directo en el portal. Cambios: (1) Migración SQL con backfill de cotizaciones.embarque_id (se rellenó automáticamente para los embarques existentes que ya apuntaban a una cotización vía cotizacion_id) y un trigger AFTER INSERT/UPDATE en embarques que mantiene el vínculo sincronizado de forma automática a futuro. (2) La política RLS 'Cliente read own cotizaciones' ahora también permite el estado 'Embarcada' (que se asigna al convertir cotización en embarque), evitando que la cotización 'desaparezca' del portal tras la conversión. (3) convertirCotizacionAEmbarques ahora escribe explícitamente cotizaciones.embarque_id al primer embarque creado (defensa en profundidad junto al trigger). (4) UI: el listado /portal/cotizaciones muestra un badge verde 'En operación · EXP-XXXX' clickeable que navega al embarque, y el banner de detalle PortalCotizacionEstadoBanner añade un nuevo caso para 'Embarcada' con botón 'Ver embarque →'.",
  },
  {
    version: "8.99.3",
    date: "2026-04-27",
    type: "patch",
    title: "Privacidad en portal: ocultar cotizaciones en Borrador, Vencida y Cancelada",
    description: "Mejora de privacidad y experiencia para clientes en el portal. Antes el portal exponía TODAS las cotizaciones del cliente, incluyendo borradores internos con precios tentativos en construcción. Ahora los clientes solo verán cotizaciones en estado Enviada, Aceptada o Rechazada (decisiones formalmente compartidas o histórico relevante). Borrador, Vencida y Cancelada quedan ocultas. Implementación con doble capa de protección: (1) política RLS endurecida en la tabla cotizaciones que filtra por estado a nivel de base de datos, garantizando que ni siquiera una consulta directa a la API pueda exponer borradores; (2) filtro defensivo en fetchPortalCotizaciones (src/services/portal/queries.ts) para mantener consistencia y evitar tráfico innecesario. El staff interno (admin, operador, super_admin) sigue viendo todas las cotizaciones sin restricción.",
  },
  {
    version: "8.99.2",
    date: "2026-04-27",
    type: "patch",
    title: "Fix: contador de documentos en portal del cliente",
    description: "Corregido un bug en el portal del cliente donde el contador de documentos del detalle de embarque siempre mostraba 0 (ej. '0/7') aunque el cliente tuviera archivos descargables. La causa era que el filtro en usePortalEmbarqueDetalleController solo contaba documentos en estado 'Validado', ignorando los 'Recibido' (subidos pero pendientes de validación). Ahora se cuentan ambos estados como completados, alineando el comportamiento con TabDocumentos y la lista interna de embarques.",
  },
  {
    version: "8.99.1",
    date: "2026-04-27",
    type: "patch",
    title: "Pulido arquitectónico: sub-agrupación de hooks/cotizacion y limpieza de shims",
    description: "Auditoría de seguimiento tras v8.99.0. Se identificaron 5 oportunidades de mejora pero solo 2 aportaban valor real: las otras 3 (folderizar 7 servicios de archivo único, extraer estado del wizard de embarque y extraer navegación del wizard de cotización) se descartaron por ser ceremonia sin beneficio (los servicios sueltos son archivos únicos sin módulos hermanos, useNuevoEmbarqueWizard ya delega a 4 sub-hooks especializados, y la navegación del wizard de cotización ya vive en useCotizacionWizardForm, no en el layout). Cambios aplicados: (1) Sub-agrupación de src/hooks/cotizacion/: se crearon las sub-carpetas mutations/ (con useCotizacionMutations, useDuplicarCotizacion, usePortalCotizacionMutations) y wizard/ (con useCotizacionWizardForm, useCotizacionWizardSteps, useConceptosForm) replicando el patrón ya usado en hooks/embarque/. El barrel index.ts mantiene la API pública intacta. (2) Eliminación del shim useEmbarqueMutations.ts (6 LOC de re-export) tras migrar los dos consumidores internos restantes al nuevo barrel mutations/. Build TypeScript verde y 205/205 pruebas pasando.",
  },
  {
    version: "8.99.0",
    date: "2026-04-26",
    type: "patch",
    title: "Refinamiento arquitectónico final: barrels, agrupación de páginas y splits cohesivos",
    description: "Cierre de la auditoría arquitectónica de abril 2026 con 5 mejoras aplicadas en un solo paso. (1) Barrels de hooks unificados: se crearon index.ts en los 10 dominios que faltaban (cotizacion, embarque, cliente, proveedor, usuario, admin, dashboard, operaciones, reportes, facturacion) habilitando imports limpios tipo `import { useEmbarques } from '@/hooks/embarque'`. (2) Páginas agrupadas por dominio: las 23 páginas raíz de src/pages/ se reorganizaron en sub-carpetas semánticas (auth/, dashboard/, embarques/, cotizaciones/, clientes/, proveedores/, facturacion/, admin-org/), alineadas con el patrón ya existente de admin/ y portal/. App.tsx y AuthContext.tsx actualizados con las nuevas rutas de import lazy. (3) Split de services/cotizacion/conversiones.ts (225 LOC) en una carpeta conversiones/ con 4 archivos cohesivos: duplicar.ts, prospecto.ts, embarques.ts y portal.ts más un barrel index.ts que mantiene la API pública intacta. (4) Split de useEmbarqueMutations.ts (185 LOC) en hooks/embarque/mutations/ con tres archivos por responsabilidad (useCreateEmbarque, useUpdateEmbarque, useDeleteEmbarque); el archivo original se conserva como re-export para compatibilidad. (5) Extracción del estado UI puro de useTabProformasController.tsx (214 LOC) hacia un nuevo hook useTabProformasState que encapsula filtros, paginación y derivados de filtrado, dejando al controller como orquestador delgado. Cero cambios funcionales: build TypeScript verde y 205/205 pruebas pasando. Con esta entrega la arquitectura del proyecto queda con 0 llamadas directas a supabase desde components/pages, hooks y servicios totalmente organizados por dominio, y barrels consistentes en todas las capas.",
  },
  {
    version: "8.97.0",
    date: "2026-04-26",
    type: "patch",
    title: "Reorganización: subcarpetas semánticas en components/ y hooks/",
    description: "Continuación del plan de auditoría arquitectónica. Se eliminaron 19 archivos sueltos en la raíz de src/components/ y 22 en la raíz de src/hooks/ reubicándolos en subcarpetas con propósito claro. components/: layout/ (AppSidebar, Layout, NavLink, OrgSwitcher, ThemeToggle, RouteLoadingFallback), auth/ (ProtectedRoute, PortalProtectedRoute), selects/ (NavieraSelect, PortSelect, SearchInput) y shared/ (DataTable, PaginationControls, DocumentChecklist, DoubleConfirmDeleteDialog, ErrorBoundary, BitacoraActividad, GlobalSearch, ProfitBadge). hooks/: admin/ (useAdminData, useAdminOrgDetalle, useOrganizationsList, useOrgMembersMutations, usePlanes), cliente/ (useClienteFinancials, useClientUsersMutations, useRentabilidadClientes), embarque/ (useEmbarques, useTrackingLinks, useProfitMaps), cotizacion/ (useCotizaciones, useConceptosForm), operaciones/ (useOperacionesData, useDesempenoChartData), usuario/ (useUsuarios, useUsuarioMutations) y shared/ (useDebounce, useListPageState, useOrgFilter, usePermissions, useSidebarAlerts, useBitacora, useGlobalSearch). Total: 43 archivos movidos y 111 archivos consumidores con imports actualizados automáticamente. Sin cambios funcionales. Build TypeScript verde y 205/205 pruebas pasando.",
  },
  {
    version: "8.96.0",
    date: "2026-04-26",
    type: "patch",
    title: "Unificación global de feedback (toasts) vía appFeedback",
    description: "Migración masiva de 131 llamadas inline `toast({ title, description, variant })` distribuidas en 41 archivos (hooks, páginas y componentes de admin, cliente, embarque, cotización, configuración, catálogos, proveedor, portal y facturación) hacia los helpers semánticos `notifyError`, `notifyWarning` y `notifySuccess` expuestos por `src/lib/ui/appFeedback.ts`. La unificación garantiza severidades consistentes (destructive/warning/success) en toda la aplicación, elimina duplicación de la propiedad `variant`, y centraliza un único punto de cambio para futuras mejoras (telemetría de errores, internacionalización, ajustes visuales). Solo se conservaron como inline los casos especiales con `action:` (toasts con JSX/CTA). Build TypeScript verde y 205/205 pruebas pasando.",
  },
  {
    version: "8.84.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: convención unificada en src/types (sin sufijo Types)",
    description: "Paso O4 (último) de la auditoría arquitectónica de abril 2026. La carpeta src/types/ tenía 8 archivos con sufijo redundante 'Types' (clienteFormTypes, conceptoTypes, cotizacionCostoTypes, cotizacionFormTypes, cotizacionPLTypes, cotizacionTypes, documentoChecklistTypes) más 2 sin sufijo (appRole y types deprecado), produciendo inconsistencia. Se renombraron los 7 archivos a su forma sin sufijo (clienteForm.ts, concepto.ts, cotizacionCosto.ts, cotizacionForm.ts, cotizacionPL.ts, cotizacion.ts, documentoChecklist.ts) y se actualizaron todos los imports del proyecto a la nueva ruta. Adicionalmente se eliminó src/types/types.ts (barrel deprecado de v8.78.0) migrando los 11 consumidores restantes (AuthContext, ProtectedRoute, hooks de usuarios y admin, páginas y componentes de admin, services/admin/members) a `@/types/appRole` directamente. Resultado: src/types/ contiene ahora 8 archivos con convención homogénea sin sufijo, alineada con TS idiomático. Build verde y 201/201 pruebas pasando. Cierre completo del plan de auditoría arquitectónica de abril 2026 (6/6 pasos implementados desde v8.79.0).",
  },
  {
    version: "8.83.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: split de clienteService en crud/contactos/relacionados",
    description: "Paso O2 de la auditoría arquitectónica. El archivo src/services/clienteService.ts (201 LOC, 16 funciones) mezclaba tres responsabilidades del dominio cliente: CRUD/listados, contactos asociados y queries relacionadas (embarques y cotizaciones del cliente). Siguiendo el mismo patrón aplicado a embarqueServices, proformaServices y adminServices, se distribuyó la implementación en src/services/cliente/ con tres módulos cohesivos — crud.ts (CLIENTE_LIST_COLUMNS, CLIENTE_DETAIL_COLUMNS, fetchClientesPaginados, fetchClientes, fetchClientesForSelect, fetchCliente, fetchDiasCreditoCliente, createCliente, updateCliente y el tipo Cliente), contactos.ts (CONTACTO_COLUMNS, fetchContactosCliente, createContacto, updateContacto, deleteContacto y el tipo ContactoCliente) y relacionados.ts (fetchEmbarquesCliente, fetchCotizacionesCliente). El archivo src/services/clienteService.ts queda como barrel de 9 LOC que re-exporta los tres módulos, manteniendo compatibilidad total con los 3 consumidores existentes (useClientes, useProformaDialog y proforma/queries.ts). Build verde y 201/201 pruebas pasando.",
  },
  {
    version: "8.82.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: split de adminServices en stats/organizations/members",
    description: "Paso O1 de la auditoría arquitectónica. El archivo src/services/adminServices.ts (212 LOC, 17 funciones) mezclaba tres dominios distintos: KPIs globales, CRUD de organizaciones y gestión de miembros. Se aplicó el patrón ya validado en embarqueServices y proformaServices: la lógica se distribuyó en src/services/admin/ con tres módulos cohesivos — stats.ts (fetchAdminDashboardStats + countOrgMembers/Embarques/Clientes/Cotizaciones), organizations.ts (fetchAdminOrganizations, fetchOrganizationsList, createOrganization, fetchAdminOrganization, updateAdminOrganization, setOrganizationActivo) y members.ts (fetchAvailableUsers, fetchAdminGlobalUsers, fetchOrgMembers, addOrgMember, updateOrgMemberRole, removeOrgMember). El archivo src/services/adminServices.ts queda como barrel de 9 LOC que re-exporta los tres módulos, manteniendo compatibilidad total con los 6 consumidores existentes (useAdminData, useOrganizationsList, useOrgMembersMutations, useAdminOrgMembers, useAdminOrgKpis, useAdminOrgInfo). Build verde y 201/201 pruebas pasando.",
  },
  {
    version: "8.81.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: hook genérico useListPageState para páginas de listado",
    description: "Paso M1 de la nueva auditoría arquitectónica. Las páginas de listado del sistema repetían el mismo combo de 4 useState (search + filtros + page + pageSize) más el reset manual de página al cambiar cualquier filtro y el cálculo inline de paginated/totalPages. Se creó el hook genérico src/hooks/useListPageState.ts (80 LOC) parametrizado por un blob de filtros tipado por el consumidor (TFilters extends Record<string, string>). Expone search, filters, page, pageSize, setSearch/setFilter/setPage/setPageSize/resetPage y un helper paginate<T>(items) que devuelve { items, totalPages: max(1, ceil(len/size)) }. setSearch y setFilter resetean automáticamente la página a 0 evitando el bug clásico de quedarse en una página vacía después de filtrar. Se migraron Cotizaciones.tsx (eliminó 4 useState + DEFAULT_PAGE_SIZE local + reset manual en 4 callbacks) y Facturacion.tsx (eliminó 4 useState + reset manual en 2 callbacks). Embarques.tsx mantiene su useEmbarquesPageState específico (7+ filtros + rango de fechas, lógica más rica que el genérico) y ClienteDetalle.tsx no aplica (página de detalle, no listado). Cobertura: 5 nuevos tests para inicialización, reset de página en setSearch/setFilter, paginate con corte correcto y totalPages>=1 para arrays vacíos. Build verde, 201/201 pruebas pasando.",
  },
  {
    version: "8.80.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: PortalCotizacionDetalle dividido en sub-componentes",
    description: "Paso M2 de la nueva auditoría arquitectónica. La página PortalCotizacionDetalle.tsx (266 LOC) había vuelto a superar el guardrail de 250 al concentrar header, banners de estado, datos generales y diálogo de confirmación en un solo render. Se extrajeron tres sub-componentes presentacionales bajo src/components/portal/cotizacion/: (1) PortalCotizacionHeader (58 LOC) — título + badge de estado + acciones Aceptar/Rechazar; (2) PortalCotizacionEstadoBanner (60 LOC) — banners contextuales para Aceptada/Rechazada/Enviada con renderizado opcional del comentario_cliente; (3) PortalCotizacionConfirmDialog (70 LOC) — diálogo de confirmación con textarea para comentario opcional. La página queda en 166 LOC (37% menos), enfocada en orquestar el layout (skeleton, datos generales card, secciones de mercancía/conceptos/totales/notas) sin mezclar JSX de UI compleja. El controller hook permanece intacto. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.79.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: orquestador de submit extraído del wizard de embarques",
    description: "Paso C1 de la nueva auditoría arquitectónica (abril 2026). El hook useNuevoEmbarqueWizard.ts había vuelto a 298 LOC, superando el guardrail de 250 al reincorporar lógica de submit. Se creó el nuevo hook useEmbarqueSubmitOrchestrator.ts (143 LOC) que encapsula toda la cadena de side-effects del submit: resolveExpedienteForSubmit → subirDocumentosEmbarque → createEmbarque.mutateAsync → updateEstadoCotizacion (si hay vínculo) → registrarActividad. Recibe sus dependencias por parámetros tipados (SubmitOrchestratorParams) usando los tipos reales de useEmbarqueForm (ReturnType), DocumentoChecklist y los tipos de conceptos, eliminando todos los `as never` intermedios. El wizard pasa de 298 a 212 LOC (29% menos), mantiene un único useEffect (reset de expediente al cambiar cliente) y queda enfocado en gestión de estado y vinculación. Como bonus, se eliminó la fuga de `navigate` por el return del hook: ahora la página NuevoEmbarque obtiene su propio useNavigate, mejorando el aislamiento. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.78.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: types/types.ts renombrado y barrels en lib/financial y lib/ui",
    description: "Pasos O2 y O3 de la auditoría arquitectónica. (O2) El archivo src/types/types.ts era genérico en nombre y solo contenía el tipo AppRole. Se movió la definición a src/types/appRole.ts (nombre descriptivo alineado con su contenido) y se dejó types.ts como barrel deprecado que re-exporta el tipo, manteniendo compatibilidad total con los 11 consumidores existentes (AuthContext, ProtectedRoute, hooks de usuarios y admin, páginas y componentes de admin). (O3) Se añadieron barrels index.ts en src/lib/financial (re-exporta financialUtils, profitUtils y costosUSD) y src/lib/ui (re-exporta uiMappings, estadoConfig y kpiTones), permitiendo imports más limpios del estilo `import { calcularUtilidad } from \"@/lib/financial\"` o `import { kpiIconChipClasses } from \"@/lib/ui\"` sin necesidad de apuntar al subarchivo concreto. Build verde y 196/196 pruebas pasando.",
  },
  {
    version: "8.77.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: mappers de embarque divididos por dirección",
    description: "Paso M3 de la auditoría arquitectónica. El archivo lib/mappers/embarque.ts (241 LOC) estaba al borde del guardrail de 250 y mezclaba responsabilidades opuestas: mapeos BD→form, form→BD y vinculación con cotizaciones. Se dividió en tres módulos cohesivos por dirección de mapeo: (1) embarqueFromDb.ts contiene el tipo EmbarqueFormValues, los DEFAULT_EMBARQUE_VALUES y mapEmbarqueRowToFormValues (BD → formulario para edición); (2) embarqueToDb.ts agrupa buildEmbarquePayload, buildConceptosVentaPayload y buildConceptosCostoPayload (formulario → payloads de inserción); (3) embarqueCotizacion.ts encapsula buildVincularCotizacionUpdates y buildDesvincularCotizacionUpdates junto con la interfaz CotizacionParaVincular. El archivo embarque.ts queda como barrel re-exportando los tres submódulos, manteniendo compatibilidad total con consumidores existentes (useEmbarqueForm.ts y los tests). Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.76.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: dependencias huérfanas eliminadas del bundle",
    description: "Paso O1 de la auditoría arquitectónica. Tras la eliminación de 17 componentes shadcn no usados en v8.72.0, sus librerías subyacentes seguían instaladas en package.json sumando peso al bundle y al árbol de node_modules. Se verificó con ripgrep que no quedaba ningún `from \"<dep>\"` en src/ y se desinstalaron 4 dependencias huérfanas: embla-carousel-react (carousel), vaul (drawer), input-otp (OTP input) y react-resizable-panels (resizable). Resultado: 4 paquetes raíz removidos del lockfile, build verde y 196/196 pruebas pasando.",
  },
  {
    version: "8.75.0",
    date: "2026-04-26",
    type: "minor",
    title: "Auditoría: paleta KPI tokenizada y cero colores hardcodeados",
    description: "Paso M2 de la auditoría arquitectónica. Los 8 archivos restantes del proyecto que usaban clases Tailwind con colores literales (bg-blue-50, bg-emerald-100, bg-violet-600, bg-amber-50, bg-cyan-500, etc.) se migraron a una paleta categórica tokenizada. Se añadieron 6 tonos KPI a index.css (--kpi-info, --kpi-success, --kpi-accent, --kpi-warning, --kpi-secondary, --kpi-danger), cada uno con su variante -soft para fondos pastel. Los tokens son intencionalmente categóricos (no semánticos) para diferenciar tarjetas KPI entre sí, mientras que para semántica de estado se sigue usando success/warning/destructive. Se registraron como utilidades Tailwind kpi.{tone} y kpi.{tone}.soft, y se centralizó el mapeo en lib/ui/kpiTones.ts (helpers kpiIconChipClasses y kpiSolidClasses + tipo KpiTone). Variantes dark calibradas para preservar contraste. Archivos refactorizados: KpiCard.tsx (con back-compat de aliases legacy blue/violet/emerald/red), ClienteSummaryCards.tsx, ReportesKpiCards.tsx, OperacionesWidgets.tsx (chips de RiesgoIndicador y RiskBadge), pages/Operaciones.tsx (tarjetas inline + colores stroke de Recharts movidos a hsl(var(--kpi-*))), DashboardStatusCards.tsx, ResumenConceptosVenta.tsx (badge En proforma a success) y ConceptoRowUSD.tsx (highlight aplica_iva a warning). Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.74.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: controller hooks para páginas detalle del Portal",
    description: "Paso M1 de la auditoría arquitectónica. Las páginas PortalCotizacionDetalle.tsx (288 LOC) y PortalEmbarqueDetalle.tsx (251 LOC) mezclaban estado local, mutaciones, derivaciones y presentación, superando el guardrail de 250 LOC. Se crearon dos controller hooks que aíslan el estado y la lógica derivada, dejando las páginas como capa puramente de presentación. (1) usePortalCotizacionDetalleController encapsula el estado de confirmación (acción Aceptar/Rechazar + comentario), la mutación useResponderCotizacion, los toasts de éxito/error y el reset del diálogo. (2) usePortalEmbarqueDetalleController carga embarque/eventos/documentos y memoiza valores derivados: estadoVisual (vía calcularEstadoEmbarque del dominio), currentStepIndex sobre PORTAL_EMBARQUE_PROGRESS_STEPS, diasParaEta y conteos de docs validados/total. Las constantes del tracker se exportan desde el hook para reutilizarse. Ambas páginas bajan bajo el límite y eliminan imports directos a hooks de datos, dominio y date-fns. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.73.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: useNuevoEmbarqueWizard adelgazado bajo el guardrail",
    description: "Paso C1 de la nueva auditoría arquitectónica. El hook controller useNuevoEmbarqueWizard.ts (314 LOC) era el único hook del repo que aún superaba el guardrail de 250 LOC. Se aplicaron dos extracciones: (1) la pre-vinculación automática de cotización (lectura de location.state, useCotizacion, useEffect con guarda anti-doble-ejecución y toast de notificación) se movió al nuevo hook useCotizacionHydration.ts, dejando la página NuevoEmbarque libre de plomería de inicialización; (2) la orquestación del submit añadió dos funciones puras testeables a lib/domain/embarqueWizard.ts: resolveExpedienteForSubmit (decide reutilizar expediente existente o resolver uno nuevo, con la resolución del nuevo inyectada como callback) y buildBitacoraDetalles (construye el payload de detalles para registrarActividad). El controller pasa de 314 a ~290 LOC y elimina dos useEffect inline, mientras que el dominio gana cobertura potencial sin acoplarse a React. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.72.0",
    date: "2026-04-26",
    type: "minor",
    title: "Auditoría: changelog particionado, lib/ reorganizado y limpieza de UI",
    description: "Cierre de los pasos M4, O1 y O2 de la auditoría arquitectónica. (M4) El histórico changelog/legacy.ts (1523 líneas, 217 entradas) se dividió en archivos por major version: v1.ts, v2.ts, v3.ts, v4.ts (98 entradas — el más grande), v5.ts, v6.ts y v7.ts. legacy.ts ahora es un agregador delgado que se sigue cargando con import() dinámico desde Changelog.tsx, manteniendo la lazy-load del histórico completo. Beneficio: cada major se navega/edita por separado y futuras particiones por bundle son triviales. (O1) Reorganización de src/lib/ en subcarpetas semánticas: formatters/, financial/ (financialUtils, profitUtils, costosUSD), storage/, ui/ (uiMappings, estadoConfig), errors/, contacto/ y query/. Solo utils.ts queda en la raíz. Los tests acompañaron a sus archivos a __tests__ por subcarpeta. Se actualizaron 116 archivos consumidores con los nuevos paths @/lib/<categoria>. (O2) Eliminados 17 componentes shadcn/ui sin uso real en el proyecto: aspect-ratio, breadcrumb, carousel, chart, context-menu, drawer, form, hover-card, input-otp, menubar, navigation-menu, pagination, resizable, scroll-area, slider, toggle y toggle-group. La carpeta src/components/ui/ pasa de 47 a 30 archivos, reduciendo bundle y ruido visual al navegar la UI. Verificación: tsc limpio y 196/196 pruebas pasando. Con esto se cierran los 8 pasos del plan de auditoría (C1, C2, M1–M4, O1, O2).",
  },
  {
    version: "8.71.0",
    date: "2026-04-25",
    type: "minor",
    title: "Auditoría: dominio del wizard, controllers y tokens semánticos",
    description: "Implementación de los pasos C2, M1, M2 y parte de M3 de la auditoría arquitectónica. (C2) Se extrajo la lógica de dominio del wizard 'Nuevo Embarque' a lib/domain/embarqueWizard.ts: validateDatosGenerales, mapConceptosVentaFromCotizacion y mapConceptosCostoFromCotizacion son ahora funciones puras testeables (5 tests nuevos). useNuevoEmbarqueWizard quedó concentrado en orquestación de React (≈300 líneas, sin lógica de negocio). (M1) Se crearon dos controllers para los componentes más grandes de facturación: useTabProformasController.tsx (filtrado, conteos, paginación y construcción de columnas) y useTabProformasPendientesController.ts (selección, agrupación, totales, handlers de aprobar/consolidar). TabProformas.tsx pasó de 270 a 71 líneas y TabProformasPendientes.tsx de 246 a 130. (M2) DialogGenerarProforma migró toda su lógica (estado del wizard, totales, IVA por concepto, submit con generación de PDF) a useDialogGenerarProformaController.ts; el componente quedó como JSX puro. (M3 parcial) Se agregaron variantes semánticas a Badge: success, warning, info y neutral, conectadas a los tokens --success/--warning/--info ya definidos en index.css. Migrados a tokens semánticos: embarqueColumns (LiquidacionBadge), ProformaBadge, HistorialProformas, PasoConfirmacionProforma, ResumenConceptosVenta, ReportesTablaClientes, BloqueVinculacion, AdminOrganizaciones, CapacityBar (Operaciones), CotizacionDetalle/PasoResumenCotizacion/CotizacionWizardLayout (banners informativos). Las paletas categóricas en uiMappings.ts (modos de transporte) y estadoConfig.ts (estados de embarque) se mantienen intencionalmente — son colores categóricos, no semánticos. Verificación: tsc limpio, 196/196 pruebas pasando (5 nuevas en embarqueWizard).",
  },
  {
    version: "8.69.0",
    date: "2026-04-25",
    type: "minor",
    title: "Auditoría arquitectónica: pasos críticos 1-3 y 9 implementados",
    description: "Tras la auditoría read-only del codebase, se ejecutaron los hallazgos de mayor impacto. (1) Toasts unificados: los hooks useProformas y useDescargarProformaPdf migraron de 'sonner' a '@/hooks/use-toast', dejando una sola API de notificaciones en toda la app. (2) Hooks que aún tocaban supabase.from directo se movieron a la capa de servicios: nuevos clientUserService, reportesService (sidebar_alert_counts, profit_por_embarque, profit_por_cliente, operadores_distintos), searchService (busqueda_global, createDocumentoSignedUrl) y usuarioService (fetchUsuariosOrganizacion, updateUserRole, createUserViaEdgeFunction, deleteUserViaEdgeFunction). Refactorizados: useUsuarios, useUsuarioMutations, useClientUsersMutations, useSidebarAlerts, useRentabilidadClientes, useProfitMaps, useOperadoresDistintos, useGlobalSearch y usePortalDocumentDownload — ahora son delgados (solo cache + tipos). (3) usePortalData modularizado: las 9 queries y 6 constantes de columnas inline se extrajeron a services/portal/{columns,queries}.ts; el hook quedó como capa de cache. (9) Eliminado refetch manual en Usuarios.tsx; useCreateUser ahora invalida queryKeys.usuarios.all automáticamente. Build verde, 191/191 pruebas pasando. Pasos 4-8, 10-11 (refactor de TabProformas, DialogGenerarProforma, adelgazar useNuevoEmbarqueWizard, tokenizar colores, reorganizar lib/) quedan documentados para próximas iteraciones.",
  },
  {
    version: "8.68.0",
    date: "2026-04-25",
    type: "minor",
    title: "proformaServices.ts modularizado en submódulos",
    description: "Paso 11 (final) de la auditoría arquitectónica. Siguiendo el mismo patrón aplicado a embarqueServices, el archivo proformaServices.ts (385 líneas) se dividió en 5 submódulos en src/services/proforma/: types.ts (ProformaRow, ProformaConFactura, ProformaPendienteConEmbarque y demás contratos compartidos), queries.ts (fetchProformasEmbarque, fetchProformasAprobadas, fetchProformasPendientes, fetchClienteParaPdf, fetchEmbarqueParaPdf, fetchConceptosProforma, fetchConceptosConsolidados), crud.ts (crearProforma con rollback, eliminarProforma con sincronización del flag tiene_proforma del embarque, aprobarProformas), facturar.ts (marcarProformaFacturada: subida de PDF/XML a Storage, generación de facturas USD/MXN y vinculación) y consolidar.ts (consolidarProformas vía RPC atómica). El archivo original quedó como barrel de re-exports manteniendo la API pública intacta para los hooks de proformas y facturación. Beneficio: el flujo más complejo del negocio (proforma → factura → consolidación) ahora es navegable por responsabilidad y cada submódulo se puede testear de forma aislada. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.67.0",
    date: "2026-04-25",
    type: "minor",
    title: "embarqueServices.ts modularizado en submódulos",
    description: "Paso 10 de la auditoría arquitectónica. El archivo embarqueServices.ts (441 líneas) se dividió en 5 submódulos cohesivos en src/services/embarque/: columns.ts (constantes EMBARQUE_LIST_COLUMNS y EMBARQUE_DETAIL_COLUMNS centralizadas para evitar selecciones inconsistentes), queries.ts (fetchEmbarques, fetchEmbarquesPaginados con todos los filtros, fetchEmbarqueById, conceptos venta/costo, documentos, notas, facturas, expedientes por cliente, proveedores para select, embarques relacionados y embarques_list_extras vía RPC), mutations.ts (RPCs crearEmbarqueRpc, actualizarEmbarqueRpc, duplicarEmbarqueRpc, eliminarEmbarqueRpc, cambio de estado y notas tipadas), eventos.ts (fetch e insert de eventos de tracking) y documentos.ts (resolverExpediente, subirDocumentosEmbarque para creación, uploadDocumentoEmbarque y deleteDocumentoEmbarque para gestión post-creación). El archivo original quedó como barrel de re-exports, manteniendo la API pública intacta — los 6 hooks consumidores (useEmbarqueQueries, useEmbarqueMutations, useEmbarquesListData, useEventosEmbarque, useEmbarquesRelacionados, useNuevoEmbarqueWizard) siguen funcionando sin cambios. Beneficio: cada responsabilidad (lectura, escritura, tracking, archivos) se navega y testea de forma aislada; cambios en columnas se hacen en un único archivo. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.66.0",
    date: "2026-04-25",
    type: "minor",
    title: "EditarEmbarque migrado a controller hook (183→100 líneas)",
    description: "Paso 9 de la auditoría arquitectónica, completando la simetría con NuevoEmbarque (Paso 7). Se extrajo toda la lógica de carga, hidratación y submit de la página EditarEmbarque.tsx al nuevo controller hook hooks/embarque/useEditarEmbarqueWizard.ts: carga del embarque y sus conceptos de venta/costo, hidratación del formulario una sola vez (guard initialized), hidratación independiente de cada lista de conceptos cuando llegan de la base, lookup del cliente seleccionado y orquestación completa del guardado (updateEmbarque → registrarActividad → toast → navegación). La página pasó de 183 a 100 líneas (-45%) y queda como un componente puramente presentacional que consume el hook y renderiza los 3 pasos del wizard. Beneficio: ahora ambos wizards (alta y edición) comparten el mismo patrón controller-hook + página presentacional, lo que facilita futuras extensiones (p. ej. duplicar embarque o vista de solo lectura) sin duplicar lógica. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.65.0",
    date: "2026-04-25",
    type: "patch",
    title: "useUsuarios estandarizado al factory central de queryKeys",
    description: "Paso 8 de la auditoría arquitectónica. Se eliminó el query key local hardcodeado ['usuarios'] de hooks/useUsuarios.ts y se reemplazó por la entrada queryKeys.usuarios.all del factory central lib/queryKeys.ts. Ahora useUsuarios, useUpdateUserRole y useDeleteUser comparten la misma referencia tipada que el resto de la aplicación, lo que asegura invalidaciones consistentes entre módulos y elimina la última fuente de divergencia de keys en hooks de gestión de usuarios. Beneficio: cualquier futura mutación que afecte a la lista de miembros (p. ej. invitaciones desde admin) puede invalidar queryKeys.usuarios.all y refrescar de forma fiable la tabla de usuarios. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.64.0",
    date: "2026-04-25",
    type: "minor",
    title: "NuevoEmbarque migrado a controller hook (282→79 líneas)",
    description: "Paso 7 de la auditoría arquitectónica. Se extrajo todo el estado y lógica del wizard de creación de embarques al nuevo controller hook hooks/embarque/useNuevoEmbarqueWizard.ts: estado local del paso actual, errores de validación, vinculación/desvinculación de cotización, hidratación de conceptos desde una cotización aceptada, manejo de modo expediente (nuevo vs existente), reset por cambio de cliente, validación del paso 1 y la orquestación completa del submit (resolverExpediente → subirDocumentosEmbarque → createEmbarque → updateEstadoCotizacion → registrarActividad). La página NuevoEmbarque.tsx pasó de 282 líneas a 79 líneas (-72%) y queda como un componente puramente presentacional que consume el hook y renderiza los 4 pasos del wizard. Beneficio: la lógica del wizard puede testearse y reutilizarse de forma aislada (p. ej. para una posible variante 'duplicar embarque'); la página solo describe estructura visual. Build verde, 191/191 pruebas pasando.",
  },
];
