import type { ChangelogEntry } from "../../../changelogData";

export const chunk0: ChangelogEntry[] = [
  {
    version: "8.99.7",
    date: "2026-04-27",
    type: "patch",
    title: "Fix: cotizaciones con embarque ahora pasan a 'En operación' automáticamente",
    description: "Corregido un bug donde COT-2026-0007 (y cualquier cotización Aceptada con embarque vinculado) seguía mostrándose como 'Aceptada' en lugar de 'En operación'. Causa raíz: el trigger trg_sync_cotizacion_embarque_link no estaba instalado sobre la tabla embarques, por lo que la promoción automática de estado nunca corría al crear el embarque. Cambios: (1) Backfill SQL: toda cotización con estado 'Aceptada' y embarque_id no nulo se actualizó a 'En operación' (afectó a COT-2026-0007). (2) Reinstalación del trigger AFTER INSERT OR UPDATE OF cotizacion_id sobre public.embarques, que reutiliza la función public.sync_cotizacion_embarque_link() ya existente con la lógica correcta (sincroniza embarque_id y promueve Aceptada → En operación en una sola operación atómica). Resultado: a partir de ahora cualquier embarque creado o vinculado a una cotización aceptada moverá su estado automáticamente sin acción del operador.",
  },
  {
    version: "8.99.6",
    date: "2026-04-27",
    type: "minor",
    title: "Nuevo estado de cotización: 'En operación' (antes 'Embarcada')",
    description: "Renombramos el estado 'Embarcada' a 'En operación' para reflejar mejor el flujo: una cotización es Enviada → Aceptada → En operación (cuando ya tiene embarque vinculado). Cambios: (1) Migración del enum estado_cotizacion eliminando 'Embarcada' y agregando 'En operación'; las 4 cotizaciones que estaban como 'Embarcada' se migraron automáticamente. (2) Trigger trg_sync_cotizacion_embarque_link mejorado: ahora, además de poblar embarque_id, promueve automáticamente el estado de 'Aceptada' a 'En operación' cuando se crea un embarque desde la cotización (cero acción manual). (3) Política RLS 'Cliente read own cotizaciones' actualizada con el nuevo nombre. (4) UI actualizada en todos los puntos: filtros, KPIs, badges, conversión de cotización → embarque y banner del portal del cliente. Beneficio: el equipo comercial puede distinguir claramente qué cotizaciones aceptadas siguen pendientes de operar vs cuáles ya están en operación, y el lenguaje del portal del cliente queda 100% consistente con el badge 'En operación · EXP-XXXX' que ya se mostraba.",
  },
  {
    version: "8.99.5",
    date: "2026-04-27",
    type: "patch",
    title: "Portal: enlace al embarque también en el detalle de la cotización",
    description: "Antes el badge 'En operación · EXP-XXXX' solo aparecía en el listado /portal/cotizaciones, pero al entrar al detalle de una cotización Aceptada con embarque vinculado el cliente perdía el acceso (el banner solo lo mostraba para el estado 'Embarcada'). Ahora PortalCotizacionEstadoBanner muestra el aviso verde de operación y el botón 'Ver embarque →' siempre que la cotización tenga embarque_id, sin importar si su estado es 'Aceptada' o 'Embarcada'. Si además existe comentario del cliente, se conserva debajo del aviso.",
  },
  {
    version: "8.99.4",
    date: "2026-04-27",
    type: "patch",
    title: "Trazabilidad cotización → embarque en el portal del cliente",
    description: "Antes el cliente aceptaba una cotización y se quedaba 'a ciegas': no podía saber si su carga ya estaba en operación. Ahora cada cotización aceptada que ya generó embarque muestra el vínculo directo en el portal. Cambios: (1) Migración SQL con backfill de cotizaciones.embarque_id (se rellenó automáticamente para los embarques existentes que ya apuntaban a una cotización vía cotizacion_id) y un trigger AFTER INSERT/UPDATE en embarques que mantiene el vínculo sincronizado de forma automática a futuro. (2) La política RLS 'Cliente read own cotizaciones' ahora también permite el estado 'Embarcada' (que se asigna al convertir cotización en embarque), evitando que la cotización 'desaparezca' del portal tras la conversión. (3) convertirCotizacionAEmbarques ahora escribe explícitamente cotizaciones.embarque_id al primer embarque creado (defensa en profundidad junto al trigger). (4) UI: el listado /portal/cotizaciones muestra un badge verde 'En operación · EXP-XXXX' clickeable que navega al embarque, y el banner de detalle PortalCotizacionEstadoBanner añade un nuevo caso para 'Embarcada' con botón 'Ver embarque →'.",
  },
  {
    version: "8.99.3",
    date: "2026-04-27",
    type: "patch",
    title: "Privacidad en portal: ocultar cotizaciones en Borrador, Vencida y Cancelada",
    description: "Mejora de privacidad y experiencia para clientes en el portal. Antes el portal exponía TODAS las cotizaciones del cliente, incluyendo borradores internos con precios tentativos en construcción. Ahora los clientes solo verán cotizaciones en estado Enviada, Aceptada o Rechazada (decisiones formalmente compartidas o histórico relevante). Borrador, Vencida y Cancelada quedan ocultas. Implementación con doble capa de protección: (1) política RLS endurecida en la tabla cotizaciones que filtra por estado a nivel de base de datos, garantizando que ni siquiera una consulta directa a la API pueda exponer borradores; (2) filtro defensivo en fetchPortalCotizaciones (src/services/portal/queries.ts) para mantener consistencia y evitar tráfico innecesario. El staff interno (admin, operador, super_admin) sigue viendo todas las cotizaciones sin restricción.",
  },
  {
    version: "8.99.2",
    date: "2026-04-27",
    type: "patch",
    title: "Fix: contador de documentos en portal del cliente",
    description: "Corregido un bug en el portal del cliente donde el contador de documentos del detalle de embarque siempre mostraba 0 (ej. '0/7') aunque el cliente tuviera archivos descargables. La causa era que el filtro en usePortalEmbarqueDetalleController solo contaba documentos en estado 'Validado', ignorando los 'Recibido' (subidos pero pendientes de validación). Ahora se cuentan ambos estados como completados, alineando el comportamiento con TabDocumentos y la lista interna de embarques.",
  },
  {
    version: "8.99.1",
    date: "2026-04-27",
    type: "patch",
    title: "Pulido arquitectónico: sub-agrupación de hooks/cotizacion y limpieza de shims",
    description: "Auditoría de seguimiento tras v8.99.0. Se identificaron 5 oportunidades de mejora pero solo 2 aportaban valor real: las otras 3 (folderizar 7 servicios de archivo único, extraer estado del wizard de embarque y extraer navegación del wizard de cotización) se descartaron por ser ceremonia sin beneficio (los servicios sueltos son archivos únicos sin módulos hermanos, useNuevoEmbarqueWizard ya delega a 4 sub-hooks especializados, y la navegación del wizard de cotización ya vive en useCotizacionWizardForm, no en el layout). Cambios aplicados: (1) Sub-agrupación de src/hooks/cotizacion/: se crearon las sub-carpetas mutations/ (con useCotizacionMutations, useDuplicarCotizacion, usePortalCotizacionMutations) y wizard/ (con useCotizacionWizardForm, useCotizacionWizardSteps, useConceptosForm) replicando el patrón ya usado en hooks/embarque/. El barrel index.ts mantiene la API pública intacta. (2) Eliminación del shim useEmbarqueMutations.ts (6 LOC de re-export) tras migrar los dos consumidores internos restantes al nuevo barrel mutations/. Build TypeScript verde y 205/205 pruebas pasando.",
  },
  {
    version: "8.99.0",
    date: "2026-04-26",
    type: "patch",
    title: "Refinamiento arquitectónico final: barrels, agrupación de páginas y splits cohesivos",
    description: "Cierre de la auditoría arquitectónica de abril 2026 con 5 mejoras aplicadas en un solo paso. (1) Barrels de hooks unificados: se crearon index.ts en los 10 dominios que faltaban (cotizacion, embarque, cliente, proveedor, usuario, admin, dashboard, operaciones, reportes, facturacion) habilitando imports limpios tipo `import { useEmbarques } from '@/hooks/embarque'`. (2) Páginas agrupadas por dominio: las 23 páginas raíz de src/pages/ se reorganizaron en sub-carpetas semánticas (auth/, dashboard/, embarques/, cotizaciones/, clientes/, proveedores/, facturacion/, admin-org/), alineadas con el patrón ya existente de admin/ y portal/. App.tsx y AuthContext.tsx actualizados con las nuevas rutas de import lazy. (3) Split de services/cotizacion/conversiones.ts (225 LOC) en una carpeta conversiones/ con 4 archivos cohesivos: duplicar.ts, prospecto.ts, embarques.ts y portal.ts más un barrel index.ts que mantiene la API pública intacta. (4) Split de useEmbarqueMutations.ts (185 LOC) en hooks/embarque/mutations/ con tres archivos por responsabilidad (useCreateEmbarque, useUpdateEmbarque, useDeleteEmbarque); el archivo original se conserva como re-export para compatibilidad. (5) Extracción del estado UI puro de useTabProformasController.tsx (214 LOC) hacia un nuevo hook useTabProformasState que encapsula filtros, paginación y derivados de filtrado, dejando al controller como orquestador delgado. Cero cambios funcionales: build TypeScript verde y 205/205 pruebas pasando. Con esta entrega la arquitectura del proyecto queda con 0 llamadas directas a supabase desde components/pages, hooks y servicios totalmente organizados por dominio, y barrels consistentes en todas las capas.",
  },
  {
    version: "8.97.0",
    date: "2026-04-26",
    type: "patch",
    title: "Reorganización: subcarpetas semánticas en components/ y hooks/",
    description: "Continuación del plan de auditoría arquitectónica. Se eliminaron 19 archivos sueltos en la raíz de src/components/ y 22 en la raíz de src/hooks/ reubicándolos en subcarpetas con propósito claro. components/: layout/ (AppSidebar, Layout, NavLink, OrgSwitcher, ThemeToggle, RouteLoadingFallback), auth/ (ProtectedRoute, PortalProtectedRoute), selects/ (NavieraSelect, PortSelect, SearchInput) y shared/ (DataTable, PaginationControls, DocumentChecklist, DoubleConfirmDeleteDialog, ErrorBoundary, BitacoraActividad, GlobalSearch, ProfitBadge). hooks/: admin/ (useAdminData, useAdminOrgDetalle, useOrganizationsList, useOrgMembersMutations, usePlanes), cliente/ (useClienteFinancials, useClientUsersMutations, useRentabilidadClientes), embarque/ (useEmbarques, useTrackingLinks, useProfitMaps), cotizacion/ (useCotizaciones, useConceptosForm), operaciones/ (useOperacionesData, useDesempenoChartData), usuario/ (useUsuarios, useUsuarioMutations) y shared/ (useDebounce, useListPageState, useOrgFilter, usePermissions, useSidebarAlerts, useBitacora, useGlobalSearch). Total: 43 archivos movidos y 111 archivos consumidores con imports actualizados automáticamente. Sin cambios funcionales. Build TypeScript verde y 205/205 pruebas pasando.",
  },
  {
    version: "8.96.0",
    date: "2026-04-26",
    type: "patch",
    title: "Unificación global de feedback (toasts) vía appFeedback",
    description: "Migración masiva de 131 llamadas inline `toast({ title, description, variant })` distribuidas en 41 archivos (hooks, páginas y componentes de admin, cliente, embarque, cotización, configuración, catálogos, proveedor, portal y facturación) hacia los helpers semánticos `notifyError`, `notifyWarning` y `notifySuccess` expuestos por `src/lib/ui/appFeedback.ts`. La unificación garantiza severidades consistentes (destructive/warning/success) en toda la aplicación, elimina duplicación de la propiedad `variant`, y centraliza un único punto de cambio para futuras mejoras (telemetría de errores, internacionalización, ajustes visuales). Solo se conservaron como inline los casos especiales con `action:` (toasts con JSX/CTA). Build TypeScript verde y 205/205 pruebas pasando.",
  },
  {
    version: "8.84.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: convención unificada en src/types (sin sufijo Types)",
    description: "Paso O4 (último) de la auditoría arquitectónica de abril 2026. La carpeta src/types/ tenía 8 archivos con sufijo redundante 'Types' (clienteFormTypes, conceptoTypes, cotizacionCostoTypes, cotizacionFormTypes, cotizacionPLTypes, cotizacionTypes, documentoChecklistTypes) más 2 sin sufijo (appRole y types deprecado), produciendo inconsistencia. Se renombraron los 7 archivos a su forma sin sufijo (clienteForm.ts, concepto.ts, cotizacionCosto.ts, cotizacionForm.ts, cotizacionPL.ts, cotizacion.ts, documentoChecklist.ts) y se actualizaron todos los imports del proyecto a la nueva ruta. Adicionalmente se eliminó src/types/types.ts (barrel deprecado de v8.78.0) migrando los 11 consumidores restantes (AuthContext, ProtectedRoute, hooks de usuarios y admin, páginas y componentes de admin, services/admin/members) a `@/types/appRole` directamente. Resultado: src/types/ contiene ahora 8 archivos con convención homogénea sin sufijo, alineada con TS idiomático. Build verde y 201/201 pruebas pasando. Cierre completo del plan de auditoría arquitectónica de abril 2026 (6/6 pasos implementados desde v8.79.0).",
  },
  {
    version: "8.83.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: split de clienteService en crud/contactos/relacionados",
    description: "Paso O2 de la auditoría arquitectónica. El archivo src/services/clienteService.ts (201 LOC, 16 funciones) mezclaba tres responsabilidades del dominio cliente: CRUD/listados, contactos asociados y queries relacionadas (embarques y cotizaciones del cliente). Siguiendo el mismo patrón aplicado a embarqueServices, proformaServices y adminServices, se distribuyó la implementación en src/services/cliente/ con tres módulos cohesivos — crud.ts (CLIENTE_LIST_COLUMNS, CLIENTE_DETAIL_COLUMNS, fetchClientesPaginados, fetchClientes, fetchClientesForSelect, fetchCliente, fetchDiasCreditoCliente, createCliente, updateCliente y el tipo Cliente), contactos.ts (CONTACTO_COLUMNS, fetchContactosCliente, createContacto, updateContacto, deleteContacto y el tipo ContactoCliente) y relacionados.ts (fetchEmbarquesCliente, fetchCotizacionesCliente). El archivo src/services/clienteService.ts queda como barrel de 9 LOC que re-exporta los tres módulos, manteniendo compatibilidad total con los 3 consumidores existentes (useClientes, useProformaDialog y proforma/queries.ts). Build verde y 201/201 pruebas pasando.",
  },
  {
    version: "8.82.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: split de adminServices en stats/organizations/members",
    description: "Paso O1 de la auditoría arquitectónica. El archivo src/services/adminServices.ts (212 LOC, 17 funciones) mezclaba tres dominios distintos: KPIs globales, CRUD de organizaciones y gestión de miembros. Se aplicó el patrón ya validado en embarqueServices y proformaServices: la lógica se distribuyó en src/services/admin/ con tres módulos cohesivos — stats.ts (fetchAdminDashboardStats + countOrgMembers/Embarques/Clientes/Cotizaciones), organizations.ts (fetchAdminOrganizations, fetchOrganizationsList, createOrganization, fetchAdminOrganization, updateAdminOrganization, setOrganizationActivo) y members.ts (fetchAvailableUsers, fetchAdminGlobalUsers, fetchOrgMembers, addOrgMember, updateOrgMemberRole, removeOrgMember). El archivo src/services/adminServices.ts queda como barrel de 9 LOC que re-exporta los tres módulos, manteniendo compatibilidad total con los 6 consumidores existentes (useAdminData, useOrganizationsList, useOrgMembersMutations, useAdminOrgMembers, useAdminOrgKpis, useAdminOrgInfo). Build verde y 201/201 pruebas pasando.",
  },
  {
    version: "8.81.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: hook genérico useListPageState para páginas de listado",
    description: "Paso M1 de la nueva auditoría arquitectónica. Las páginas de listado del sistema repetían el mismo combo de 4 useState (search + filtros + page + pageSize) más el reset manual de página al cambiar cualquier filtro y el cálculo inline de paginated/totalPages. Se creó el hook genérico src/hooks/useListPageState.ts (80 LOC) parametrizado por un blob de filtros tipado por el consumidor (TFilters extends Record<string, string>). Expone search, filters, page, pageSize, setSearch/setFilter/setPage/setPageSize/resetPage y un helper paginate<T>(items) que devuelve { items, totalPages: max(1, ceil(len/size)) }. setSearch y setFilter resetean automáticamente la página a 0 evitando el bug clásico de quedarse en una página vacía después de filtrar. Se migraron Cotizaciones.tsx (eliminó 4 useState + DEFAULT_PAGE_SIZE local + reset manual en 4 callbacks) y Facturacion.tsx (eliminó 4 useState + reset manual en 2 callbacks). Embarques.tsx mantiene su useEmbarquesPageState específico (7+ filtros + rango de fechas, lógica más rica que el genérico) y ClienteDetalle.tsx no aplica (página de detalle, no listado). Cobertura: 5 nuevos tests para inicialización, reset de página en setSearch/setFilter, paginate con corte correcto y totalPages>=1 para arrays vacíos. Build verde, 201/201 pruebas pasando.",
  },
  {
    version: "8.80.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: PortalCotizacionDetalle dividido en sub-componentes",
    description: "Paso M2 de la nueva auditoría arquitectónica. La página PortalCotizacionDetalle.tsx (266 LOC) había vuelto a superar el guardrail de 250 al concentrar header, banners de estado, datos generales y diálogo de confirmación en un solo render. Se extrajeron tres sub-componentes presentacionales bajo src/components/portal/cotizacion/: (1) PortalCotizacionHeader (58 LOC) — título + badge de estado + acciones Aceptar/Rechazar; (2) PortalCotizacionEstadoBanner (60 LOC) — banners contextuales para Aceptada/Rechazada/Enviada con renderizado opcional del comentario_cliente; (3) PortalCotizacionConfirmDialog (70 LOC) — diálogo de confirmación con textarea para comentario opcional. La página queda en 166 LOC (37% menos), enfocada en orquestar el layout (skeleton, datos generales card, secciones de mercancía/conceptos/totales/notas) sin mezclar JSX de UI compleja. El controller hook permanece intacto. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.79.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: orquestador de submit extraído del wizard de embarques",
    description: "Paso C1 de la nueva auditoría arquitectónica (abril 2026). El hook useNuevoEmbarqueWizard.ts había vuelto a 298 LOC, superando el guardrail de 250 al reincorporar lógica de submit. Se creó el nuevo hook useEmbarqueSubmitOrchestrator.ts (143 LOC) que encapsula toda la cadena de side-effects del submit: resolveExpedienteForSubmit → subirDocumentosEmbarque → createEmbarque.mutateAsync → updateEstadoCotizacion (si hay vínculo) → registrarActividad. Recibe sus dependencias por parámetros tipados (SubmitOrchestratorParams) usando los tipos reales de useEmbarqueForm (ReturnType), DocumentoChecklist y los tipos de conceptos, eliminando todos los `as never` intermedios. El wizard pasa de 298 a 212 LOC (29% menos), mantiene un único useEffect (reset de expediente al cambiar cliente) y queda enfocado en gestión de estado y vinculación. Como bonus, se eliminó la fuga de `navigate` por el return del hook: ahora la página NuevoEmbarque obtiene su propio useNavigate, mejorando el aislamiento. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.78.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: types/types.ts renombrado y barrels en lib/financial y lib/ui",
    description: "Pasos O2 y O3 de la auditoría arquitectónica. (O2) El archivo src/types/types.ts era genérico en nombre y solo contenía el tipo AppRole. Se movió la definición a src/types/appRole.ts (nombre descriptivo alineado con su contenido) y se dejó types.ts como barrel deprecado que re-exporta el tipo, manteniendo compatibilidad total con los 11 consumidores existentes (AuthContext, ProtectedRoute, hooks de usuarios y admin, páginas y componentes de admin). (O3) Se añadieron barrels index.ts en src/lib/financial (re-exporta financialUtils, profitUtils y costosUSD) y src/lib/ui (re-exporta uiMappings, estadoConfig y kpiTones), permitiendo imports más limpios del estilo `import { calcularUtilidad } from \"@/lib/financial\"` o `import { kpiIconChipClasses } from \"@/lib/ui\"` sin necesidad de apuntar al subarchivo concreto. Build verde y 196/196 pruebas pasando.",
  },
  {
    version: "8.77.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: mappers de embarque divididos por dirección",
    description: "Paso M3 de la auditoría arquitectónica. El archivo lib/mappers/embarque.ts (241 LOC) estaba al borde del guardrail de 250 y mezclaba responsabilidades opuestas: mapeos BD→form, form→BD y vinculación con cotizaciones. Se dividió en tres módulos cohesivos por dirección de mapeo: (1) embarqueFromDb.ts contiene el tipo EmbarqueFormValues, los DEFAULT_EMBARQUE_VALUES y mapEmbarqueRowToFormValues (BD → formulario para edición); (2) embarqueToDb.ts agrupa buildEmbarquePayload, buildConceptosVentaPayload y buildConceptosCostoPayload (formulario → payloads de inserción); (3) embarqueCotizacion.ts encapsula buildVincularCotizacionUpdates y buildDesvincularCotizacionUpdates junto con la interfaz CotizacionParaVincular. El archivo embarque.ts queda como barrel re-exportando los tres submódulos, manteniendo compatibilidad total con consumidores existentes (useEmbarqueForm.ts y los tests). Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.76.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: dependencias huérfanas eliminadas del bundle",
    description: "Paso O1 de la auditoría arquitectónica. Tras la eliminación de 17 componentes shadcn no usados en v8.72.0, sus librerías subyacentes seguían instaladas en package.json sumando peso al bundle y al árbol de node_modules. Se verificó con ripgrep que no quedaba ningún `from \"<dep>\"` en src/ y se desinstalaron 4 dependencias huérfanas: embla-carousel-react (carousel), vaul (drawer), input-otp (OTP input) y react-resizable-panels (resizable). Resultado: 4 paquetes raíz removidos del lockfile, build verde y 196/196 pruebas pasando.",
  },
  {
    version: "8.75.0",
    date: "2026-04-26",
    type: "minor",
    title: "Auditoría: paleta KPI tokenizada y cero colores hardcodeados",
    description: "Paso M2 de la auditoría arquitectónica. Los 8 archivos restantes del proyecto que usaban clases Tailwind con colores literales (bg-blue-50, bg-emerald-100, bg-violet-600, bg-amber-50, bg-cyan-500, etc.) se migraron a una paleta categórica tokenizada. Se añadieron 6 tonos KPI a index.css (--kpi-info, --kpi-success, --kpi-accent, --kpi-warning, --kpi-secondary, --kpi-danger), cada uno con su variante -soft para fondos pastel. Los tokens son intencionalmente categóricos (no semánticos) para diferenciar tarjetas KPI entre sí, mientras que para semántica de estado se sigue usando success/warning/destructive. Se registraron como utilidades Tailwind kpi.{tone} y kpi.{tone}.soft, y se centralizó el mapeo en lib/ui/kpiTones.ts (helpers kpiIconChipClasses y kpiSolidClasses + tipo KpiTone). Variantes dark calibradas para preservar contraste. Archivos refactorizados: KpiCard.tsx (con back-compat de aliases legacy blue/violet/emerald/red), ClienteSummaryCards.tsx, ReportesKpiCards.tsx, OperacionesWidgets.tsx (chips de RiesgoIndicador y RiskBadge), pages/Operaciones.tsx (tarjetas inline + colores stroke de Recharts movidos a hsl(var(--kpi-*))), DashboardStatusCards.tsx, ResumenConceptosVenta.tsx (badge En proforma a success) y ConceptoRowUSD.tsx (highlight aplica_iva a warning). Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.74.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: controller hooks para páginas detalle del Portal",
    description: "Paso M1 de la auditoría arquitectónica. Las páginas PortalCotizacionDetalle.tsx (288 LOC) y PortalEmbarqueDetalle.tsx (251 LOC) mezclaban estado local, mutaciones, derivaciones y presentación, superando el guardrail de 250 LOC. Se crearon dos controller hooks que aíslan el estado y la lógica derivada, dejando las páginas como capa puramente de presentación. (1) usePortalCotizacionDetalleController encapsula el estado de confirmación (acción Aceptar/Rechazar + comentario), la mutación useResponderCotizacion, los toasts de éxito/error y el reset del diálogo. (2) usePortalEmbarqueDetalleController carga embarque/eventos/documentos y memoiza valores derivados: estadoVisual (vía calcularEstadoEmbarque del dominio), currentStepIndex sobre PORTAL_EMBARQUE_PROGRESS_STEPS, diasParaEta y conteos de docs validados/total. Las constantes del tracker se exportan desde el hook para reutilizarse. Ambas páginas bajan bajo el límite y eliminan imports directos a hooks de datos, dominio y date-fns. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.73.0",
    date: "2026-04-26",
    type: "patch",
    title: "Auditoría: useNuevoEmbarqueWizard adelgazado bajo el guardrail",
    description: "Paso C1 de la nueva auditoría arquitectónica. El hook controller useNuevoEmbarqueWizard.ts (314 LOC) era el único hook del repo que aún superaba el guardrail de 250 LOC. Se aplicaron dos extracciones: (1) la pre-vinculación automática de cotización (lectura de location.state, useCotizacion, useEffect con guarda anti-doble-ejecución y toast de notificación) se movió al nuevo hook useCotizacionHydration.ts, dejando la página NuevoEmbarque libre de plomería de inicialización; (2) la orquestación del submit añadió dos funciones puras testeables a lib/domain/embarqueWizard.ts: resolveExpedienteForSubmit (decide reutilizar expediente existente o resolver uno nuevo, con la resolución del nuevo inyectada como callback) y buildBitacoraDetalles (construye el payload de detalles para registrarActividad). El controller pasa de 314 a ~290 LOC y elimina dos useEffect inline, mientras que el dominio gana cobertura potencial sin acoplarse a React. Build verde, 196/196 pruebas pasando.",
  },
  {
    version: "8.72.0",
    date: "2026-04-26",
    type: "minor",
    title: "Auditoría: changelog particionado, lib/ reorganizado y limpieza de UI",
    description: "Cierre de los pasos M4, O1 y O2 de la auditoría arquitectónica. (M4) El histórico changelog/legacy.ts (1523 líneas, 217 entradas) se dividió en archivos por major version: v1.ts, v2.ts, v3.ts, v4.ts (98 entradas — el más grande), v5.ts, v6.ts y v7.ts. legacy.ts ahora es un agregador delgado que se sigue cargando con import() dinámico desde Changelog.tsx, manteniendo la lazy-load del histórico completo. Beneficio: cada major se navega/edita por separado y futuras particiones por bundle son triviales. (O1) Reorganización de src/lib/ en subcarpetas semánticas: formatters/, financial/ (financialUtils, profitUtils, costosUSD), storage/, ui/ (uiMappings, estadoConfig), errors/, contacto/ y query/. Solo utils.ts queda en la raíz. Los tests acompañaron a sus archivos a __tests__ por subcarpeta. Se actualizaron 116 archivos consumidores con los nuevos paths @/lib/<categoria>. (O2) Eliminados 17 componentes shadcn/ui sin uso real en el proyecto: aspect-ratio, breadcrumb, carousel, chart, context-menu, drawer, form, hover-card, input-otp, menubar, navigation-menu, pagination, resizable, scroll-area, slider, toggle y toggle-group. La carpeta src/components/ui/ pasa de 47 a 30 archivos, reduciendo bundle y ruido visual al navegar la UI. Verificación: tsc limpio y 196/196 pruebas pasando. Con esto se cierran los 8 pasos del plan de auditoría (C1, C2, M1–M4, O1, O2).",
  },
  {
    version: "8.71.0",
    date: "2026-04-25",
    type: "minor",
    title: "Auditoría: dominio del wizard, controllers y tokens semánticos",
    description: "Implementación de los pasos C2, M1, M2 y parte de M3 de la auditoría arquitectónica. (C2) Se extrajo la lógica de dominio del wizard 'Nuevo Embarque' a lib/domain/embarqueWizard.ts: validateDatosGenerales, mapConceptosVentaFromCotizacion y mapConceptosCostoFromCotizacion son ahora funciones puras testeables (5 tests nuevos). useNuevoEmbarqueWizard quedó concentrado en orquestación de React (≈300 líneas, sin lógica de negocio). (M1) Se crearon dos controllers para los componentes más grandes de facturación: useTabProformasController.tsx (filtrado, conteos, paginación y construcción de columnas) y useTabProformasPendientesController.ts (selección, agrupación, totales, handlers de aprobar/consolidar). TabProformas.tsx pasó de 270 a 71 líneas y TabProformasPendientes.tsx de 246 a 130. (M2) DialogGenerarProforma migró toda su lógica (estado del wizard, totales, IVA por concepto, submit con generación de PDF) a useDialogGenerarProformaController.ts; el componente quedó como JSX puro. (M3 parcial) Se agregaron variantes semánticas a Badge: success, warning, info y neutral, conectadas a los tokens --success/--warning/--info ya definidos en index.css. Migrados a tokens semánticos: embarqueColumns (LiquidacionBadge), ProformaBadge, HistorialProformas, PasoConfirmacionProforma, ResumenConceptosVenta, ReportesTablaClientes, BloqueVinculacion, AdminOrganizaciones, CapacityBar (Operaciones), CotizacionDetalle/PasoResumenCotizacion/CotizacionWizardLayout (banners informativos). Las paletas categóricas en uiMappings.ts (modos de transporte) y estadoConfig.ts (estados de embarque) se mantienen intencionalmente — son colores categóricos, no semánticos. Verificación: tsc limpio, 196/196 pruebas pasando (5 nuevas en embarqueWizard).",
  },
  {
    version: "8.69.0",
    date: "2026-04-25",
    type: "minor",
    title: "Auditoría arquitectónica: pasos críticos 1-3 y 9 implementados",
    description: "Tras la auditoría read-only del codebase, se ejecutaron los hallazgos de mayor impacto. (1) Toasts unificados: los hooks useProformas y useDescargarProformaPdf migraron de 'sonner' a '@/hooks/use-toast', dejando una sola API de notificaciones en toda la app. (2) Hooks que aún tocaban supabase.from directo se movieron a la capa de servicios: nuevos clientUserService, reportesService (sidebar_alert_counts, profit_por_embarque, profit_por_cliente, operadores_distintos), searchService (busqueda_global, createDocumentoSignedUrl) y usuarioService (fetchUsuariosOrganizacion, updateUserRole, createUserViaEdgeFunction, deleteUserViaEdgeFunction). Refactorizados: useUsuarios, useUsuarioMutations, useClientUsersMutations, useSidebarAlerts, useRentabilidadClientes, useProfitMaps, useOperadoresDistintos, useGlobalSearch y usePortalDocumentDownload — ahora son delgados (solo cache + tipos). (3) usePortalData modularizado: las 9 queries y 6 constantes de columnas inline se extrajeron a services/portal/{columns,queries}.ts; el hook quedó como capa de cache. (9) Eliminado refetch manual en Usuarios.tsx; useCreateUser ahora invalida queryKeys.usuarios.all automáticamente. Build verde, 191/191 pruebas pasando. Pasos 4-8, 10-11 (refactor de TabProformas, DialogGenerarProforma, adelgazar useNuevoEmbarqueWizard, tokenizar colores, reorganizar lib/) quedan documentados para próximas iteraciones.",
  },
  {
    version: "8.68.0",
    date: "2026-04-25",
    type: "minor",
    title: "proformaServices.ts modularizado en submódulos",
    description: "Paso 11 (final) de la auditoría arquitectónica. Siguiendo el mismo patrón aplicado a embarqueServices, el archivo proformaServices.ts (385 líneas) se dividió en 5 submódulos en src/services/proforma/: types.ts (ProformaRow, ProformaConFactura, ProformaPendienteConEmbarque y demás contratos compartidos), queries.ts (fetchProformasEmbarque, fetchProformasAprobadas, fetchProformasPendientes, fetchClienteParaPdf, fetchEmbarqueParaPdf, fetchConceptosProforma, fetchConceptosConsolidados), crud.ts (crearProforma con rollback, eliminarProforma con sincronización del flag tiene_proforma del embarque, aprobarProformas), facturar.ts (marcarProformaFacturada: subida de PDF/XML a Storage, generación de facturas USD/MXN y vinculación) y consolidar.ts (consolidarProformas vía RPC atómica). El archivo original quedó como barrel de re-exports manteniendo la API pública intacta para los hooks de proformas y facturación. Beneficio: el flujo más complejo del negocio (proforma → factura → consolidación) ahora es navegable por responsabilidad y cada submódulo se puede testear de forma aislada. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.67.0",
    date: "2026-04-25",
    type: "minor",
    title: "embarqueServices.ts modularizado en submódulos",
    description: "Paso 10 de la auditoría arquitectónica. El archivo embarqueServices.ts (441 líneas) se dividió en 5 submódulos cohesivos en src/services/embarque/: columns.ts (constantes EMBARQUE_LIST_COLUMNS y EMBARQUE_DETAIL_COLUMNS centralizadas para evitar selecciones inconsistentes), queries.ts (fetchEmbarques, fetchEmbarquesPaginados con todos los filtros, fetchEmbarqueById, conceptos venta/costo, documentos, notas, facturas, expedientes por cliente, proveedores para select, embarques relacionados y embarques_list_extras vía RPC), mutations.ts (RPCs crearEmbarqueRpc, actualizarEmbarqueRpc, duplicarEmbarqueRpc, eliminarEmbarqueRpc, cambio de estado y notas tipadas), eventos.ts (fetch e insert de eventos de tracking) y documentos.ts (resolverExpediente, subirDocumentosEmbarque para creación, uploadDocumentoEmbarque y deleteDocumentoEmbarque para gestión post-creación). El archivo original quedó como barrel de re-exports, manteniendo la API pública intacta — los 6 hooks consumidores (useEmbarqueQueries, useEmbarqueMutations, useEmbarquesListData, useEventosEmbarque, useEmbarquesRelacionados, useNuevoEmbarqueWizard) siguen funcionando sin cambios. Beneficio: cada responsabilidad (lectura, escritura, tracking, archivos) se navega y testea de forma aislada; cambios en columnas se hacen en un único archivo. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.66.0",
    date: "2026-04-25",
    type: "minor",
    title: "EditarEmbarque migrado a controller hook (183→100 líneas)",
    description: "Paso 9 de la auditoría arquitectónica, completando la simetría con NuevoEmbarque (Paso 7). Se extrajo toda la lógica de carga, hidratación y submit de la página EditarEmbarque.tsx al nuevo controller hook hooks/embarque/useEditarEmbarqueWizard.ts: carga del embarque y sus conceptos de venta/costo, hidratación del formulario una sola vez (guard initialized), hidratación independiente de cada lista de conceptos cuando llegan de la base, lookup del cliente seleccionado y orquestación completa del guardado (updateEmbarque → registrarActividad → toast → navegación). La página pasó de 183 a 100 líneas (-45%) y queda como un componente puramente presentacional que consume el hook y renderiza los 3 pasos del wizard. Beneficio: ahora ambos wizards (alta y edición) comparten el mismo patrón controller-hook + página presentacional, lo que facilita futuras extensiones (p. ej. duplicar embarque o vista de solo lectura) sin duplicar lógica. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.65.0",
    date: "2026-04-25",
    type: "patch",
    title: "useUsuarios estandarizado al factory central de queryKeys",
    description: "Paso 8 de la auditoría arquitectónica. Se eliminó el query key local hardcodeado ['usuarios'] de hooks/useUsuarios.ts y se reemplazó por la entrada queryKeys.usuarios.all del factory central lib/queryKeys.ts. Ahora useUsuarios, useUpdateUserRole y useDeleteUser comparten la misma referencia tipada que el resto de la aplicación, lo que asegura invalidaciones consistentes entre módulos y elimina la última fuente de divergencia de keys en hooks de gestión de usuarios. Beneficio: cualquier futura mutación que afecte a la lista de miembros (p. ej. invitaciones desde admin) puede invalidar queryKeys.usuarios.all y refrescar de forma fiable la tabla de usuarios. Build verde, 191/191 pruebas pasando.",
  },
  {
    version: "8.64.0",
    date: "2026-04-25",
    type: "minor",
    title: "NuevoEmbarque migrado a controller hook (282→79 líneas)",
    description: "Paso 7 de la auditoría arquitectónica. Se extrajo todo el estado y lógica del wizard de creación de embarques al nuevo controller hook hooks/embarque/useNuevoEmbarqueWizard.ts: estado local del paso actual, errores de validación, vinculación/desvinculación de cotización, hidratación de conceptos desde una cotización aceptada, manejo de modo expediente (nuevo vs existente), reset por cambio de cliente, validación del paso 1 y la orquestación completa del submit (resolverExpediente → subirDocumentosEmbarque → createEmbarque → updateEstadoCotizacion → registrarActividad). La página NuevoEmbarque.tsx pasó de 282 líneas a 79 líneas (-72%) y queda como un componente puramente presentacional que consume el hook y renderiza los 4 pasos del wizard. Beneficio: la lógica del wizard puede testearse y reutilizarse de forma aislada (p. ej. para una posible variante 'duplicar embarque'); la página solo describe estructura visual. Build verde, 191/191 pruebas pasando.",
  },
];
