import type { ChangelogEntry } from "../../../changelogData";

export const chunk1: ChangelogEntry[] = [
  {
    version: "8.63.0",
    date: "2026-04-25",
    type: "minor",
    title: "Reglas de cambio de estado de embarque movidas a dominio puro",
    description: "Paso 6 de la auditoría arquitectónica. La verificación confirmó que useEmbarqueMutations.ts ya no toca Supabase directamente (todas sus mutaciones delegan al service embarqueServices.ts), por lo que el foco se trasladó al segundo punto pendiente: lógica de negocio embebida en el hook. Se trasladaron al dominio puro lib/domain/embarque.ts las reglas que decidían qué evento de tracking generar al avanzar el estado de un embarque: el mapa ESTADO_A_EVENTO_TRACKING (Confirmado→Otro, En Tránsito→Zarpe, Arribo→Arribo a Puerto, En Aduana→Despacho Aduanal, Entregado→Entrega, EIR→Liberación, Cerrado→Otro), la función tipoEventoParaEstado (con fallback 'Otro') y descripcionEventoCambioEstado (formato estándar con comillas). El hook ahora solo orquesta la mutación y consume estas funciones. Se añadieron 5 pruebas unitarias para las nuevas reglas (191/191 totales pasando). Beneficio: cualquier cambio futuro en la matriz estado→evento se hace en un único archivo testeado sin tocar React Query ni hooks.",
  },
  {
    version: "8.62.0",
    date: "2026-04-25",
    type: "minor",
    title: "DialogGenerarProforma migrado a React Query",
    description: "Paso 5 de la auditoría arquitectónica. El diálogo de generación de proforma reemplazó sus fetches imperativos (fetchDiasCreditoCliente dentro de useEffect y fetchClienteParaPdf dentro del handler de confirmación) por hooks dedicados de React Query: useDiasCreditoCliente (precarga reactiva, cache de 5 min, key clientes.diasCredito) y useFetchClienteParaPdf (helper basado en queryClient.fetchQuery con cache de 5 min, key clientes.paraPdf). Se añadieron las nuevas keys al factory central de queryKeys. Beneficio: los datos del cliente se cachean entre aperturas del diálogo (evita fetches duplicados al generar varias proformas seguidas), el código se vuelve declarativo, los errores y estados de carga quedan integrados al ecosistema de React Query, y el patrón es coherente con el resto del proyecto. Build verde, 186/186 pruebas pasando.",
  },
  {
    version: "8.61.0",
    date: "2026-04-25",
    type: "minor",
    title: "Más dominio puro de cotización extraído del service",
    description: "Paso 4 de la auditoría arquitectónica. Se trasladaron tres reglas de negocio que vivían embebidas en services/cotizacion/conversiones.ts a lib/domain/cotizacion.ts: (1) filtrarCostosParaContenedor — la regla de que los costos con unidad de medida 'BL' solo se replican en el primer contenedor cuando una cotización se convierte en N embarques; (2) mapCostosACostosEmbarque — la transformación de cotizacion_costos a inserts de conceptos_costo, sin acoplamiento a tipos de Supabase en runtime; y (3) calcularFechaVigencia — el cálculo de fecha_vigencia (YYYY-MM-DD) sumando vigencia_dias a una fecha base, con default de 15 días. El service ahora orquesta llamadas a Supabase pero la lógica de negocio queda probada de forma aislada (9 nuevas pruebas unitarias, 186/186 totales pasando). Beneficio: las reglas críticas de la conversión cotización→embarques son refactorizables y verificables sin levantar la base de datos.",
  },
  {
    version: "8.60.0",
    date: "2026-04-25",
    type: "minor",
    title: "Nuevo services/clienteService.ts — useClientes deja de tocar Supabase",
    description: "Paso 3 de la auditoría arquitectónica. Se creó services/clienteService.ts como capa única de acceso a las tablas clientes y contactos_cliente, centralizando: fetchClientesPaginados, fetchClientes, fetchClientesForSelect, fetchCliente, createCliente, updateCliente, fetchContactosCliente/createContacto/updateContacto/deleteContacto, fetchEmbarquesCliente, fetchCotizacionesCliente y fetchDiasCreditoCliente (que antes vivía en proformaServices.ts y se reexporta desde ahí para no romper imports). El hook src/hooks/useClientes.ts se redujo a una capa de React Query pura: cada hook delega 100% al service, sin llamadas directas a supabase ni queries inline. Beneficio: la jerarquía Hooks → Services → Supabase queda completa para el dominio de clientes; los selects de columnas (CLIENTE_LIST_COLUMNS, CLIENTE_DETAIL_COLUMNS, CONTACTO_COLUMNS) viven en un solo lugar y pueden testearse de forma aislada. Build verde, 177/177 pruebas pasando.",
  },
  {
    version: "8.59.0",
    date: "2026-04-25",
    type: "minor",
    title: "Partición de cotizacionServices y nuevo dominio puro de cotización",
    description: "Refactor interno sin cambios visibles. El monolito services/cotizacionServices.ts (575 L) se descompuso por responsabilidad en services/cotizacion/{crud,costos,conversiones,wizard}.ts: CRUD/queries de la tabla cotizaciones, gestión de cotizacion_costos, conversiones de alto nivel (duplicar, prospecto→cliente, cotización→embarques, respuesta del portal) y orquestadores del wizard (savePaso1/2/3/Final). Adicionalmente se creó lib/domain/cotizacion.ts con la función pura buildConceptosFromCostos que antes vivía en el service mezclada con I/O. El archivo cotizacionServices.ts se mantiene como barrel que re-exporta toda la API pública para no romper imports existentes. Se añadieron 6 pruebas unitarias para el nuevo dominio (177 pruebas en total pasando). Beneficio: cada archivo del dominio cotización es independiente, fácil de localizar y testear.",
  },
  {
    version: "8.58.0",
    date: "2026-04-25",
    type: "minor",
    title: "Tipos de dominio centralizados en src/types/ — fin de la inversión de capas",
    description: "Refactor interno sin cambios visibles que cierra la principal deuda detectada en la auditoría: la inversión de dependencias entre capas. Se movieron a src/types/ los tipos que vivían en components/ y hooks/ y eran consumidos por services/ y lib/: ConceptoVentaCotizacion, DimensionLCL, DimensionAerea, CotizacionRow, CreateCotizacionInput (→ cotizacionTypes.ts), FilaCostoLocal y FilaCostoDetalle (→ cotizacionPLTypes.ts), DocumentoChecklist (→ documentoChecklistTypes.ts), ClienteFormData (→ clienteFormTypes.ts) y CostoCotizacion (→ cotizacionCostoTypes.ts). Los archivos originales conservan re-exports para no romper consumidores. Resultado: cero imports ascendentes desde services/, lib/ o generators/ hacia components/, hooks/ o pages/; la jerarquía Pages → Hooks → Services → Lib se respeta ahora al 100%. Build verde, 171/171 pruebas pasando.",
  },
  {
    version: "8.57.0",
    date: "2026-04-25",
    type: "minor",
    title: "Trazabilidad histórica de la tasa de IVA en proformas",
    description: "Mejora de auditoría sin cambios visibles. Se agregan las columnas tasa_iva_aplicada a las tablas proformas y proforma_conceptos_consolidados, y la función atómica consolidar_proformas se actualiza para persistirla tanto en la cabecera como en cada concepto consolidado. El service crearProforma ahora exige y guarda la tasa que el componente usó para calcular subtotal/IVA/total. Beneficio: si la organización cambia su tasa de IVA en el futuro (por ejemplo de 16% a 8%), las proformas y consolidados emitidos previamente conservan la tasa exacta con la que fueron calculados, garantizando trazabilidad fiscal y cuadres históricos correctos. Valor por defecto 0.16 para registros previos.",
  },
  {
    version: "8.56.0",
    date: "2026-04-25",
    type: "minor",
    title: "Tests del dominio de proformas y guía oficial de transacciones RPC",
    description: "Mejora interna de calidad sin cambios visibles. Se agregan 15 pruebas unitarias para lib/domain/proforma.ts (calcularTotalesProforma, agruparProformasPendientes, montoPrincipalProforma, totalesProformasSeleccionadas) cubriendo IVA fijo en MXN, override de IVA en USD, agrupación por expediente y contenedor, fallback a __sin_contenedor__, prioridad USD/MXN y suma de selecciones. Se documenta en ARCHITECTURE.md el patrón oficial 'Transacciones complejas → RPC en Supabase' explicando por qué los rollbacks manuales en JS no son atómicos y cómo modelar funciones plpgsql security definer consumidas desde el service. Resultado: 171 pruebas pasan en CI y la guía arquitectónica refleja la práctica actual.",
  },
  {
    version: "8.55.0",
    date: "2026-04-25",
    type: "minor",
    title: "Refactor: descomposición del Dashboard del Portal de clientes",
    description: "Refactor 100% interno sin cambios visibles. La página PortalDashboard (280 líneas con welcome, KPIs clicables, distribución de estados, próximos arribos, facturación pendiente y embarques recientes en un único archivo) se descompone en seis subcomponentes presentacionales bajo components/portal/dashboard/: PortalWelcomeCard, PortalKpiGrid, PortalEstadoEmbarquesCard, PortalProximosArribosCard, PortalFacturacionPendienteCard y PortalEmbarquesRecientesCard. La página queda en ~85 líneas dedicadas únicamente a orquestar los hooks de datos (usePortalEmbarques, usePortalCotizaciones, usePortalFacturas, usePortalDashboardKpis) y a componer el layout. Cada tarjeta recibe props tipadas estrictas y es reutilizable de forma independiente.",
  },
  {
    version: "8.54.0",
    date: "2026-04-25",
    type: "minor",
    title: "Refactor: descomposición de la página de detalle de organización",
    description: "Refactor 100% interno sin cambios visibles. La página AdminOrgDetalle (279 líneas con header, KPIs, info editable, tabla de miembros, diálogos de confirmación y configuración mezclados en un solo archivo) se descompone en cuatro subcomponentes presentacionales bajo components/admin/org-detalle/: OrgHeader, OrgInfoCard, OrgMembersCard y OrgConfigCard. La página queda en ~80 líneas dedicadas únicamente a orquestar el hook useAdminOrgDetalle y conectar callbacks con los componentes hijos. Cada subcomponente recibe props tipadas estrictas y es independiente del hook, lo que facilita pruebas y reutilización.",
  },
  {
    version: "8.53.0",
    date: "2026-04-25",
    type: "minor",
    title: "Refactor: descomposición del hook de detalle de organización",
    description: "Refactor 100% interno sin cambios visibles. Se descompone useAdminOrgDetalle (un 'God Hook' de ~245 líneas con 9 queries y mutaciones mezcladas) en cuatro hooks especializados con responsabilidades claras: useAdminOrgInfo (lectura, edición y activación de la organización), useAdminOrgKpis (los cuatro contadores agregados), useAdminOrgMembers (listado y mutaciones de miembros) y useAdminOrgConfig (configuración por categoría). El hook original se conserva como composición ligera para no romper AdminOrgDetalle. La I/O se mueve a adminServices.ts (fetchAdminOrganization, updateAdminOrganization, setOrganizationActivo, countOrg*, fetchOrgMembers, updateOrgMemberRole, removeOrgMember). La función pura de agrupación de configuración por categoría se extrae a lib/domain/configuracion.ts. Resultado: hooks pequeños, testeables individualmente, y cero llamadas directas a Supabase desde los hooks de admin.",
  },
  {
    version: "8.52.0",
    date: "2026-04-25",
    type: "minor",
    title: "Refactor: capa de servicios completa para embarques, cotizaciones y administración",
    description: "Tercera y última fase del refactor arquitectónico transversal. 100% interno, sin cambios visibles para el usuario. (1) embarqueServices.ts ahora encapsula todas las llamadas a Supabase del módulo de embarques: queries paginadas, detalle, conceptos de venta/costo, documentos, notas, facturas, expedientes por cliente, list-extras, relacionados por BL, y mutaciones (crear/actualizar/duplicar/eliminar vía RPC, cambio de estado, notas, eventos de tracking, subida y borrado de documentos). Los hooks useEmbarqueQueries, useEmbarqueMutations, useEmbarquesListData y useEmbarquesRelacionados quedan reducidos a manejo de React Query. (2) cotizacionServices.ts unifica queries (lista, aceptadas, detalle, embarques vinculados), mutaciones CRUD, generación de folio, costos, duplicación, conversiones (prospecto→cliente y cotización→embarques) y respuesta del portal. Seis hooks de cotización (useCotizacionQueries, useCotizacionMutations, useCotizacionCostos, useCotizacionConversions, useDuplicarCotizacion, usePortalCotizacionMutations) ahora solo orquestan caché. (3) Nuevo adminServices.ts con stats del super admin, listado y creación de organizaciones, usuarios disponibles vía edge function y alta de miembros. useAdminData, useOrganizationsList y useOrgMembersMutations migrados. Resultado: las únicas llamadas directas a Supabase desde hooks que quedan son hooks muy específicos (portal, dashboard, búsqueda global), preparando el terreno para futuras pruebas unitarias del service layer.",
  },
  {
    version: "8.51.0",
    date: "2026-04-25",
    type: "minor",
    title: "Refactor arquitectónico transversal: catálogos, bitácora y proveedores",
    description: "Continuación de la limpieza arquitectónica iniciada en v8.50. Este refactor es 100% interno y no cambia ninguna funcionalidad visible para el usuario. (1) Nueva capa de servicios para los módulos que aún tenían SQL crudo dentro de los hooks: catalogosService (navieras, puertos, tipos de contenedor, tipo de cambio), bitacoraService, proveedorServices, configuracionService, clienteFinancialsService y extensión de trackingService y embarqueServices con eventos de tracking. (2) Diez hooks adelgazados (useNavieras, usePuertos, useTiposContenedor, useExchangeRates, useEventosEmbarque, useBitacora, useProveedores, useTrackingLinks, useConfiguracionOrg, useClienteFinancials) que ahora solo manejan estado de React Query, delegando toda la I/O y el mapeo a sus services. (3) Centralización de las query keys restantes en lib/queryKeys.ts (trackingLinks y clienteFinancials) eliminando los últimos strings hard-codeados, y arreglo del query key suelto en invalidateProformaCaches. (4) Lógica de agrupación de proformas pendientes (por expediente y por contenedor), suma de seleccionadas y elección de moneda principal extraída de TabProformasPendientes a lib/domain/proforma.ts como funciones puras y testeables. Resultado: el componente queda enfocado solo en presentación e interacción.",
  },
  {
    version: "8.50.1",
    date: "2026-04-25",
    type: "patch",
    title: "Pre-Facturación: consolidación atómica en BD y query keys centralizadas",
    description: "Mejoras internas finales del refactor del módulo de proformas. (1) La consolidación de proformas (sumar totales, crear la nueva, copiar conceptos agrupados por contenedor y marcar las originales) ahora corre en una sola transacción atómica vía la nueva función de base de datos consolidar_proformas: si cualquier paso falla, todo se revierte automáticamente sin rollbacks manuales del cliente. (2) Las query keys de proformas (lista por embarque, pendientes, aprobadas y conceptos de venta) están ahora centralizadas en lib/queryKeys.ts y se consumen de forma tipada desde el hook useProformas, eliminando strings hard-codeados duplicados; además se introdujo un helper invalidateProformaCaches que evita repetir la lógica de invalidación en cada mutación. (3) Se eliminaron del módulo de dominio las funciones sumarTotalesProformas y construirSnapshotConsolidado que quedaron sin uso al migrar la lógica a la base de datos.",
  },
  {
    version: "8.50.0",
    date: "2026-04-25",
    type: "minor",
    title: "Refactor arquitectónico del módulo Pre-Facturación",
    description: "Refactor interno (sin cambios funcionales para el usuario) que limpia la deuda técnica detectada en la auditoría del módulo de proformas. (1) Nueva capa de dominio (lib/domain/proforma.ts) con funciones puras para cálculo de totales, suma de proformas consolidadas y construcción de snapshots de conceptos. (2) Nueva capa de servicios (services/proformaServices.ts y services/authService.ts) que centraliza todas las llamadas a la base de datos y el login, con tipos nominales para evitar 'as any' en los joins. (3) Hook useProformas reducido de 570 a 158 líneas: ahora solo orquesta React Query y toasts, delegando reglas de negocio al service. (4) Nuevo hook compartido useDescargarProformaPdf que centraliza la descarga de PDF (antes duplicada entre TabFacturacion y TabProformas). (5) Eliminación del IVA hardcodeado (16%): ahora se obtiene dinámicamente con useTasaIVA(). (6) DialogGenerarProforma y TabFacturacion partidos en sub-componentes presentacionales (PasoSeleccionConceptos, PasoConfirmacionProforma, ResumenConceptosVenta, HistorialProformas, HistorialFacturas) para mejorar mantenibilidad. (7) Sacadas todas las llamadas directas a Supabase de Login.tsx y NuevoEmbarque.tsx hacia sus respectivos services.",
  },
  {
    version: "8.49.0",
    date: "2026-04-24",
    type: "minor",
    title: "Pre-Facturación: tipo Individual/Consolidada, badges de revisión y PDF agrupado por contenedor",
    description: "Cierre del flujo de revisión de proformas. (1) En la pestaña 'Proformas' (que ya solo muestra las aprobadas) se añadieron las columnas 'BL Master' y 'Tipo': 'Individual' para proformas normales o 'Consolidada (N)' para las que agruparon N proformas originales. (2) En el detalle del embarque (TabFacturacion), cada proforma muestra ahora un doble badge: estado de revisión (Pendiente de revisión / Aprobada / Consolidada en PRO-XXXX) y estado de pago (Facturada / Pago pendiente). (3) Nueva tabla proforma_conceptos_consolidados que guarda el snapshot de conceptos por contenedor cuando se crea una proforma consolidada (descripción, cantidad, precio unitario, total, IVA, moneda, contenedor, tipo de contenedor y embarque de origen). (4) El generador de PDF detecta proformas consolidadas y produce un layout especial: agrupa los conceptos por '📦 Contenedor: XXX (Tipo)', muestra subtotal por contenedor, y al final los totales globales USD/MXN; también añade un badge 'CONSOLIDADA' al header.",
  },
  {
    version: "8.48.0",
    date: "2026-04-24",
    type: "minor",
    title: "Pre-Facturación: nueva pestaña 'Pendientes' con consolidación de proformas",
    description: "Se introdujo una etapa intermedia de revisión en el flujo de proformas. (1) Cambios en BD: nuevos campos estado_revision (pendiente/aprobada/consolidada) y proformas_origen (array de IDs originales) en la tabla proformas; las proformas existentes fueron migradas a 'aprobada' para no afectar el listado actual. (2) Toda nueva proforma generada nace en estado 'pendiente' y aparece en la nueva pestaña 'Pendientes' (primera del módulo Pre-Facturación), con badge de conteo. (3) La pestaña agrupa por expediente y subagrupa por contenedor, mostrando BL, cliente, número de proforma, monto principal (USD si aplica, si no MXN) y fecha; cada expediente se puede expandir/contraer y filtrar por expediente, BL o cliente. (4) Checkboxes para seleccionar proformas con totalizador en tiempo real (USD y MXN). (5) Botón 'Consolidar y aprobar': crea una nueva proforma consolidada del mismo expediente sumando todos los totales, marcando las originales como 'consolidada' y enlazándolas vía consolidada_en; la nueva proforma queda directamente aprobada. (6) Botón 'Aprobar individual': mueve las proformas seleccionadas al listado de 'Proformas' sin fusionarlas. (7) La pestaña 'Proformas' ahora solo muestra las aprobadas (oculta pendientes y originales consolidadas).",
  },
  {
    version: "8.47.0",
    date: "2026-04-24",
    type: "minor",
    title: "Facturación: creación automática de factura y archivos timbrados",
    description: "Al marcar una proforma como facturada, ahora se crea automáticamente el registro en la tabla de facturas (una por moneda si la proforma tiene USD y MXN), con folio, fechas, vencimiento calculado según los días de crédito y vínculo a la proforma origen. Se pueden adjuntar opcionalmente los archivos PDF y XML de la factura timbrada (subidos al bucket público 'facturas'). En la tabla de Facturas del módulo Pre-Facturación se añadieron las columnas 'Proforma' (folio de origen) y 'Archivos' (descarga rápida de PDF/XML). En la tabla de Proformas, junto al folio de factura aparecen iconos para descargar los archivos timbrados. En el detalle del embarque, la sección 'Facturas' muestra la proforma de origen y los archivos, y la sección 'Proformas Generadas' incluye los iconos de descarga PDF/XML cuando ya está facturada.",
  },
  {
    version: "8.46.0",
    date: "2026-04-24",
    type: "minor",
    title: "Proformas: marcado como facturada con folio externo",
    description: "Las proformas ahora pueden marcarse como facturadas registrando el folio de la factura emitida en el sistema externo de la contadora. Cambios: (1) Nuevos campos en la tabla proformas: estado_proforma (pendiente/facturada), folio_factura_externa y fecha_facturacion. (2) En la tabla del módulo Pre-Facturación se añadieron las columnas 'Estado' (badge amarillo Pendiente / verde Facturada) y 'Folio Factura', además de un filtro por estado (Todas / Pendientes / Facturadas) con conteos. (3) Botón 'Marcada Facturada' en cada fila pendiente que abre un diálogo con campos folio (requerido) y fecha de facturación (por defecto hoy); las proformas ya facturadas solo muestran 'Descargar PDF'. (4) En la tabla 'Proformas Generadas' del detalle del embarque (TabFacturacion) también se muestran el estado y folio de factura externa, y se oculta el botón Eliminar para proformas facturadas. (5) Búsqueda y exportación CSV incluyen el folio de factura externa.",
  },
  {
    version: "8.45.2",
    date: "2026-04-24",
    type: "patch",
    title: "Proformas: formato especial para Flete Terrestre en PDF",
    description: "El generador de PDF de proformas ahora muestra el concepto 'Flete Terrestre' como 'Servicios de Logística (Flete Terrestre)' para cumplir con los requisitos de facturación. Esta transformación solo aplica al documento PDF generado; la descripción original se mantiene sin cambios en la base de datos y en las tablas de la interfaz.",
  },
];
