import type { ChangelogEntry } from "../../changelogData";

export const chunk2: ChangelogEntry[] = [
  {
    version: "8.45.1",
    date: "2026-04-24",
    type: "patch",
    title: "Fix: Campos faltantes en query de conceptos de venta",
    description: "Corregida la función useEmbarqueConceptosVenta en useEmbarqueQueries.ts para incluir los campos estado_facturacion, proforma_id y aplica_iva en la selección. Estos campos son necesarios para mostrar correctamente el estado de facturación de cada concepto (Pendiente/En proforma) y el toggle de IVA en el diálogo de generación de proformas.",
  },
  {
    version: "8.45.0",
    date: "2026-04-24",
    type: "minor",
    title: "Proformas: ejecutivo de operaciones y días de crédito",
    description: "Las proformas ahora capturan dos campos adicionales clave para la gestión comercial: el ejecutivo de operaciones (tomado automáticamente del operador asignado al embarque) y los días de crédito (campo numérico editable que se inicializa con el valor predeterminado del cliente, si está configurado). En el diálogo 'Generar Proforma' (Paso 1) se añadió un input numérico de días de crédito junto a la visualización del ejecutivo asignado; en el Paso 2 ambos datos se incluyen en el resumen de confirmación. El PDF de la proforma muestra una nueva sección 'Condiciones Comerciales' con el ejecutivo y los días de crédito (mostrando 'Contado' cuando el valor es 0). En la tabla 'Proformas Generadas' del detalle del embarque se incorporaron las columnas 'Operador' y 'Días Crédito'; en la tabla global del módulo Pre-Facturación se añadieron las mismas columnas (después de Cliente) y se incluyen en la exportación CSV. Adicionalmente, se agregó el campo dias_credito al catálogo de clientes para servir como valor por defecto.",
  },
  {
    version: "8.44.0",
    date: "2026-04-24",
    type: "minor",
    title: "Proformas: flujo de revisión en 2 pasos y eliminación",
    description: "El diálogo 'Generar Proforma' ahora utiliza un flujo de dos pasos para evitar generaciones accidentales. Paso 1 (Selección y revisión): el usuario marca conceptos, ajusta el toggle de IVA por concepto (MXN bloqueado en activo, USD editable) y ve los totales en tiempo real; el botón 'Revisar Proforma' avanza sin guardar nada. Paso 2 (Confirmación): muestra un resumen final con la tabla detallada de conceptos, indicadores de IVA por línea, totales por moneda y notas; el botón 'Volver' permite regresar a editar y solo 'Confirmar y Generar' persiste los cambios (crea la proforma, marca los conceptos como en_proforma, actualiza tiene_proforma=true y descarga el PDF). Adicionalmente, en la tabla 'Proformas Generadas' del embarque se incorporó el botón 'Eliminar' con confirmación: al confirmar libera los conceptos asociados (estado pendiente, proforma_id=null), elimina el registro de la proforma y, si era la única del embarque, marca tiene_proforma=false.",
  },
  {
    version: "8.43.1",
    date: "2026-04-24",
    type: "patch",
    title: "Toggle de IVA por concepto en proformas",
    description: "El diálogo 'Generar Proforma' ahora incluye un switch de IVA por cada concepto de la lista. Reglas: los conceptos en MXN tienen el switch activo y deshabilitado (siempre llevan IVA al 16%); los conceptos en USD permiten al usuario decidir si aplica IVA, inicializándose con el valor del campo aplica_iva del concepto. El switch se desactiva si el concepto no está seleccionado. Los totales (Subtotal, IVA y Total por moneda) se recalculan en tiempo real al cambiar cualquier toggle. Al generar la proforma, la decisión del usuario se persiste en cada concepto (campo aplica_iva en conceptos_venta) antes de marcarlos como 'en_proforma', garantizando que el PDF y el historial reflejen exactamente lo seleccionado.",
  },
  {
    version: "8.43.0",
    date: "2026-04-24",
    type: "minor",
    title: "Pre-Facturación: tab Proformas y PDF mejorado",
    description: "Se renombra el módulo 'Facturación' a 'Pre-Facturación' (sidebar y título de página) para reflejar mejor el flujo operativo (proformas → facturas → liquidación). Nueva pestaña 'Proformas' como vista por defecto del módulo, que lista todas las proformas de la organización con columnas: # Proforma, Expediente, Cliente, Monto USD, Monto MXN, Fecha y Acciones. Incluye búsqueda por número/expediente/cliente, exportación a CSV con todos los desgloses (subtotal, IVA y total por moneda), paginación server-side y botón 'Descargar' por fila que regenera el PDF cargando en paralelo embarque, conceptos asociados y datos fiscales del cliente. PDF rediseñado: encabezado con título 'PROFORMA' grande (32px, espaciado de letras) y badge 'SIN VALIDEZ FISCAL' en ámbar; bloque de Datos del Cliente con razón social, RFC y dirección completa (dirección + ciudad + estado + CP); bloque de Datos del Embarque en grid de 3 columnas con modo, tipo, incoterm, ruta origen→destino y descripción de mercancía; tablas separadas por moneda con bloque de subtotales/IVA/total destacado al pie de cada tabla (USD muestra IVA solo si algún concepto lo lleva; MXN siempre muestra IVA al 16%); aviso amarillo prominente al pie 'Este documento es una proforma y no tiene validez fiscal'. Tasa de IVA leída desde useTasaIVA.",
  },
  {
    version: "8.42.0",
    date: "2026-04-24",
    type: "minor",
    title: "Generación de proformas desde el embarque",
    description: "Nueva funcionalidad para generar proformas directamente desde la pestaña Facturación del detalle del embarque. Cada concepto de venta muestra ahora su estado: 'Pendiente' (gris con reloj) o 'En proforma' (verde con check), junto con un resumen de totales agrupados por moneda (MXN/USD). Botón 'Generar Proforma' visible cuando hay conceptos pendientes, con badge que indica la cantidad disponible. Diálogo modal permite seleccionar conceptos individualmente mediante checkboxes (todos seleccionados por defecto), recalculando totales en tiempo real. Cálculo de IVA automático: conceptos en MXN siempre llevan IVA; conceptos en USD usan el nuevo campo 'aplica_iva' de conceptos_venta para determinar si aplica. Tasa de IVA leída desde configuración (useTasaIVA). Al confirmar: se genera número consecutivo (PRO-AAAA-NNNN) vía RPC, se inserta la proforma con totales separados USD/MXN, se marcan los conceptos seleccionados como 'en_proforma' con su proforma_id (rollback automático en caso de error), se actualiza el badge del embarque vía trigger y se descarga el PDF automáticamente. Nueva sección 'Proformas Generadas' lista el historial con número, fecha, totales y botón de descarga (regenera el PDF a partir de los conceptos asociados). El generador PDF (src/generators/proformaPdf.ts) reutiliza el estilo y layout de cotizacionPdf.ts e incluye datos del embarque, conceptos en USD/MXN con desglose de IVA y resumen de totales.",
  },
  {
    version: "8.41.0",
    date: "2026-04-24",
    type: "minor",
    title: "Sistema de proformas: base de datos, badge visual y filtro",
    description: "Se sienta la base del módulo de proformas. Base de datos: nueva tabla 'proformas' con campos separados USD y MXN (subtotal, IVA, total), número consecutivo único por organización con formato 'PRO-AAAA-NNNN' (reinicia cada año) generado por la función generar_numero_proforma. La columna 'tiene_proforma' del embarque se sincroniza automáticamente vía trigger al crear o eliminar proformas, sin afectar el flujo operativo de estados (Confirmado → En Tránsito → Llegada → En Proceso → EIR → Cerrado). Conceptos de venta ahora incluyen 'estado_facturacion' (pendiente/en_proforma) y 'proforma_id' para trazabilidad. UI: nuevo componente ProformaBadge que muestra un badge grande prominente 'SIN PROFORMA' (naranja con triángulo de alerta) o 'PROFORMA GENERADA' (verde con check) en el encabezado del detalle del embarque y como columna en la lista. Filtro: nuevo selector en la lista de embarques (Todas / Con proforma / Sin proforma) que opera server-side. Políticas RLS multi-tenant aplicadas (acceso por organización + lectura propia para clientes).",
  },
  {
    version: "8.40.1",
    date: "2026-04-22",
    type: "patch",
    title: "Fix: Sanitización de nombres de archivo en Storage",
    description: "Corrige el error 'Invalid key' que aparecía al subir documentos a un embarque cuando el nombre del archivo, del documento o del expediente contenía caracteres no permitidos por Supabase Storage (acentos, espacios, paréntesis, ideogramas CJK, símbolos). Nueva utilidad src/lib/storageUtils.ts (sanitizeStorageKey, sanitizeFileName, buildEmbarqueDocPath) que normaliza Unicode, elimina diacríticos, reemplaza caracteres no-ASCII por '_', colapsa repeticiones, preserva la extensión y limita la longitud por segmento. Aplicada en los 3 puntos de upload de embarques: creación inicial (embarqueServices), carga posterior por documento (useUploadDocumentoEmbarque) y MSDS (useEmbarqueForm). Mensaje de error mejorado en useEmbarqueDocumentosActions: si Supabase devuelve 'Invalid key' se muestra una guía clara al usuario para renombrar el archivo. Cobertura con 17 nuevos tests unitarios.",
  },
  {
    version: "8.40.0",
    date: "2026-04-19",
    type: "minor",
    title: "Modo oscuro con toggle en el header",
    description: "Nuevo ThemeProvider que gestiona el tema (claro/oscuro) y lo persiste en localStorage bajo la clave 'librecarga-theme'. En la primera visita se respeta la preferencia del sistema operativo (prefers-color-scheme). Se añade un botón de toggle (sol/luna) en los tres headers principales: Layout interno, AdminLayout (panel de Super Admin) y PortalLayout (portal de cliente). La paleta dark se recalibró sobre los tokens HSL existentes para mejorar contraste y legibilidad: fondos azul-marino corporativos en lugar de negro puro, sidebar ligeramente más oscuro que el fondo principal, primary invertido al azul eléctrico de marca para mayor presencia, y tokens semánticos de estado (Llegada, En Proceso, Cerrado) ajustados para mantener jerarquía visual sobre fondo oscuro. Sin migración ni cambios de schema.",
  },
  {
    version: "8.39.0",
    date: "2026-04-19",
    type: "minor",
    title: "Crear embarque desde cotización — wizard pre-rellenado",
    description: "Nuevo flujo 'Crear Embarque' visible en el detalle de cotizaciones Aceptadas. Al pulsar el botón se abre el wizard de Nuevo Embarque con la cotización ya vinculada y todos los datos pre-cargados: cliente, modo, tipo, incoterm, ruta (origen/destino), descripción de mercancía, peso, volumen, piezas, tipo de carga y contenedor. Además se hidratan automáticamente los conceptos de venta (desde el JSONB de la cotización) y los conceptos de costo (desde la tabla cotizacion_costos), incluyendo el match de proveedor por nombre. Al finalizar el wizard, el embarque queda enlazado vía cotizacion_id y la cotización se marca como Embarcada. Coexiste con el botón 'Generar Embarques' (que sigue creando N embarques en background según num_contenedores) — el nuevo flujo es para crear un único embarque revisando datos paso a paso.",
  },
  {
    version: "8.38.0",
    date: "2026-04-19",
    type: "minor",
    title: "Reorganización final de hooks + refactor preventivo de páginas",
    description: "Reorganización del directorio src/hooks/: los 14 hooks de cotización se movieron a hooks/cotizacion/ y los 12 hooks de embarque a hooks/embarque/, dejando en raíz solo hooks transversales (auth, dashboard, clientes, etc.). Los barrels useCotizaciones.ts y useEmbarques.ts mantienen la API pública intacta — los ~40 consumidores externos siguen funcionando sin tocarse. Refactor preventivo de las dos pages que excedían el nuevo límite ESLint de 250 LOC: Reportes.tsx (276 → 105 LOC) ahora delega en ReportesFiltros, ReportesKpiCards, ReportesTopChart y ReportesTablaClientes; ClienteDetalle.tsx (291 → 230 LOC) extrae las 6 cards de resumen a ClienteSummaryCards. ARCHITECTURE.md documenta la nueva convención de hooks de dominio. 139/139 tests verdes.",
  },
  {
    version: "8.37.0",
    date: "2026-04-19",
    type: "patch",
    title: "Refactor UI — modularización de ConceptoRows y DesempenoOperadores",
    description: "Cierre suave de la auditoría: (1) ConceptoRows.tsx (238 LOC) dividido en archivos independientes UnidadMedidaSelect.tsx, ConceptoRowUSD.tsx y ConceptoRowMXN.tsx; el archivo original queda como barrel re-export para no romper consumidores. (2) DesempenoOperadores.tsx (290 LOC → 132 LOC) extrae OperadorCard.tsx, ClienteExpandible.tsx y desempenoVisuals.ts (constantes ESTADO_COLOR/ESTADO_ICON). (3) Guardrail ESLint reforzado: max-lines bajado de 300 → 250 LOC para detectar drift más temprano. 139 tests verdes.",
  },
  {
    version: "8.36.0",
    date: "2026-04-19",
    type: "patch",
    title: "Cierre auditoría — eliminación de re-exports @deprecated en src/data/",
    description: "Tramo final de la auditoría de arquitectura: (1) Migrados los 32 archivos consumidores de @/data/{types,conceptoTypes,cotizacionFormTypes,*Constants} a sus nuevas ubicaciones canónicas en @/types/* y @/constants/*. (2) Eliminados los 7 archivos puente marcados @deprecated en src/data/. (3) Movidos los tests de constantes a src/constants/__tests__/. (4) ARCHITECTURE.md actualizado con sección de deuda técnica aceptada (hooks Detalle fragmentados a propósito). 139 tests verdes. src/data/ queda solo con datasets puros (changelog, ports).",
  },
  {
    version: "8.35.0",
    date: "2026-04-19",
    type: "patch",
    title: "Cierre auditoría — barrels completos e imports unificados",
    description: "Tercer tramo de la auditoría: (1) Los barrels useEmbarques.ts y useCotizaciones.ts ahora exportan también usePrefetchEmbarque y usePrefetchCotizacion, completando la API pública. (2) Las páginas Embarques.tsx, Cotizaciones.tsx y NuevoEmbarque.tsx fusionan sus imports en una sola línea desde el barrel, eliminando la mezcla barrel + módulo interno. (3) Auditoría confirma que los hooks restantes con imports internos (useEmbarqueForm, useCotizacionWizardForm, useCotizacionDetalleHandlers) son detalles especializados que no pertenecen al barrel público — el orquestador useEmbarqueDetalleActions ya cumple su rol.",
  },
  {
    version: "8.34.0",
    date: "2026-04-19",
    type: "minor",
    title: "Continuación auditoría — types/, constants/, tests services y shadcn read-only",
    description: "Segunda tanda de la auditoría de arquitectura: (1) Reorganización de src/data/: los archivos *Types.ts se movieron a src/types/ y los *Constants.ts a src/constants/. Los archivos originales se conservan como re-exports marcados @deprecated para no romper imports existentes (cero cambios en ~35 archivos consumidores). (2) Cobertura de tests: nuevos suites unitarios para services/trackingService (4 tests) y services/csfService (3 tests) con mocks de fetch y supabase.auth — los services ahora tienen pruebas. (3) src/components/ui/README.md documenta que los componentes shadcn son read-only y el procedimiento para wrappers. Build verde, 139 tests pasando.",
  },
  {
    version: "8.33.0",
    date: "2026-04-19",
    type: "minor",
    title: "Auditoría arquitectura — capa limpia + changelog lazy + ARCHITECTURE.md",
    description: "Aplicados los items críticos de la auditoría: (1) Eliminadas las llamadas directas a supabase.from(...) en Cotizaciones.tsx y Embarques.tsx; ahora usan los nuevos hooks usePrefetchCotizacion / usePrefetchEmbarque. (2) TrackingPublico.tsx delega la llamada a la edge function al nuevo services/trackingService.ts, manteniendo la página libre de detalles de transporte. (3) changelogData.ts se partió en recentChangelog (v8.x, 400 líneas, eager) y changelog/legacy.ts (v0–v7.x, 1500 líneas, dynamic import bajo demanda). El chunk inicial de Changelog cayó de ~340kB a 34kB. (4) Nuevo ARCHITECTURE.md documenta el contrato pages/hooks/services. Sin cambios funcionales: 132 tests siguen verdes.",
  },
  {
    version: "8.32.0",
    date: "2026-04-18",
    type: "minor",
    title: "Dashboard split — summary eager + details lazy",
    description: "Se dividió la RPC monolítica dashboard_stats en dos funciones especializadas: dashboard_summary (KPIs, conteos y resúmenes — ~5x más liviana, se carga eager) y dashboard_details (alertas, próximos arribos, profit del mes, embarques del mes siguiente y cargas por cliente — se carga en segundo plano una vez que summary terminó). El primer pintado del Dashboard ahora muestra cards y conteos sin esperar las listas largas, mejorando el TTFB percibido 2–3x. El contrato del hook useDashboardData se mantiene intacto: ambos payloads se combinan internamente. dashboard_stats se conserva sin cambios para retrocompatibilidad.",
  },
  {
    version: "8.31.0",
    date: "2026-04-18",
    type: "patch",
    title: "Cierre del plan — AuthContext memoizado y preload idle de rutas",
    description: "Últimas dos acciones del plan: (1) AuthContext ahora memoiza su value con useMemo, evitando re-renders en cascada de todos los consumidores cada vez que el provider se vuelve a renderizar. (2) Tras el login se programa un import() en idle (requestIdleCallback con fallback setTimeout) de las páginas Embarques, Cotizaciones y Dashboard, dejando sus chunks en caché del navegador. La primera navegación a esas pantallas resulta prácticamente instantánea (sin esperar el round-trip de descarga del chunk). Plan de rendimiento v8.25.0 cerrado al 100%.",
  },
  {
    version: "8.30.0",
    date: "2026-04-18",
    type: "patch",
    title: "Re-auditoría de rendimiento — paginación de Changelog",
    description: "Tras re-auditar el plan v8.25.0, se confirmó que la mayoría de las acciones pendientes ya estaban resueltas: useClientes y useProveedores ya tienen placeholderData, OrganizationContext ya memoiza su value con useMemo y reutiliza la org cacheada del AuthContext, useSidebarAlerts ya define staleTime de 5 min, y todos los imports de lucide-react usan named imports (tree-shaking correcto). La única deuda real era el peso del módulo Changelog (~32 kB gzip). Solución: la página ahora muestra solo las primeras 20 entradas con un botón 'Ver más' para cargar las siguientes páginas. El renderizado inicial es ~85% más liviano sin reducir el contenido disponible.",
  },
  {
    version: "8.29.0",
    date: "2026-04-18",
    type: "patch",
    title: "Optimización de rendimiento — ciclo 4 (auditoría de bundle)",
    description: "Cierre del plan de rendimiento v8.25.0: se incorpora rollup-plugin-visualizer (activable con ANALYZE=true npx vite build) para auditar el tamaño real de los chunks. Auditoría confirmó que (a) los chunks vendor (react, query, radix, charts) están correctamente aislados, (b) las páginas operativas pesan <30 kB gzip, y (c) charts-vendor (97 kB gzip) solo se carga al visitar Dashboard/Reportes/Operaciones gracias al lazy-loading. Única deuda detectada: Changelog.js (32 kB gzip) por su contenido estático extenso, pero ya es lazy-loaded y no afecta el TTI de pantallas operativas. Plan de rendimiento completado: 10/10 acciones ejecutadas.",
  },
];
