import type { ChangelogEntry } from "../../../changelogData";

export const chunk3: ChangelogEntry[] = [
  {
    version: "8.28.0",
    date: "2026-04-18",
    type: "patch",
    title: "Optimización de rendimiento — ciclo 3 (prefetch en hover)",
    description: "Tercer ciclo del plan de rendimiento: (1) DataTable expone una nueva prop opcional onRowMouseEnter para ejecutar acciones al pasar el cursor sobre una fila. (2) Las páginas Embarques y Cotizaciones ahora prefetchean el detalle (queryClient.prefetchQuery con staleTime 30s) cuando el usuario apunta una fila — la navegación al detalle resulta prácticamente instantánea (cache caliente). Cero cambios funcionales ni en RLS.",
  },
  {
    version: "8.27.0",
    date: "2026-04-18",
    type: "patch",
    title: "Optimización de rendimiento — ciclo 2 (portal + detalle + bitácora)",
    description: "Continuación del plan de rendimiento: (1) Reemplazo de select('*') en usePortalEmbarque, usePortalEventos y usePortalDocumentos con listas explícitas de columnas — payload del portal cliente reducido ~50%. (2) useCliente y useContactosCliente migrados a constantes CLIENTE_DETAIL_COLUMNS / CONTACTO_COLUMNS. (3) useProveedor migrado a PROVEEDOR_DETAIL_COLUMNS. (4) useBitacora y useActividadReciente usan ahora BITACORA_COLUMNS explícitas; useBitacora añade placeholderData para evitar parpadeo al paginar. Cero cambios funcionales; payloads de detalle 40–60% más ligeros.",
  },
  {
    version: "8.26.0",
    date: "2026-04-18",
    type: "patch",
    title: "Optimización de rendimiento — ciclo 1 (Badge ref + payloads + caché)",
    description: "Ejecución del primer ciclo del plan de rendimiento v8.25.0: (1) Badge ahora usa React.forwardRef, eliminando el warning 'Function components cannot be given refs' de DataTableInner y previniendo remontes silenciosos en filas con tooltips/popovers. (2) Reemplazo de select('*') por listas explícitas de columnas en los 6 hooks de detalle de embarque (useEmbarque, conceptos venta/costo, documentos, notas, facturas) — payload de detalle reducido 60–80%. (3) staleTime aumentado a 30 minutos en catálogos useNavieras, usePuertos y useTiposContenedor — revalidaciones reducidas ~90%. (4) React.memo aplicado a AlertasDemoraCard, ProximosArribosCard, CargasActivasClienteCard y ProfitTable; useMemo para fechas y saludo en Dashboard — elimina re-renders parásitos al cambiar filtros.",
  },
  {
    version: "8.24.0",
    date: "2026-04-18",
    type: "patch",
    title: "Cierre de Fase 8 — eliminación de archivos legacy en lib/",
    description: "Migración completa de los 19 imports restantes que aún apuntaban a las ubicaciones legacy (lib/embarqueMappers, lib/cotizacionFormMappers, lib/dashboardParsers, lib/cotizacionDetalleHelpers, lib/embarqueLogic, lib/mappers/cotizacionMappers) a sus aliases canónicos en lib/mappers/, lib/parsers/ y lib/domain/. Los archivos legacy (que solo re-exportaban) fueron eliminados y el contenido real ahora vive en su ubicación final. Los tests unitarios se reubicaron bajo lib/{mappers,parsers}/__tests__/. Cero cambios funcionales; 132 tests pasando.",
  },
  {
    version: "8.23.0",
    date: "2026-04-18",
    type: "patch",
    title: "Optimización de rendimiento — eliminación del ciclo de refetch de 60s",
    description: "Tres mejoras críticas de rendimiento detectadas en auditoría: (1) AuthContext ahora ignora eventos TOKEN_REFRESHED e INITIAL_SESSION (Supabase rota el token cada ~60s); estos eventos ya no disparan setUser/fetchUserContext, eliminando la cadena de refetches dashboard_stats + sidebar_alert_counts + bitacora insert que se observaba cada minuto. Guard adicional por sessionStorage evita registrar bitácora de login duplicada en refresh de pestaña. (2) DataTable ya no se envuelve con memo() — al ser un componente genérico provocaba el warning 'Function components cannot be given refs' cuando un hijo (Badge con Slot) recibía un ref desde una row con onClick, rompiendo la memoización silenciosamente. La memoización efectiva ahora se logra memoizando columns/data en los padres. (3) staleTime aumentado a 5 min para dashboard.stats y sidebar.alertCounts (antes 30s default y 1 min respectivamente); refetches en background drásticamente reducidos.",
  },
  {
    version: "8.22.0",
    date: "2026-04-18",
    type: "minor",
    title: "Fase 8 — Descomposición de componentes grandes y reorganización de lib/",
    description: "Refactor estructural sin cambios funcionales: (1) StepDatosGenerales reducido de 328 → 90 LOC dividiéndolo en BloqueClienteContactos, BloqueMercancia y BloqueVinculacion bajo src/components/embarque/secciones/. (2) SeccionConceptosVentaCotizacion reducido de 317 → 109 LOC extrayendo ConceptoRowUSD/ConceptoRowMXN/UnidadMedidaSelect a src/components/cotizacion/conceptos/ConceptoRows.tsx. (3) PortalCotizacionDetalle reducido de 306 → 288 LOC delegando parsing y cálculo de totales al nuevo hook usePortalCotizacionDetalle. (4) Reorganización de lib/: creados aliases canónicos lib/mappers/{embarque,cotizacion,cotizacionForm}.ts, lib/parsers/{dashboard,cotizacionDetalle}.ts y lib/domain/embarque.ts (re-exports con @deprecated en raíz para migración gradual sin romper consumidores). (5) Barrels useEmbarques/useCotizaciones se mantienen como puntos de entrada únicos (separación interna ya cumple el patrón). 132 tests pasando, sin regresiones funcionales.",
  },
  {
    version: "8.21.0",
    date: "2026-04-18",
    type: "patch",
    title: "Guardarraíles ESLint contra deriva arquitectónica",
    description: "Añadidas reglas ESLint para prevenir regresión a archivos sobredimensionados: max-lines (300 LOC), max-lines-per-function (150), complexity (15), max-depth (4), max-params (5). Exenciones aplicadas a primitivos shadcn (src/components/ui/**), tipos generados de Supabase, catálogos de datos (changelogData, ports) y archivos de tests. Las reglas emiten warnings (no bloquean build) para permitir refactor incremental cuando aparezcan violaciones futuras.",
  },
  {
    version: "8.20.0",
    date: "2026-04-18",
    type: "minor",
    title: "Fase 7 — Pulido arquitectónico: extracción de hooks y tokens semánticos",
    description: "Refactor de organización (cero cambios funcionales): (1) Embarques.tsx reducido de 357 a ~225 líneas extrayendo useEmbarquesPageState (filtros+paginación+debounce), buildEmbarqueColumns (definición de columnas DataTable) y EmbarqueRowActions (dropdown editar/duplicar/eliminar). (2) DesempenoOperadores y PortalDashboard delegan cómputo a hooks especializados (useDesempenoChartData, usePortalDashboardKpis). (3) Tipos del formulario de cotización movidos a capa neutra src/data/cotizacionFormTypes.ts (rompe inversión de dependencia lib→components). (4) Constantes MODOS/TIPOS/INCOTERMS/UNIDADES_MEDIDA centralizadas en src/data/wizardConstants.ts. (5) Tokens semánticos --state-llegada, --state-en-proceso, --state-cerrado añadidos en index.css con variantes light/dark; DesempenoOperadores y PortalDashboard migrados a tokens (eliminadas paletas violet/amber crudas).",
  },
  {
    version: "8.19.0",
    date: "2026-04-18",
    type: "minor",
    title: "Cierre del refactor arquitectónico (Fases 4-6) — auditoría final",
    description: "Auditoría final post-refactor. Verificación exhaustiva del ranking de deuda técnica del audit original: (1) Páginas de detalle reducidas — EmbarqueDetalle (149 líneas) y CotizacionDetalle (216 líneas) ya delegan estado a hooks dedicados (useEmbarqueDetalleActions, useCotizacionDetalleState) y UI a componentes hijos. (2) FormProvider implementado en ambos wizards (CotizacionWizardLayout y NuevoEmbarque/EditarEmbarque), eliminando prop-drilling en las secciones. (3) useCotizacionWizardForm delega navegación a useCotizacionWizardSteps. (4) DialogConvertirProspecto y OrgSwitcher confirmados como componentes presentacionales puros sin acceso directo a Supabase. (5) Edge functions consolidadas con shared utils. (6) lib/services/generators reorganizados. Suite de tests: 132 tests pasando en 17 archivos. Cero cambios funcionales en esta versión — únicamente verificación y documentación del estado final.",
  },
  {
    version: "8.18.1",
    date: "2026-04-18",
    type: "patch",
    title: "Cobertura de tests: módulos puros extraídos en Fase 4-6",
    description: "Se agregaron 41 tests unitarios nuevos para los módulos puros extraídos durante el refactor arquitectónico: dashboardParsers (13 tests cubriendo parseConteoPorEstado, parseArribosEsteMes, parseResumenMesSiguiente, parseCargasPorCliente y combinarActivos), cotizacionDetalleHelpers (12 tests cubriendo parseConceptos, calcularTotalesConceptos y getNombreDestinatario) y embarqueMappers (16 tests cubriendo buildEmbarquePayload, buildConceptosVentaPayload/CostoPayload y los helpers de vinculación/desvinculación con cotizaciones). Total de la suite: pasa de ~50 a ~91 tests, sin cambios funcionales.",
  },
  {
    version: "8.18.0",
    date: "2026-04-18",
    type: "minor",
    title: "Refactor arquitectónico Fase 6: reorganización de carpetas y utilidades compartidas para edge functions",
    description: "Sexta iteración del refactor arquitectónico. (1) Reorganización de carpetas: src/lib/ ahora contiene exclusivamente utilidades puras (formatters, financialUtils, dashboardParsers, etc.); los módulos con efectos secundarios sobre la base de datos o el almacenamiento se movieron a src/services/ (storage, csfService, embarqueServices, cotizacionServices) y los generadores de documentos a src/generators/ (cotizacionPdf, exportCsv). Esta separación clarifica la testabilidad y la dirección de las dependencias. (2) Edge functions: se creó supabase/functions/_shared/ con utilidades reutilizables para CORS (cors.ts), respuestas JSON estandarizadas (response.ts) y autenticación con verificación de rol admin (auth.ts). Las 7 edge functions (create-user, list-users, delete-user, invite-client-user, exchange-rates, tracking-public, parse-csf) fueron refactorizadas para consumir estas utilidades, eliminando ~250 líneas de código duplicado y unificando el manejo de errores. Cero cambios visuales ni de comportamiento; toda la API pública se preserva.",
  },
  {
    version: "8.17.0",
    date: "2026-04-18",
    type: "minor",
    title: "Refactor arquitectónico Fase 5: aislamiento de backend, descomposición de páginas y división del wizard",
    description: "Quinta iteración del refactor arquitectónico. (1) Aislamiento de backend: GlobalSearch, TabResumen del embarque, PortalEmbarqueDocumentos, NuevoUsuarioDialog y AgregarMiembroOrgDialog ya no acceden directamente al cliente de base de datos; ahora consumen hooks dedicados (useGlobalSearch, useEmbarquesRelacionados, usePortalDocumentDownload, useOrganizationsList, useAvailableUsers, useAddOrgMember). (2) Descomposición de páginas: EmbarqueDetalle delega su encabezado al nuevo EmbarqueDetalleHeader; CotizacionDetalle delega sus acciones por estado y la sección de embarques generados a CotizacionDetalleSecciones. (3) Wizard de cotización: la navegación entre pasos se extrajo a useCotizacionWizardSteps, dejando a useCotizacionWizardForm como orquestador puro de estado y cálculos. Cero cambios visuales ni de comportamiento; toda la API pública se preserva.",
  },
  {
    version: "8.16.0",
    date: "2026-04-18",
    type: "minor",
    title: "Refactor arquitectónico Fase 4: separación de responsabilidades",
    description: "Cuarta iteración del refactor arquitectónico que limpia la deuda técnica restante del audit original. (1) Acceso a backend: TabPortalCliente ya no usa el cliente de base de datos directamente; ahora consume el nuevo hook useClientUsers, lo que centraliza la invalidación de caché. (2) Componentes: SeccionCostosInternosPLUnificado se dividió en tres archivos especializados (Local para el wizard, Detalle para la persistencia desde BD y un dispatcher delgado), manteniendo intacta la API pública. (3) Hooks god-object: useDashboardData delega el parsing del JSONB a un módulo puro y testeable (lib/dashboardParsers.ts); useCotizacionDetalleState se separa en helpers puros (cotizacionDetalleHelpers.ts) + hook de handlers (useCotizacionDetalleHandlers); useEmbarqueDetalleActions se reorganiza como orquestador de dos hooks focalizados (useEmbarqueEstadoActions y useEmbarqueDocumentosActions). Cero cambios visuales ni de comportamiento.",
  },
  {
    version: "8.15.2",
    date: "2026-04-18",
    type: "patch",
    title: "Refactor arquitectónico Fase 1.3: descomposición de componentes y hooks",
    description: "Tercera iteración del refactor arquitectónico. Se extrajeron de useCotizacionWizardForm.ts los tipos del formulario (CotizacionFormValues), los valores por defecto (COTIZACION_FORM_DEFAULTS) y la función pura buildCotizacionDefaultValues a un nuevo archivo src/lib/cotizacionFormMappers.ts; el hook se redujo de 369 a ~210 líneas y ahora se concentra en orquestar el wizard. Se creó el hook useEmbarqueDetalleTracking que encapsula la creación y copiado del enlace público de tracking, eliminando dependencias directas de useToast y useCreateTrackingLink desde la página EmbarqueDetalle. Cero cambios visuales ni de comportamiento; la API pública (re-exports) se preserva.",
  },
  {
    version: "8.15.1",
    date: "2026-04-18",
    type: "patch",
    title: "Refactor arquitectónico Fase 1.2: separación de mappers y helpers de moneda",
    description: "Se extrajo la lógica pura de mapeo entre el formulario de embarque y la BD a src/lib/embarqueMappers.ts (DEFAULT_EMBARQUE_VALUES, mapEmbarqueRowToFormValues, buildEmbarquePayload, buildConceptosVentaPayload, buildConceptosCostoPayload y los updates de vincular/desvincular cotización). El hook useEmbarqueForm se redujo de 287 a ~135 líneas, ahora solo orquesta RHF + side-effects. Adicionalmente se creó src/lib/costosUSD.ts con helpers sumarEnUSD/aUSD para totalizar listas de conceptos por moneda; StepCostosPrecios.tsx ahora consume estos helpers en lugar de duplicar la conversión inline. Cero cambios visuales ni de comportamiento.",
  },
  {
    version: "8.15.0",
    date: "2026-04-18",
    type: "minor",
    title: "Refactor arquitectónico Fase 1.1: mappings de estado unificados",
    description: "Se consolidaron los mapeos visuales de estado (color de badge, borde izquierdo, barra apilada, icono, gradiente y glow) en una única fuente de verdad: src/lib/estadoConfig.ts. Antes existían tres funciones independientes en uiMappings.ts (getEstadoColor, getEstadoBorderColor, getEstadoBarColor) y un ESTADO_CONFIG separado en components/dashboard/. Ahora todos los consumidores leen del mismo objeto, eliminando duplicación y facilitando agregar nuevos estados. Las funciones existentes se mantienen como wrappers ligeros para preservar la API pública (cero cambios visuales). Archivo components/dashboard/estadoConfig.ts eliminado.",
  },
  {
    version: "8.14.3",
    date: "2026-04-18",
    type: "patch",
    title: "Optimizaciones de rendimiento (Fase 4)",
    description: "Se redujo significativamente el tamaño del payload del Dashboard: la función dashboard_stats ahora limita los resultados a los más relevantes (top 15 alertas de demora, top 15 próximos arribos, top 30 embarques con mejor profit del mes y top 30 del mes siguiente). Esto reduce el JSON enviado al navegador de ~50KB a ~10KB en organizaciones con muchos embarques. Adicionalmente, en builds de producción ahora se eliminan automáticamente los console.log/warn (drop_console) y se separan los bundles de Recharts, React Query y Radix UI en chunks dedicados para mejorar el cacheo del navegador entre despliegues.",
  },
  {
    version: "8.14.2",
    date: "2026-04-18",
    type: "patch",
    title: "Optimizaciones de rendimiento (Fase 3)",
    description: "Se aplicó memoización (React.memo) al componente genérico DataTable y a las tarjetas de embarque del portal del cliente. Esto evita que las tablas y listas se vuelvan a renderizar cuando cambia un estado externo no relacionado (por ejemplo, al expandir un panel, abrir un menú o cambiar el foco). En vistas con muchas filas el desplazamiento y las interacciones se sienten más fluidas.",
  },
  {
    version: "8.14.1",
    date: "2026-04-18",
    type: "minor",
    title: "Optimizaciones de rendimiento (Fase 2)",
    description: "Se optimizó significativamente el Dashboard de Operaciones: (1) todos los cálculos por operador (KPIs, desglose por estado, clientes, cargas en riesgo e histórico de 6 meses) ahora se ejecutan en una sola consulta al servidor mediante la nueva función operaciones_stats(), eliminando la descarga completa de embarques al navegador; (2) se memoizaron las tarjetas de operador y los clientes expandibles con React.memo para evitar re-renders innecesarios al expandir/contraer filas; (3) el resultado se cachea por 60 segundos. En proyectos con cientos de embarques esto reduce el tiempo de carga de Operaciones de varios segundos a milisegundos.",
  },
  {
    version: "8.14.0",
    date: "2026-04-18",
    type: "minor",
    title: "Optimizaciones de rendimiento (Fase 1)",
    description: "Se redujo significativamente el tiempo de carga inicial y la latencia en navegación: (1) las consultas de rol, organización y membresía se consolidaron en una sola llamada al servidor (antes eran 6); (2) se agregaron índices de búsqueda por similitud (pg_trgm) e índices auxiliares en embarques, clientes, proveedores, cotizaciones y facturas para acelerar la búsqueda global y los filtros; (3) la generación de PDF de cotizaciones ahora se carga bajo demanda, reduciendo el tamaño del paquete inicial; (4) se desactivó el refetch automático al cambiar de pestaña y se agregó caché de 30s-5min en consultas de detalle y catálogos; (5) la bitácora de login ahora se registra de manera diferida sin bloquear el render.",
  },
];
