import type { ChangelogEntry } from "../../changelogData";

export const chunk4: ChangelogEntry[] = [
  {
    version: "8.13.4",
    date: "2026-04-17",
    type: "patch",
    title: "Columna Contenedor en lista de embarques",
    description: "La tabla principal de la página Embarques ahora incluye la columna 'Contenedor' justo después de 'BL Master', mostrando el número de contenedor en formato monoespaciado. Si no hay contenedor asignado, se muestra '-'.",
  },
  {
    version: "8.13.3",
    date: "2026-04-17",
    type: "patch",
    title: "Columna Contenedor en tabla de embarques del dashboard",
    description: "La tabla de embarques del próximo mes en el Dashboard principal ahora incluye la columna 'Contenedor' con el número de contenedor de cada embarque. La columna es ordenable y muestra '-' cuando no hay contenedor asignado.",
  },
  {
    version: "8.13.2",
    date: "2026-04-17",
    type: "patch",
    title: "Clientes expandibles en tarjetas de Desempeño por Operador",
    description: "Cada cliente listado dentro de la tarjeta de operador ahora es clickeable y se expande mostrando el desglose de embarques por estado (Confirmado, En Tránsito, Llegada, En Proceso, Cerrado) específico de ese cliente con ese operador. Incluye animación suave y flecha indicadora.",
  },
  {
    version: "8.13.1",
    date: "2026-04-17",
    type: "patch",
    title: "Top 5 clientes en tarjetas de Desempeño por Operador",
    description: "Las tarjetas de operador ahora muestran únicamente los 5 clientes con mayor cantidad de embarques, ordenados de mayor a menor. Si el operador maneja más de 5 clientes, se indica la cantidad restante con un texto '+X clientes más'.",
  },
  {
    version: "8.13.0",
    date: "2026-04-17",
    type: "minor",
    title: "Dashboard de Operaciones: Desempeño por Operador",
    description: "Se reemplazaron las secciones 'Ranking de operaciones' y 'Cargas en riesgo' por un nuevo reporte 'Desempeño por Operador' que muestra en tiempo real el estado de trabajo de cada persona: gráfico comparativo de barras apiladas por estado (Confirmado, En Tránsito, Llegada, En Proceso, Cerrado) y tarjetas individuales con desglose visual y lista de clientes con cantidad de embarques.",
  },
  {
    version: "8.12.0",
    date: "2026-04-16",
    type: "minor",
    title: "Asociar embarques a expediente existente",
    description: "Al crear un nuevo embarque, ahora es posible asociarlo a un expediente existente del mismo cliente. Esto permite que múltiples embarques (ej. contenedores 20' y 40') compartan el mismo número de expediente y BL.",
  },
  {
    version: "8.11.0",
    date: "2026-04-15",
    type: "minor",
    title: "Notas por concepto de costos P&L en cotizaciones",
    description: "Cada concepto de costos internos (USD y MXN) ahora permite agregar notas opcionales que se persisten en la base de datos y se muestran en el wizard y vista detalle de la cotización.",
  },
  {
    version: "8.10.0",
    date: "2026-04-15",
    type: "minor",
    title: "Notas por concepto de venta en cotizaciones",
    description: "Cada concepto de venta (USD y MXN) ahora permite agregar notas opcionales que se muestran en la vista detalle y se incluyen en el PDF exportado para el cliente.",
  },
  {
    version: "8.9.0",
    date: "2026-04-14",
    type: "minor",
    title: "Widget: Cargas activas por cliente en Dashboard",
    description: "Nuevo widget en el Dashboard principal que muestra una tabla ranked de clientes ordenados por número de embarques activos, con desglose por estado y navegación directa al detalle del cliente.",
  },
  {
    version: "8.8.0",
    date: "2026-04-13",
    type: "minor",
    title: "Compactación: helpers getOrigen/getDestino centralizados",
    description: "Creados helpers reutilizables getOrigen() y getDestino() en formatters.ts para resolver la ubicación de un embarque según modo de transporte. Eliminadas 14 ocurrencias duplicadas en 8 archivos.",
  },
  {
    version: "8.7.1",
    date: "2026-04-13",
    type: "patch",
    title: "Fix: estado de documentos al crear embarque",
    description: "Corregido bug donde los documentos subidos durante la creación de un embarque quedaban en estado 'Pendiente' en vez de 'Recibido'. Se actualizó la función de creación y se corrigieron los registros existentes afectados.",
  },
  {
    version: "8.7.0",
    date: "2026-04-12",
    type: "minor",
    title: "Compactación final: externalización de datos, hooks de mutaciones y filtros",
    description: "1) Datos del changelog externalizados a src/data/changelogData.ts (-1,950 líneas en página). 2) Mutaciones Supabase extraídas de 4 componentes UI a hooks dedicados (useUsuarioMutations, useClientUsersMutations, usePortalCotizacionMutations). 3) Filtros de Embarques.tsx extraídos a componente EmbarquesFiltros.",
  },
  {
    version: "8.6.0",
    date: "2026-04-12",
    type: "minor",
    title: "Descomposición de componentes y extracción de servicios",
    description: "1) SeccionCostosInternosPLUnificado descompuesto en TablaCostosLocal y TablaCostosDetalle (444→230 líneas). 2) Lógica de guardado del wizard de cotización extraída a lib/cotizacionServices.ts (savePaso1-4, buildConceptosFromCostos). useCotizacionWizardForm reducido de 429→280 líneas.",
  },
  {
    version: "8.5.2",
    date: "2026-04-12",
    type: "patch",
    title: "Consistencia final: getErrorMessage y tipado de tests",
    description: "1) NuevoClienteDialog migrado a getErrorMessage centralizado (2 catch blocks). 2) as any eliminado en usePermissions.test.tsx con tipado Partial<ReturnType>.",
  },
  {
    version: "8.5.1",
    date: "2026-04-12",
    type: "patch",
    title: "Consolidación ICONO_EVENTO y formatDate residuales",
    description: "1) ICONO_EVENTO extraído a embarqueConstants.ts e importado en TabTracking, PortalEmbarqueTimeline y TrackingPublico. 2) format(new Date(...)) inline migrado a formatDate en AdminOrgDetalle y TrackingPublico.",
  },
  {
    version: "8.5.0",
    date: "2026-04-12",
    type: "minor",
    title: "Limpieza final: type safety, query keys y descomposición portal",
    description: "1) as any eliminado en CotizacionDetalle (comentario_cliente tipado). 2) Query keys centralizados: client_users, organizations-list, embarques-relacionados registrados en queryKeys.ts. 3) format(parseISO) inline migrado a formatDate en 4 archivos (PortalDashboard, PortalEmbarqueDetalle, TabPortalCliente, TabTracking). 4) AgregarMiembroOrgDialog migrado de useEffect+setState a useQuery. 5) PortalEmbarqueDetalle descompuesto en PortalEmbarqueTimeline y PortalEmbarqueDocumentos.",
  },
  {
    version: "8.4.0",
    date: "2026-04-12",
    type: "minor",
    title: "Limpieza arquitectónica final: hooks admin, consolidación y tests",
    description: "1) Queries directas de Supabase en AdminDashboard, AdminUsuarios y AdminOrganizaciones extraídas a useAdminData.ts con hooks dedicados. 2) Wrappers backward-compat (useEmbarquesLiquidacion, useEmbarquesDocsStatus) eliminados; Embarques.tsx migrado a useEmbarquesListExtras. 3) useEmbarqueUtils.ts eliminado; tipos consolidados en useEmbarques.ts. 4) Test de helpers.test.ts dividido en formatters.test.ts y uiMappings.test.ts.",
  },
  {
    version: "8.3.0",
    date: "2026-04-12",
    type: "minor",
    title: "Limpieza arquitectónica: eliminación de deuda técnica post-v8.2.0",
    description: "1) Mapas estadoColor duplicados en 3 páginas del portal unificados con getEstadoColor de uiMappings.ts. 2) 17 consumidores migrados de helpers.ts a imports directos (formatters.ts/uiMappings.ts); helpers.ts eliminado. 3) 6 casts 'as any' eliminados: comentario_cliente tipado correctamente, enums de eventos derivados del esquema. 4) formatDate extendida con locale (es por defecto). 5) barColors inline en PortalDashboard movido a getEstadoBarColor en uiMappings.ts. 6) ESTADO_TIMELINE deprecated eliminado; consumidores migrados a ESTADOS_EMBARQUE. 7) resolverContacto extraída a lib/contactoUtils.ts.",
  },
  {
    version: "8.2.0",
    date: "2026-04-12",
    type: "minor",
    title: "Auditoría arquitectónica: refactoring de separación de concerns",
    description: "1) calcularEstadoEmbarque movida de hooks/ a lib/embarqueLogic.ts (lógica pura). 2) Mapeos visuales del portal centralizados en uiMappings.ts. 3) Query keys del portal integradas en la factoría queryKeys.ts. 4) formatDate consolidada en formatters.ts. 5) ESTADO_TIMELINE derivado de ESTADOS_EMBARQUE. 6) ProfitBadge ya no se re-exporta desde lib/. 7) EmbarqueCard extraída a components/portal/. 8) Re-exports obsoletos eliminados. 9) Tipo any eliminado de EmbarqueCard.",
  },
  {
    version: "8.1.0",
    date: "2026-04-10",
    type: "minor",
    title: "Unificación de alertas entre sidebar y dashboard",
    description: "El badge rojo del sidebar ahora usa la misma lógica dinámica de estado (basada en fechas ETD/ETA) que el dashboard, asegurando que ambos muestren el mismo conteo de embarques con demora.",
  },
];
