/**
 * Módulos de FAQ de la página /ayuda. Separado para mantener archivos
 * ≤200 líneas (Power of 10). Re-exportado por `ayudaContent.ts`.
 */
import type { AyudaModulo } from "./ayudaTypes";
import {
  NBA_LEAD_SIN_CONTACTAR_HORAS,
  SEMANA_LEAD_SIN_CONTACTAR_DIAS,
} from "@/features/crm/domain/umbralesContacto";

export const MODULOS: AyudaModulo[] = [
  {
    id: "inicio",
    titulo: "1. Inicio / Dashboard",
    resumen: "Tu pantalla de arranque: qué pasa hoy en la operación.",
    audiencia: ["Todos"],
    faqs: [
      { pregunta: "¿Qué muestra el dashboard?", respuesta: "Cards de arribos del mes (con utilidad proyectada), embarques en riesgo (demoras), facturación pendiente y comisiones devengadas. Cambia según tu rol: un vendedor ve sólo sus cuentas, un coordinador ve toda la operación." },
      { pregunta: "¿Para qué sirve el toggle 'míos / todos'?", respuesta: "Lo ven vendedores y operadores. Filtra el dashboard a sólo los embarques/cuentas asignados a ti, o muestra los de toda la organización." },
      { pregunta: "¿Qué significan los colores de los badges?", respuesta: "Rojo = atención urgente (factura vencida, demora). Amarillo = próximo a vencer (ETA en ≤1 día). Azul = informativo. Gris = sin pendientes." },
      { pregunta: "¿Por qué no veo utilidad MXN en una card?", respuesta: "La utilidad se calcula al tipo de cambio del día de cierre. Si el embarque sigue abierto, verás 'proyectado' con el TC actual; cuando cierre, se fija el real." },
    ],
  },
  {
    id: "crm",
    titulo: "2. CRM",
    resumen: "Leads, oportunidades, actividades y forecast comercial.",
    audiencia: ["Vendedor", "Gerente Comercial"],
    faqs: [
      { pregunta: "¿Diferencia entre 'Mi día' y 'Resumen'?", respuesta: "Mi día es tu lista accionable: Next Best Actions, actividades de hoy, deals cerrando esta semana. Resumen es el tablero ejecutivo: KPIs, totales de forecast, embudo y leaderboard. Mi día = qué hacer; Resumen = cómo vamos." },
      { pregunta: "¿Cómo creo un lead rápido?", respuesta: "Botón '+' arriba a la derecha del CRM (Quick Add) o atajo de teclado en cualquier pantalla del CRM. También puedes importar masivamente desde CRM → Leads → Importar CSV." },
      { pregunta: "¿Cómo convierto una oportunidad ganada en cotización?", respuesta: "Abre la oportunidad → botón 'Crear cotización desde oportunidad'. Se prellenan cliente, contacto, ruta y vendedor; sólo confirmas tarifa y conceptos." },
      { pregunta: "¿Qué son las Next Best Actions (NBA)?", respuesta: "Sugerencias automáticas del CRM: leads sin contactar hace más de 3 días, cotizaciones sin respuesta, oportunidades a punto de cerrarse. Aparecen primero en Mi día." },
      { pregunta: "¿Cómo busco una cuenta o contacto?", respuesta: "Ctrl+K (Cmd+K en Mac) abre la paleta global y busca en leads, oportunidades, clientes, contactos y embarques al mismo tiempo." },
      { pregunta: "¿Quién ve el forecast?", respuesta: "Todos ven el suyo. Gerente Comercial y admins ven el de todo el equipo, con leaderboard por vendedor." },
    ],
  },
  {
    id: "cotizaciones",
    titulo: "3. Cotizaciones",
    resumen: "Armar cotizaciones tarifa-first, con P&L preliminar y handoff a embarque.",
    audiencia: ["Vendedor", "Ejecutivo de Pricing"],
    faqs: [
      { pregunta: "¿Qué es 'tarifa-first'?", respuesta: "El wizard te pide primero ruta y tipo de contenedor; el sistema busca tarifas vigentes con esos criterios y te muestra el Top 3. Tú eliges y los costos se heredan — no capturas costos a mano." },
      { pregunta: "¿Qué hago si no hay tarifa para esa ruta?", respuesta: "Marca la cotización como 'requiere pricing' y notifica al Ejecutivo de Pricing. Él captura/negocia la tarifa en Costeo y la cotización se actualiza." },
      { pregunta: "¿Quién puede sobrescribir una tarifa sugerida (override)?", respuesta: "Sólo Gerente Comercial y admins. El Vendedor propone, el Gerente aprueba. El override queda registrado en bitácora con quién y por qué." },
      { pregunta: "¿Dónde veo el margen de mi cotización?", respuesta: "En el wizard, pestaña 'Conceptos y P&L'. Muestra venta, costos heredados de la tarifa y margen bruto preliminar. El Vendedor ve sólo el de sus cuentas." },
      { pregunta: "¿Cómo hago el handoff al Coordinador Logístico?", respuesta: "Cuando el cliente confirma, abre la cotización → botón 'Convertir a embarque'. Se crea el embarque con expediente, se copian datos y el Coordinador recibe la notificación." },
      { pregunta: "¿Puedo enviar la cotización por correo desde el ERP?", respuesta: "Sí. Botón 'Enviar por correo' en el detalle de la cotización. Adjunta el PDF, valida el dominio del destinatario y registra el envío en bitácora." },
    ],
  },
  {
    id: "costeo",
    titulo: "4. Costeo / Tarifas",
    resumen: "Matriz de tarifas con partners, ranking y demoras automáticas.",
    audiencia: ["Ejecutivo de Pricing", "Gerente Comercial"],
    faqs: [
      { pregunta: "¿Cómo capturo una tarifa nueva?", respuesta: "Costeo → Tarifas → '+ Nueva tarifa'. Ruta (origen/destino con UN/LOCODE), tipo de contenedor, partner (proveedor), vigencia, días libres y frecuencia del servicio. Sin alguno de esos campos no entra al ranking." },
      { pregunta: "¿Cómo funciona el Top 3 ranking?", respuesta: "Para una ruta + contenedor dados, el sistema ordena las tarifas vigentes por costo total considerando flete, días libres y frecuencia. Las 3 mejores se le ofrecen al Vendedor en el wizard de cotización." },
      { pregunta: "¿Cómo vinculo un agente a un proveedor?", respuesta: "En la tarifa, campo 'Partner'. Es obligatorio: cada agente debe estar vinculado a un proveedor del directorio para que CXP pueda recibir su factura después." },
      { pregunta: "¿Qué es la carta garantía y cuándo se usa?", respuesta: "Documento que firmas con la naviera para liberar el contenedor sin pagar demoras al momento. Se registra en el embarque y NO es facturable al cliente." },
      { pregunta: "¿De dónde salen las demoras facturadas al cliente?", respuesta: "El ERP calcula auto, a partir del timeline del embarque, un tabulador escalonado de días extra × tarifa contra cliente. Aparece como concepto en la proforma; el costo equivalente (lo que cobra la naviera) entra a CXP." },
    ],
  },
  {
    id: "embarques",
    titulo: "5. Embarques",
    resumen: "Crear, editar y dar seguimiento al ciclo cotización → entrega.",
    audiencia: ["Coordinador Logístico", "Gerente de Operaciones"],
    faqs: [
      { pregunta: "¿Cómo creo un embarque desde cero?", respuesta: "Embarques → Nuevo. Wizard de 4 pasos: datos generales, ruta y fechas, conceptos de venta y costos, documentos. Al guardar se asigna expediente automático." },
      { pregunta: "¿Cómo lo creo desde una cotización aprobada?", respuesta: "En Cotizaciones, abre la cotización → 'Convertir a embarque'. Se copian cliente, ruta, conceptos y notas; sólo confirmas fechas y guardas. Es el handoff oficial Vendedor → Coordinador." },
      { pregunta: "¿Cuándo uso FCL vs LCL?", respuesta: "FCL si el cliente paga un contenedor completo. LCL si comparte contenedor (consolidado) — en ese caso el sistema te obliga a registrar BL House bajo un BL Master padre." },
      { pregunta: "¿Cómo avanzo el estado del embarque?", respuesta: "Detalle → pestaña Tracking → 'Avanzar estado'. Los 7 estados son: Propuesta, Confirmado, En tránsito, En puerto, Liberado, Entregado, Cerrado. Cada cambio genera evento de timeline automático." },
      { pregunta: "¿Por qué no puedo avanzar el estado?", respuesta: "Hay candados: avanzar a 'Liberado' requiere checklist de documentos completo; 'Cerrado' requiere todas las facturas emitidas y pagos liquidados. El sistema te dice qué falta." },
      { pregunta: "¿Por qué no me deja eliminar un embarque?", respuesta: "Si tiene factura emitida o proforma aprobada, no se puede eliminar (regla fiscal). Cancela la factura primero o usa la papelera (sólo admin)." },
      { pregunta: "¿De dónde sale la alerta de docs faltantes?", respuesta: "El embarque tiene un checklist de documentos obligatorios según incoterm y tipo de carga. La sidebar muestra badge cuando algún embarque está incompleto." },
    ],
  },
  {
    id: "cxp",
    titulo: "6. Compras (CXP)",
    resumen: "Facturas de proveedor, bandejas 'Por capturar' y 'Por pagar', conciliación con embarque.",
    audiencia: ["Auxiliar Contable", "Tesorero", "Contador"],
    faqs: [
      { pregunta: "¿Qué es 'Por capturar'?", respuesta: "Bandeja con costos del embarque (sugeridos por la tarifa) que todavía no tienen factura de proveedor recibida. Es la lista del Auxiliar Contable: cuando llega el PDF/XML, lo captura desde aquí." },
      { pregunta: "¿Cómo subo una factura de proveedor?", respuesta: "Compras → CXP → 'Nueva factura' (o desde 'Por capturar', botón 'Capturar'). Sube el XML o PDF; el sistema parsea RFC, monto e IVA y te muestra los costos del embarque candidatos para conciliar." },
      { pregunta: "¿Qué es el folio interno FP-XXXXXX?", respuesta: "Identificador único por organización para cada factura de proveedor (FP-000001 en adelante). Lo asigna la BD, es inmutable y la tabla de CXP viene ordenada por folio descendente (lo más reciente arriba)." },
      { pregunta: "¿Quién autoriza pagar al proveedor?", respuesta: "Sólo Tesorero (y admins). El Auxiliar Contable captura, el Tesorero paga — separación de funciones a propósito." },
      { pregunta: "¿Cómo veo qué facturas están vencidas?", respuesta: "Compras → CXP → tab 'Por pagar' o el reporte de aging. La tabla muestra días de vencimiento por factura." },
      { pregunta: "¿Por qué no puedo eliminar un proveedor?", respuesta: "Si tiene facturas, embarques o tarifas vinculadas, el sistema lo bloquea (te dice cuántos registros depende de él). Hay que migrarlos primero." },
    ],
  },
  {
    id: "facturacion",
    titulo: "7. Facturación (CXC)",
    resumen: "Proformas, facturas, cartera, complementos de pago y comisiones.",
    audiencia: ["Contador", "Ejecutivo de Cobranza"],
    faqs: [
      { pregunta: "¿Diferencia entre proforma y factura?", respuesta: "La proforma es el borrador que el cliente aprueba. La factura es el CFDI definitivo timbrado en SAT. Sólo se factura desde una proforma marcada 'Aprobada por cliente'." },
      { pregunta: "¿Cómo consolido proformas?", respuesta: "Selecciona varias proformas del mismo cliente en la pestaña Pendientes → 'Consolidar'. Se genera una sola factura con todos los conceptos." },
      { pregunta: "¿Cómo emito una factura?", respuesta: "Desde la proforma aprobada → 'Timbrar'. El ERP envía a Facturapi, recibe el CFDI y guarda PDF + XML. Sólo Contador y admins pueden hacerlo." },
      { pregunta: "¿Cómo cancelo un CFDI?", respuesta: "Detalle de la factura → 'Cancelar'. Eliges motivo SAT (01, 02, 03, 04) y, si aplica, el folio del CFDI sustituto. Queda registrado en bitácora." },
      { pregunta: "¿Cuándo emito un complemento de pago (REP)?", respuesta: "Cuando una factura PPD se cobra (total o parcial). El ERP te recuerda emitirlo desde Cartera; el contador lo timbra con un click." },
      { pregunta: "¿Cómo descargo el layout contable?", respuesta: "Facturación → tab Facturas → 'Layout contable'. CSV con RFC, subtotal, IVA, uso CFDI y todos los campos que tu contador necesita." },
      { pregunta: "¿Qué es el 'Hueco de facturación'?", respuesta: "Embarques cuyo ETD pasó hace más de 5 días sin factura emitida. Indica que el proveedor ya nos cobró pero al cliente no — riesgo de capital de trabajo." },
      { pregunta: "¿Cómo registro una promesa de pago?", respuesta: "Facturación → Cartera → abre la factura vencida → 'Registrar promesa'. El sistema crea recordatorio para esa fecha." },
    ],
  },
  {
    id: "tesoreria",
    titulo: "8. Tesorería",
    resumen: "Pagos a proveedores, conciliación bancaria y liquidación de comisiones.",
    audiencia: ["Tesorero"],
    faqs: [
      { pregunta: "¿Cómo concilio movimientos bancarios?", respuesta: "Tesorería → sube el estado de cuenta (CSV/Excel) → el ERP sugiere matches contra pagos pendientes con tolerancia ±$1 y ±5 días. Apruebas o rechazas cada sugerencia." },
      { pregunta: "¿Qué pasa si un movimiento no matchea?", respuesta: "Queda en 'Sin conciliar'. Puedes cazarlo manualmente buscando por monto/referencia, o marcarlo como gasto operativo." },
      { pregunta: "¿Cómo registro un pago a proveedor?", respuesta: "Compras → CXP → abre la factura → 'Registrar pago'. Captura banco, monto y referencia. Si fue transferencia, conciliación bancaria lo cazará automáticamente." },
      { pregunta: "¿Cómo liquido comisiones del vendedor?", respuesta: "Facturación → Comisiones → calcula devengadas del mes (sólo facturas cobradas). Marca como liquidadas al pagarlas." },
      { pregunta: "¿Mezcla el ERP MXN con USD?", respuesta: "No. Cada divisa lleva su propia cartera, su propia caja y su propia conciliación. Las conversiones quedan registradas con tipo de cambio del día." },
    ],
  },
  {
    id: "profit",
    titulo: "9. Utilidad y reportes",
    resumen: "Estado de resultados, P&L por contenedor y leaderboard.",
    audiencia: ["Gerencia", "Contador"],
    faqs: [
      { pregunta: "¿Cómo veo el margen de un embarque específico?", respuesta: "/profit → 'P&L por contenedor'. Lista cada embarque con venta, costos directos, margen y % margen. Filtra por mes, cliente o vendedor." },
      { pregunta: "¿Qué incluye el estado de resultados?", respuesta: "Ventas − costos directos − gastos operativos + diferencia cambiaria del periodo. Lo ves por mes o trimestre, con comparativo vs periodo anterior." },
      { pregunta: "¿De dónde sale la diferencia cambiaria?", respuesta: "De la variación de TC entre el día de la factura y el día del cobro (o entre captura y pago, en CXP). El ERP lo calcula automático cuando concilias el movimiento." },
      { pregunta: "¿Cómo exporto a contabilidad?", respuesta: "Cada reporte tiene botón 'Exportar CSV'. Layout contable separado para facturas emitidas, recibidas y pagos." },
      { pregunta: "¿Quién aparece en el leaderboard?", respuesta: "Vendedores con facturas cobradas en el mes en curso. Se ordena por monto cerrado con barra de avance contra cuota (si está configurada)." },
    ],
  },
  {
    id: "clientes-portal",
    titulo: "10. Clientes y Portal",
    resumen: "Onboarding, documentos, contactos y acceso al portal del cliente.",
    audiencia: ["Atención a Clientes", "Coordinador Logístico", "Vendedor"],
    faqs: [
      { pregunta: "¿Qué documentos necesita un cliente para operar?", respuesta: "11 documentos obligatorios: CSF, comprobante domicilio, identificación oficial del representante legal, acta constitutiva, etc. El sistema los lista y bloquea operación hasta que estén todos." },
      { pregunta: "¿Cómo subo la CSF de un cliente?", respuesta: "Cliente → tab Documentos → sube el PDF de la CSF. El ERP la lee con IA y extrae RFC, razón social, régimen fiscal y domicilio fiscal automáticamente para que sólo confirmes." },
      { pregunta: "¿Cómo doy acceso al portal a un cliente?", respuesta: "Cliente → pestaña Usuarios del portal → 'Invitar'. Recibe email con liga; sólo verá SUS embarques, cotizaciones y facturas." },
      { pregunta: "¿Qué ve el cliente en el portal?", respuesta: "Sus embarques con tracking en vivo, sus cotizaciones, sus facturas (con descarga de PDF/XML), notificaciones de cambios de estado y datos de contacto del Coordinador asignado." },
      { pregunta: "¿Cómo manejo contactos con Tax ID extranjero?", respuesta: "En el contacto del cliente, campo 'Tax ID internacional' (no RFC). Aplica para shippers o consignees en el extranjero." },
      { pregunta: "¿Cómo importo clientes masivamente?", respuesta: "Clientes → 'Importar CSV'. Descarga el template, llénalo, súbelo. El sistema valida cada fila antes de insertar." },
    ],
  },
  {
    id: "operacion",
    titulo: "11. Operación diaria",
    resumen: "Atajos, búsqueda global, bandejas, bitácora y multi-organización.",
    audiencia: ["Todos"],
    faqs: [
      { pregunta: "¿Cómo busco rápido un embarque, cliente o factura?", respuesta: "Ctrl+K (Cmd+K en Mac) desde cualquier pantalla. Busca en embarques, cotizaciones, clientes, contactos, facturas y proformas al mismo tiempo." },
      { pregunta: "¿Qué son las bandejas del sidebar?", respuesta: "Vistas filtradas de pendientes: 'Por capturar' (costos sin factura de proveedor), 'Por pagar' (CXP vigente), 'Por emitir' (proformas aprobadas sin facturar). El badge rojo cuenta los items." },
      { pregunta: "¿Qué significan los badges del sidebar?", respuesta: "Rojo en Embarques = embarques en riesgo (demoras o ETA hoy). Rojo en Facturación = facturas vencidas. Rojo en CXP = facturas próximas a vencer. Aparece sólo si hay algo que ver." },
      { pregunta: "¿Dónde veo qué cambió alguien?", respuesta: "/bitacora — registra cada CRUD importante con diff de campos sensibles (qué cambió de qué a qué, quién lo hizo, cuándo). Es inmutable." },
      { pregunta: "¿Cómo cambio entre organizaciones (super-admin)?", respuesta: "Selector arriba del sidebar — sólo lo ve el super-admin de Libre Carga. Al entrar a otra organización, todos los datos se filtran a ese tenant y cada acción queda registrada como impersonación." },
      { pregunta: "¿Qué pasa si la app se cae?", respuesta: "Verás una pantalla con botón 'Reintentar'. El error se reporta automáticamente a logs internos. Si persiste, repórtalo desde el botón flotante de Feedback (esquina inferior)." },
      { pregunta: "¿Cómo cambio el tema (claro/oscuro)?", respuesta: "Menú del usuario abajo del sidebar → 'Tema' → claro / oscuro / sistema." },
    ],
  },
  {
    id: "roles",
    titulo: "12. Roles y permisos",
    resumen: "Quién puede hacer qué dentro del ERP.",
    audiencia: ["Administrador de organización"],
    faqs: [
      { pregunta: "¿Cómo invito a un usuario?", respuesta: "Usuarios → 'Nuevo Usuario'. Email, contraseña inicial y rol (dropdown agrupado por área: Administración / Operaciones / Comercial / Finanzas / Soporte). El usuario debe cambiar su contraseña al primer login." },
      { pregunta: "¿Cuáles son los 12 roles asignables?", respuesta: "Admin (org). Operaciones: Gerente de Operaciones, Gerente Visor, Coordinador Logístico. Comercial: Gerente Comercial, Ejecutivo de Pricing, Vendedor/KAM. Finanzas: Contador, Tesorero, Auxiliar Contable, Ejecutivo de Cobranza. Soporte: Atención a Clientes." },
      { pregunta: "¿Qué hace cada uno?", respuesta: "El dropdown del modal de nuevo usuario muestra la descripción de cada rol. Resumen: Vendedor arma cotizaciones; Pricing negocia tarifas con partners; Coordinador ejecuta embarques tras el handoff; Contador timbra y emite; Tesorero paga y concilia; Auxiliar captura facturas de proveedor; Cobranza da seguimiento a vencidas." },
      { pregunta: "¿Cómo funciona el handoff Vendedor → Coordinador?", respuesta: "El Vendedor arma la cotización con P&L preliminar. Cuando el cliente confirma, dispara 'Convertir a embarque' — el Coordinador Logístico recibe el embarque y toma el control operativo. El Vendedor sigue viendo embarques y cobranza de sus cuentas." },
      { pregunta: "¿Quién aprueba un override de tarifa?", respuesta: "Sólo Gerente Comercial y admins. El Vendedor o Pricing proponen; el override queda en bitácora con quién aprobó y motivo." },
      { pregunta: "¿Cómo cambio el rol de un usuario existente?", respuesta: "Usuarios → abre el usuario → cambia el rol → guarda. El cambio aplica inmediatamente al siguiente refresh de su sesión." },
      { pregunta: "¿Puedo tener un usuario con varios roles?", respuesta: "No. Cada usuario tiene un rol único por organización. Para responsabilidades cruzadas, asigna el rol con más permisos (típicamente Gerente)." },
    ],
  },
];
