/** Defaults del formulario de Cotización (separado de types para respetar Power of 10 200 LOC). */
import type { CotizacionFormValues, LclFleteManual } from "./form";

export const DEFAULT_LCL_FLETE_MANUAL: LclFleteManual = {
  tarifaWM: 0,
  minimo: 0,
  diasLibresAlmacenaje: 0,
  consolidadorId: null,
};

export const COTIZACION_FORM_DEFAULTS: CotizacionFormValues = {
  esProspecto: false,
  clienteId: "",
  prospectoModo: "vincular",
  oportunidadId: "",
  leadId: "",
  monedaCrm: "",
  prospectoEmpresa: "",
  prospectoContacto: "",
  prospectoEmail: "",
  prospectoTelefono: "",
  prospectoRfc: "",
  prospectoDireccion: "",
  prospectoCiudad: "",
  prospectoEntidadFederativa: "",
  prospectoCp: "",
  modo: "",
  tipo: "",
  incoterm: "",
  tipoCarga: "",
  sectorEconomico: "",
  descripcionMercancia: "",
  descripcionAdicional: "",
  tipoEmbarque: "",
  tipoContenedor: "",
  tipoPeso: "",
  dimensionesLCL: [],
  dimensionesAereas: [],
  pesoKg: 0,
  volumenM3: 0,
  piezas: 0,
  tipoUnidad: "",
  origen: "",
  destino: "",
  tiempoTransitoDias: undefined,
  frecuencia: "",
  rutaTexto: "",
  validezPropuesta: undefined,
  tipoMovimiento: "",
  seguro: false,
  valorSeguroUsd: 0,
  diasLibresDestino: 0,
  diasAlmacenaje: 0,
  cartaGarantia: false,
  notas: "",
  numContenedores: 0,
  modalidadEquipo: "",
  puntoIntermedio: "",
  tarifaId: null,
  tarifaOverride: {},
  sinDesgloseCostos: false,
  lclFleteManual: DEFAULT_LCL_FLETE_MANUAL,
  agenteId: null,
  agenteNombre: "",
  navieraId: null,
  navieraNombre: "",
};
