/**
 * Mapeo visual de los estados del ciclo de vida de un embarque.
 * Extraído de `estadoConfig.ts` en v13.380.2 (límite de 200 líneas por archivo).
 */
import {
  Anchor,
  Archive,
  ClipboardCheck,
  Container,
  FileText,
  Loader2,
  MapPin,
  PackageCheck,
  Ship,
  Wallet,
  Warehouse,
  XCircle,
} from "lucide-react";
import { DEFAULT_VISUAL, type EstadoVisual } from "./estadoConfigBase";

export const ESTADO_CONFIG_EMBARQUES: Record<string, EstadoVisual> = {
  // v13.303.21 — "Cotización" (Propuesta) eliminado del workflow. Se conserva
  // la entrada como fallback visual por si aparece por dato legacy.
  "Cotización": {
    ...DEFAULT_VISUAL,
    badge: "bg-muted text-muted-foreground border border-border",
    icon: FileText,
    gradient: "from-muted to-muted/80",
  },
  "En Proceso": {
    badge: "bg-warning/15 text-warning border border-warning/30",
    borderLeft: "border-l-warning",
    bar: "bg-warning",
    icon: Loader2,
    gradient: "from-warning to-warning/80",
    border: "border-warning",
    text: "text-warning",
    glow: "shadow-[0_0_20px_hsl(var(--warning)/0.25)]",
  },
  "Llegada": {
    badge: "bg-state-arribo/15 text-state-arribo border border-state-arribo/30",
    borderLeft: "border-l-state-arribo",
    bar: "bg-state-arribo",
    icon: MapPin,
    gradient: "from-state-arribo to-state-arribo/80",
    border: "border-state-arribo",
    text: "text-state-arribo",
    glow: "shadow-[0_0_20px_hsl(var(--state-arribo)/0.25)]",
  },
  Confirmado: {
    badge: "bg-info/15 text-info border border-info/30",
    borderLeft: "border-l-info",
    bar: "bg-info",
    icon: Anchor,
    gradient: "from-info to-info/80",
    border: "border-info",
    text: "text-info",
    glow: "shadow-[0_0_20px_hsl(var(--info)/0.25)]",
  },
  "En Tránsito": {
    badge: "bg-warning/15 text-warning border border-warning/30",
    borderLeft: "border-l-warning",
    bar: "bg-warning",
    icon: Ship,
    gradient: "from-warning to-warning/80",
    border: "border-warning",
    text: "text-warning",
    glow: "shadow-[0_0_20px_hsl(var(--warning)/0.25)]",
  },
  Arribo: {
    badge: "bg-state-arribo/15 text-state-arribo border border-state-arribo/30",
    borderLeft: "border-l-state-arribo",
    bar: "bg-state-arribo",
    icon: Container,
    gradient: "from-state-arribo to-state-arribo/80",
    border: "border-state-arribo",
    text: "text-state-arribo",
    glow: "shadow-[0_0_20px_hsl(var(--state-arribo)/0.25)]",
  },
  "En Aduana": {
    badge: "bg-state-aduana/15 text-state-aduana border border-state-aduana/30",
    borderLeft: "border-l-state-aduana",
    bar: "bg-state-aduana",
    icon: Warehouse,
    gradient: "from-state-aduana to-state-aduana/80",
    border: "border-state-aduana",
    text: "text-state-aduana",
    glow: "shadow-[0_0_20px_hsl(var(--state-aduana)/0.25)]",
  },
  Entregado: {
    badge: "bg-success/15 text-success border border-success/30",
    borderLeft: "border-l-success",
    bar: "bg-success",
    icon: PackageCheck,
    gradient: "from-success to-success/80",
    border: "border-success",
    text: "text-success",
    glow: "shadow-[0_0_20px_hsl(var(--success)/0.25)]",
  },
  EIR: {
    badge: "bg-state-eir/15 text-state-eir border border-state-eir/30",
    borderLeft: "border-l-state-eir",
    bar: "bg-state-eir",
    icon: ClipboardCheck,
    gradient: "from-state-eir to-state-eir/80",
    border: "border-state-eir",
    text: "text-state-eir",
    glow: "shadow-[0_0_20px_hsl(var(--state-eir)/0.25)]",
  },
  // v13.380.0 — Cierre operativo listo, cierre financiero pendiente.
  "Por liquidar": {
    badge: "bg-warning/15 text-warning border border-warning/30",
    borderLeft: "border-l-warning",
    bar: "bg-warning",
    icon: Wallet,
    gradient: "from-warning to-warning/80",
    border: "border-warning",
    text: "text-warning",
    glow: "shadow-[0_0_20px_hsl(var(--warning)/0.25)]",
  },
  Cerrado: {
    ...DEFAULT_VISUAL,
    icon: Archive,
  },
  Cancelado: {
    badge: "bg-destructive/15 text-destructive border border-destructive/30",
    borderLeft: "border-l-destructive",
    bar: "bg-destructive",
    icon: XCircle,
    gradient: "from-destructive to-destructive/80",
    border: "border-destructive",
    text: "text-destructive",
    glow: "",
  },
};
