import type { ChangelogEntry } from "../changelogData";

export const changelogV3: ChangelogEntry[] = [
  {
    version: "3.15.0",
    date: "2026-03-02",
    type: "minor",
    title: "Unificación de Monto y Subtotal en Costos y Venta",
    description: "Se unificaron las columnas Monto y Subtotal en un solo campo editable 'Subtotal (sin IVA)' en ambas tablas. El Total USD se calcula directamente desde este valor.",
  },
  {
    version: "3.14.0",
    date: "2026-03-02",
    type: "minor",
    title: "Conversión automática a USD en Costos y Venta",
    description: "Se agregó columna 'Total USD' en cada fila de Conceptos de Costo y Venta con conversión automática usando los tipos de cambio configurados. Los totales generales y la utilidad estimada ahora se calculan en USD.",
  },
  {
    version: "3.13.7",
    date: "2026-03-02",
    type: "patch",
    title: "Eliminación de checkbox IVA en Costos y Venta",
    description: "Se removió la columna IVA (checkbox) de las tablas de Conceptos de Costo y Conceptos de Venta para simplificar el formulario.",
  },
  {
    version: "3.13.6",
    date: "2026-03-02",
    type: "patch",
    title: "Total general en Conceptos de Costo",
    description: "Se agregó el total general al final de la tabla de Conceptos de Costo, mostrando la suma de todos los totales por fila.",
  },
  {
    version: "3.13.5",
    date: "2026-03-02",
    type: "patch",
    title: "Columna IVA en Conceptos de Venta",
    description: "Se agregó columna IVA con checkbox en la tabla de Conceptos de Venta. Total por fila incluye 16% si está marcado. El total general muestra la suma de todos los totales.",
  },
  {
    version: "3.13.4",
    date: "2026-03-02",
    type: "patch",
    title: "Columna IVA en Conceptos de Costo",
    description: "Se agregó una columna IVA con checkbox en la tabla de Conceptos de Costo. Si está marcado, el total de la fila incluye 16% de IVA. Sin cambios en Conceptos de Venta.",
  },
  {
    version: "3.13.3",
    date: "2026-03-02",
    type: "patch",
    title: "Catálogo estandarizado de conceptos en Costos y Pricing",
    description: "Se reemplazó el campo de texto libre de concepto en ambas tablas (Costos y Venta) por un dropdown con 7 opciones fijas: Flete Marítimo, Embalaje, Coordinación de Recolección, Seguro de Carga, Manejo, Demoras y Cargos en Destino. Aplica para todos los modos de transporte.",
  },
  {
    version: "3.13.2",
    date: "2026-03-02",
    type: "patch",
    title: "Reorden de secciones en Costos y Pricing",
    description: "Se reorganizó el paso 4 del wizard de embarques para mostrar primero 'Conceptos de Costo' y después 'Conceptos de Venta'. Sin cambios en campos, columnas ni lógica.",
  },
  {
    version: "3.13.1",
    date: "2026-03-02",
    type: "patch",
    title: "Tipo de carga y MSDS en Datos Generales de embarques",
    description: "Nuevo dropdown 'Tipo de carga' (Carga General / Mercancía Peligrosa) en la sección de Datos Generales del wizard de creación y edición de embarques. Si se selecciona 'Mercancía Peligrosa', se muestra un campo para adjuntar la hoja de seguridad (MSDS) al storage. Columnas tipo_carga y msds_archivo agregadas a la tabla embarques.",
  },
  {
    version: "3.13.0",
    date: "2026-03-02",
    type: "minor",
    title: "Refactorización integral del código",
    description: "Consolidación de utilidades duplicadas: getEstadoColor unificado para todos los estados (embarque, cotización, factura), resolverContacto centralizado, interfaces ConceptoVentaLocal/ConceptoCostoLocal extraídas a conceptoTypes.ts, hook useConceptosForm reutilizable. Componentes SearchInput y PaginationControls extraídos y usados en 5+ páginas. Eliminación de ~20 casts 'as any' en CotizacionDetalle, código muerto de validaciones y variables abreviadas renombradas.",
  },
  {
    version: "3.12.5",
    date: "2026-03-02",
    type: "patch",
    title: "Validaciones obligatorias deshabilitadas temporalmente",
    description: "Se deshabilitaron temporalmente todas las validaciones de campos obligatorios en el wizard de creación de embarques (Paso 1 y Paso 2) para facilitar las pruebas durante el desarrollo.",
  },
  {
    version: "3.12.4",
    date: "2026-03-02",
    type: "patch",
    title: "Campo 'Carta garantía' para Marítimo FCL",
    description: "Nuevo campo dropdown 'Carta garantía' (Sí/No) en la sección de Ruta del formulario de cotizaciones, visible únicamente cuando el modo es Marítimo y el tipo de embarque es FCL. Persistido en la base de datos y mostrado en el detalle de la cotización.",
  },
  {
    version: "3.12.3",
    date: "2026-03-02",
    type: "patch",
    title: "Campo 'Días libres de almacenaje' para Marítimo LCL",
    description: "Nuevo campo numérico 'Días libres de almacenaje' en la sección de Ruta del formulario de cotizaciones, visible únicamente cuando el modo es Marítimo y el tipo de embarque es LCL. Persistido en la base de datos y mostrado en el detalle de la cotización cuando el valor es mayor a 0.",
  },
  {
    version: "3.12.2",
    date: "2026-03-02",
    type: "patch",
    title: "Campo 'Días libres en destino' para Marítimo FCL",
    description: "Nuevo campo numérico 'Días libres en destino' en la sección de Ruta del formulario de cotizaciones, visible únicamente cuando el modo es Marítimo y el tipo de embarque es FCL. Persistido en la base de datos y mostrado en el detalle de la cotización cuando el valor es mayor a 0.",
  },
  {
    version: "3.12.1",
    date: "2026-03-02",
    type: "patch",
    title: "Vigencia reemplazada por Validez de la Propuesta",
    description: "Se eliminó el campo manual 'Vigencia (días)' de la sección inferior del formulario de cotizaciones. La vigencia ahora se calcula automáticamente a partir de la fecha de 'Validez de la propuesta' seleccionada en la sección de Ruta. La Card se renombró a 'Notas Adicionales' y solo muestra el campo de notas.",
  },
  {
    version: "3.12.0",
    date: "2026-03-02",
    type: "minor",
    title: "Campos adicionales de ruta y seguro en cotizaciones",
    description: "Se agregaron 7 campos nuevos a la sección Ruta de cotizaciones: tiempo de tránsito (días), frecuencia (Diaria/Semanal/Quincenal), ruta de texto libre, validez de la propuesta (fecha), tipo de movimiento (CY-CY/CY-DR/DR-DR/DR-CY), seguro (toggle Sí/No) con valor en USD. El valor del seguro se suma automáticamente al total de la cotización. Campos visibles en detalle de cotización.",
  },
  {
    version: "3.11.0",
    date: "2026-03-02",
    type: "minor",
    title: "Autocompletado de puertos para carga marítima y multimodal",
    description: "Los campos de Origen y Destino en la sección Ruta ahora usan un buscador con autocompletado basado en un catálogo de ~150 puertos cuando el modo es Marítimo o Multimodal. Cada sugerencia muestra nombre del puerto, ciudad y país. Si el puerto no está en la lista, se permite escribirlo manualmente. Los flujos Aéreo y Terrestre conservan sus campos actuales sin cambios.",
  },
  {
    version: "3.10.0",
    date: "2026-03-02",
    type: "minor",
    title: "Sección de Mercancía Aérea con peso volumétrico",
    description: "Nueva sección de mercancía específica para carga aérea. Incluye tipo de carga, sector económico, descripción adicional, MSDS condicional y tabla dinámica de dimensiones con cálculo automático de peso volumétrico por fila (H×L×W×Pcs / 6000). Totales de piezas y peso volumétrico en kg. Datos persistidos en columna JSONB dimensiones_aereas.",
  },
  {
    version: "3.9.0",
    date: "2026-03-02",
    type: "minor",
    title: "Mercancía dinámica FCL/LCL para carga marítima",
    description: "Sección de mercancía en cotizaciones ahora se adapta dinámicamente al tipo de embarque marítimo. FCL muestra selector de contenedor (10 tipos), tipo de peso (Normal/Sobrepeso) y campos compartidos. LCL muestra tabla dinámica de dimensiones con cálculo automático de volumen m³ y totales. Para modos no marítimos se mantienen los campos estándar. Los datos se persisten en 6 nuevas columnas de la tabla cotizaciones.",
  },
  {
    version: "3.8.0",
    date: "2026-03-02",
    type: "minor",
    title: "Tipo de Carga y Descripción de Mercancía en Cotizaciones",
    description: "Nuevo dropdown de Tipo de Carga (Carga General / Mercancía Peligrosa) con campo condicional para subir hoja de seguridad MSDS. Descripción de mercancía reemplazada por dropdown con 9 categorías fijas: Automotriz, Médica, Alimentos, Carga Proyecto, Construcción, Industrial, General, Tecnología, Arte y Moda.",
  },
  {
    version: "3.7.0",
    date: "2026-03-02",
    type: "minor",
    title: "Flujo Prospecto/Cliente en Cotizaciones",
    description: "Nuevo flujo de destinatario al crear cotizaciones: cliente existente o prospecto (empresa, contacto, email, teléfono). Nuevo estado 'Aceptada' intermedio. Al aceptar, si es prospecto se puede convertir a cliente con formulario pre-llenado; luego se habilita 'Crear Embarque'. Registro completo en bitácora.",
  },
  {
    version: "3.6.0",
    date: "2026-03-02",
    type: "minor",
    title: "Módulo de Cotizaciones",
    description: "Nuevo módulo completo de cotizaciones con tabla independiente. Incluye listado con filtros y paginación, formulario simplificado para crear cotizaciones, detalle con conceptos de venta, y conversión automática a embarque al confirmar. Estados: Borrador, Enviada, Confirmada, Rechazada, Vencida. Registro en bitácora y folio auto-generado (COT-YYYY-NNNN).",
  },
  {
    version: "3.5.0",
    date: "2026-03-02",
    type: "minor",
    title: "Mejoras operativas: estado de embarques, edición de clientes, notas y confirmación de eliminación",
    description: "Nuevo botón 'Avanzar estado' en el detalle del embarque con confirmación y registro en bitácora. Edición de datos del cliente desde su página de detalle. Doble confirmación antes de eliminar contactos. Formulario para agregar notas libres en la pestaña de Notas del embarque con registro automático en bitácora.",
  },
  {
    version: "3.4.0",
    date: "2026-03-01",
    type: "minor",
    title: "Edición de embarques existentes",
    description: "Nueva página para editar embarques con wizard de 3 pasos (Datos Generales, Datos de Ruta, Costos y Pricing) pre-cargados con los valores actuales. Sincronización completa de conceptos de venta y costo. Registro automático en bitácora. Botón Editar conectado desde el detalle del embarque.",
  },
  {
    version: "3.3.1",
    date: "2026-03-01",
    type: "patch",
    title: "Suite de tests unitarios y de integración",
    description: "44 tests en 11 archivos cubriendo helpers (formatDate, getEstadoColor, getModoIcon), formatters (formatCurrency), utils (cn), constantes de embarque/proveedor/contenedores/puertos/navieras, componente BitacoraActividad y hook usePermissions.",
  },
  {
    version: "3.3.0",
    date: "2026-03-01",
    type: "minor",
    title: "Sistema de Bitácora y Actividad",
    description: "Nueva tabla centralizada bitacora_actividad para registrar todas las acciones de usuarios. Hook useBitacora con consultas filtradas y registro automático. Componente BitacoraActividad como timeline visual. Página dedicada /bitacora con paginación y filtros por módulo. Widget de actividad reciente en Dashboard. Registro automático al crear embarques, clientes, proveedores, subir documentos e iniciar sesión.",
  },
  {
    version: "3.2.0",
    date: "2026-03-01",
    type: "minor",
    title: "Renombramiento de variables para mayor claridad",
    description: "Todas las variables de 1-2 letras y abreviaciones ambiguas fueron reemplazadas por nombres descriptivos en 22 archivos. Ejemplos: e→embarque, f→factura, qc→queryClient, tc→tipoCambio, le→cargandoEmbarques, cv→venta, cc→costo, prov→proveedor, [y,m,d]→[anio,mes,dia]. El código ahora es legible sin necesidad de contexto adicional.",
  },
  {
    version: "3.1.0",
    date: "2026-03-01",
    type: "minor",
    title: "Refactorización — Limpieza, deduplicación y modularización",
    description: "Eliminación de funciones helper duplicadas (getModoIcon, getEstadoColor, formatDate) en favor de las centralizadas en helpers.ts. Hook useContactosCliente deduplicado. Constantes de proveedor extraídas a proveedorConstants.ts. NuevoEmbarque dividido en 5 sub-componentes (StepDatosGenerales, StepDatosRuta, StepDocumentos, StepCostosPrecios, StepIndicator). EmbarqueDetalle dividido en 5 tabs (TabResumen, TabDocumentos, TabCostos, TabFacturacion, TabNotas). Eliminados componentes sin usar (TableSkeleton, ErrorState) y variable muerta fileInputRef.",
  },
  {
    version: "3.0.0",
    date: "2026-03-01",
    type: "major",
    title: "Fases 3 y 4 — Permisos, búsqueda, storage, responsive y tipos de cambio",
    description: "Permisos por rol en toda la UI (viewers solo lectura). Emails reales en gestión de usuarios. Subida de documentos al storage con descarga. Búsqueda global (Ctrl+K) en embarques, clientes, proveedores y facturas. Componentes reutilizables TableSkeleton y ErrorState. Tipos de cambio dinámicos desde API externa. Versión actualizada a v3.0.0.",
  },
];
