import type { ChangelogEntry } from "../changelogData";

export const changelogV4: ChangelogEntry[] = [
  {
    version: "4.46.1",
    date: "2026-03-12",
    type: "patch",
    title: "Tendencia de cargas usa ETD en vez de fecha de creación",
    description: "La gráfica de tendencia y KPIs del Dashboard de Operaciones ahora agrupan las cargas por fecha de zarpe (ETD) en lugar de fecha de captura en el sistema. Etiquetas actualizadas a 'Por ETD'.",
  },
  {
    version: "4.46.0",
    date: "2026-03-11",
    type: "minor",
    title: "Dashboard de Operaciones completo",
    description: "Nuevo dashboard con KPIs globales, ranking de operadores por profit, tabla expandible con clientes y mini gráficas, tendencia de cargas creadas vs llegadas con filtro por operador, y barra de balance.",
  },
  {
    version: "4.45.0",
    date: "2026-03-11",
    type: "minor",
    title: "Sección colapsable Dashboards y página Operaciones",
    description: "El menú lateral ahora agrupa Dashboard Principal y el nuevo Dashboard de Operaciones en una sección colapsable 'Dashboards'. Se eliminó Reportes del menú y se agregó un separador visual.",
  },
  {
    version: "4.44.0",
    date: "2026-03-11",
    type: "minor",
    title: "Eliminar proveedores (solo administradores)",
    description: "Los administradores pueden eliminar proveedores desde su detalle, con doble confirmación de seguridad y registro en bitácora.",
  },
  {
    version: "4.43.1",
    date: "2026-03-11",
    type: "patch",
    title: "Mercancía general muestra todos los campos sin condición de modo",
    description: "Tipo de Unidad, Peso, Volumen y Piezas se muestran siempre en la sección de mercancía general, independientemente del modo de transporte.",
  },
  {
    version: "4.43.0",
    date: "2026-03-11",
    type: "minor",
    title: "Editar cotizaciones en estado Borrador",
    description: "Los operadores y administradores pueden editar cotizaciones cuando están en estado Borrador. Se reutiliza el wizard de 4 pasos con los datos pre-llenados desde la cotización guardada.",
  },
  {
    version: "4.42.0",
    date: "2026-03-11",
    type: "minor",
    title: "Campo 'Tipo de Unidad' para modo Terrestre en cotizaciones",
    description: "Al seleccionar modo Terrestre, se ocultan Peso, Volumen y Piezas y se muestra un campo de texto libre 'Tipo de Unidad' (Ej. Trailer, Caja seca, Plataforma, Rabón).",
  },
  {
    version: "4.41.0",
    date: "2026-03-11",
    type: "minor",
    title: "Operadores pueden eliminar cotizaciones",
    description: "Los usuarios con rol operador ahora pueden eliminar cotizaciones. Se implementó doble confirmación para mayor seguridad.",
  },
  {
    version: "4.40.0",
    date: "2026-03-11",
    type: "minor",
    title: "Agregar incoterm 'N/A'",
    description: "Se añadió la opción 'N/A' al dropdown de incoterm en cotizaciones y embarques.",
  },
  {
    version: "4.39.0",
    date: "2026-03-11",
    type: "minor",
    title: "Agregar tipo de operación 'Intra USA'",
    description: "Se añadió la opción 'Intra USA' al dropdown de tipo de operación en cotizaciones y embarques.",
  },
  {
    version: "4.38.1",
    date: "2026-03-11",
    type: "patch",
    title: "Simplificar etiqueta de contenedores en cotización",
    description: "Se cambió el texto 'Número de contenedores/Embarques' a 'Número de contenedores' en el formulario de nueva cotización.",
  },
  {
    version: "4.38.0",
    date: "2026-03-11",
    type: "minor",
    title: "Filtro por operador en tablero de embarques",
    description: "Se agregó un dropdown para filtrar embarques por operador asignado en la vista principal.",
  },
  {
    version: "4.37.5",
    date: "2026-03-11",
    type: "patch",
    title: "Agregar tipo de contenedor 20' GP",
    description: "Se añadió la opción 20' GP a todos los dropdowns de tipo de contenedor en embarques y cotizaciones.",
  },
  {
    version: "4.37.4",
    date: "2026-03-11",
    type: "patch",
    title: "Formato legible de timestamp en Notas y Actividad",
    description: "Las fechas en la pestaña Notas y Actividad del embarque ahora muestran formato DD/MM/YYYY, HH:mm localizado (es-MX) en lugar del formato ISO crudo.",
  },
  {
    version: "4.37.3",
    date: "2026-03-10",
    type: "patch",
    title: "Unificar catálogo de conceptos embarques ↔ cotizaciones",
    description: "CATALOGO_CONCEPTOS en embarqueConstants.ts ahora contiene los mismos 18 conceptos usados en cotizaciones, eliminando discrepancias entre módulos.",
  },
  {
    version: "4.37.2",
    date: "2026-03-10",
    type: "patch",
    title: "Limpieza: eliminar componente legacy de costos internos",
    description: "Se removió SeccionCostosInternosCotizacion (no utilizado) reemplazado por SeccionCostosInternosPLUnificado.",
  },
  {
    version: "4.37.1",
    date: "2026-03-10",
    type: "patch",
    title: "Fix setValue en vinculación de cotización y soporte Cross Trade",
    description: "Corregido el problema donde los campos controlados (Select, Combobox) no se actualizaban al vincular/desvincular una cotización. Se agregó 'Cross Trade' al listado de tipos de operación en embarques.",
  },
  {
    version: "4.37.0",
    date: "2026-03-10",
    type: "minor",
    title: "Vincular cotización existente al crear embarque",
    description: "Al crear un nuevo embarque se puede vincular opcionalmente una cotización con estado 'Aceptada'. Se pre-llenan los campos del formulario y al guardar la cotización cambia a 'Embarcada'.",
  },
  {
    version: "4.36.7",
    date: "2026-03-10",
    type: "patch",
    title: "Corrección de datos: COT-2026-0007 a Aceptada",
    description: "Se corrigió el estado de la cotización COT-2026-0007 que quedó como 'Embarcada' sin embarques activos, revirtiéndola a 'Aceptada'.",
  },
  {
    version: "4.36.6",
    date: "2026-03-10",
    type: "patch",
    title: "Revertir cotización al eliminar embarque vinculado",
    description: "Al eliminar un embarque que tiene cotización vinculada, si no quedan más embarques asociados a esa cotización, el estado se revierte automáticamente a 'Aceptada'.",
  },
  {
    version: "4.36.5",
    date: "2026-03-10",
    type: "patch",
    title: "Políticas RLS permisivas para eliminar embarques",
    description: "Se agregaron políticas DELETE permisivas en 6 tablas (embarques, conceptos_venta, conceptos_costo, documentos_embarque, notas_embarque, facturas) para que la eliminación en cascada funcione correctamente para roles admin y operador.",
  },
  {
    version: "4.36.4",
    date: "2026-03-10",
    type: "minor",
    title: "Eliminar embarques desde la lista",
    description: "Se agregó botón de eliminar por fila en la lista de embarques, visible en hover para roles admin y operador, con flujo de doble confirmación y registro en bitácora.",
  },
  {
    version: "4.36.3",
    date: "2026-03-10",
    type: "patch",
    title: "Estado 'Embarcada' en cotizaciones al generar embarques",
    description: "Al convertir una cotización en embarques, el estado ahora cambia a 'Embarcada' en lugar de 'Convertida'. Se agregó el filtro y badge con color índigo para el nuevo estado.",
  },
  {
    version: "4.36.2",
    date: "2026-03-10",
    type: "patch",
    title: "Barra de progreso de facturación en resumen del mes siguiente",
    description: "Se agregó una barra de progreso visual con porcentaje en la tarjeta de Facturados del resumen del mes siguiente. La barra cambia de color según el avance: verde (≥75%), amarillo (25-74%) y rojo (<25%).",
  },
  {
    version: "4.36.1",
    date: "2026-03-10",
    type: "patch",
    title: "Simplificar confirmación de eliminación en DocumentChecklist",
    description: "Se reemplazó el flujo de doble confirmación por un solo diálogo directo al eliminar archivos adjuntos, corrigiendo el bug donde la segunda confirmación no ejecutaba la eliminación.",
  },
  {
    version: "4.36.0",
    date: "2026-03-10",
    type: "minor",
    title: "Profit filtrado por mes + Tabla de embarques mes siguiente con facturación",
    description: "La tabla de Profit USD ahora muestra solo embarques con arribo este mes. Se reemplazó la tabla de embarques activos por una vista del mes siguiente con resumen de facturación (venta, costo, profit, facturados vs pendientes) y columna de estado de facturación.",
  },
  {
    version: "4.35.0",
    date: "2026-03-09",
    type: "minor",
    title: "Línea de tiempo visual + Indicador de arribos y profit",
    description: "Se reemplazaron las tarjetas de estado del Dashboard por una línea de tiempo horizontal interactiva con 5 nodos (Confirmado → En Tránsito → Arribo → En Aduana → Entregado). Se agregó indicador compacto de arribos del mes con métricas de ya llegaron, en camino y profit USD proyectado.",
  },
  {
    version: "4.34.0",
    date: "2026-03-09",
    type: "minor",
    title: "Tarjeta 'Arribos este mes' en Dashboard",
    description: "Se agregó una tarjeta informativa al final de la fila de estados del Dashboard que muestra el conteo de embarques con ETA dentro del mes en curso. Estilo consistente con las tarjetas existentes, barra cyan decorativa.",
  },
  {
    version: "4.33.1",
    date: "2026-03-09",
    type: "patch",
    title: "Corregir registro duplicado de logins en bitácora",
    description: "El evento SIGNED_IN de autenticación se disparaba en cada refresh de token y recarga de página, generando miles de registros falsos de login. Ahora se usa un ref para registrar solo el primer login real por sesión del componente.",
  },
  {
    version: "4.33.0",
    date: "2026-03-09",
    type: "minor",
    title: "Mejoras completas en la Bitácora de Actividad",
    description: "Se filtran logins por defecto con toggle para incluirlos. Se corrigieron nombres de acciones inconsistentes (crear cotización, editar_cliente, cambiar_estado). Se agregó tracking para facturas. Se añadió módulo Cotizaciones a filtros y rutas de navegación. Nuevos íconos para agregar_nota y eliminar_documento.",
  },
  {
    version: "4.32.2",
    date: "2026-03-09",
    type: "patch",
    title: "Corregir eliminación de documentos en embarques",
    description: "El botón Eliminar en el detalle del embarque ahora muestra un diálogo de confirmación antes de proceder. La función de eliminación ahora borra el registro completo de la base de datos y el archivo de Storage, en lugar de solo limpiar el campo.",
  },
  {
    version: "4.32.1",
    date: "2026-03-09",
    type: "patch",
    title: "Eliminar archivos adjuntos con doble confirmación",
    description: "Los operadores pueden eliminar archivos adjuntos en el paso de Documentos Requeridos al crear un embarque. Incluye doble confirmación para evitar borrados accidentales.",
  },
  {
    version: "4.32.0",
    date: "2026-03-09",
    type: "minor",
    title: "Nuevo sistema de estados de embarques",
    description: "7 estados en orden: Confirmado → En Tránsito → Arribo → En Aduana → Entregado → EIR → Cerrado. Cálculo automático solo para importaciones marítimas. Arribo reemplaza la detección automática post-ETA. Nuevos colores semánticos por estado.",
  },
  {
    version: "4.31.0",
    date: "2026-03-09",
    type: "minor",
    title: "Dashboard completo de Reportes",
    description: "Expansión mayor con filtro de período, 4 nuevas secciones (Panorama General, Operaciones, Ventas, Rentabilidad) y métricas avanzadas.",
  },
  {
    version: "4.30.5",
    date: "2026-03-07",
    type: "patch",
    title: "Page break en PDF de cotización",
    description: "Se agregó un salto de página en el PDF generado de cotización para separar los datos generales y mercancía (página 1) de los conceptos de venta, resumen y notas (página 2).",
  },
  {
    version: "4.30.4",
    date: "2026-03-07",
    type: "patch",
    title: "Formato de fecha legible en tabla de Cotizaciones",
    description: "La columna Fecha ahora muestra día/mes/año y hora en formato es-MX (ej. 05/03/2026, 14:35) en lugar del timestamp crudo.",
  },
  {
    version: "4.30.3",
    date: "2026-03-07",
    type: "patch",
    title: "Desglose correcto de totales en PDF de cotización",
    description: "Se corrigió el bloque de resumen del PDF para mostrar subtotal, IVA y total por separado en USD y MXN, con visualización condicional según los conceptos existentes.",
  },
  {
    version: "4.30.2",
    date: "2026-03-07",
    type: "patch",
    title: "Corrección de nombres de puerto duplicados en tablas de embarques",
    description: "Se mejoró la lógica de extracción del nombre corto de puertos en la tabla de Embarques Activos del Dashboard y en el listado principal de Embarques para manejar correctamente datos guardados con el formato anterior.",
  },
  {
    version: "4.30.1",
    date: "2026-03-07",
    type: "patch",
    title: "Corrección de nombre duplicado en selector de puertos",
    description: "Se ajustó la función shortName para extraer solo el nombre del puerto sin repetir cuando el valor ya viene en formato 'Nombre - Ciudad, País'.",
  },
  {
    version: "4.30.0",
    date: "2026-03-07",
    type: "minor",
    title: "Generar PDF de cotización",
    description: "Nuevo botón en CotizacionDetalle para generar un PDF profesional con header de empresa, datos generales, mercancía (general, FCL, LCL, aérea con dimensiones), tablas de conceptos USD y MXN, resumen de totales, notas y sello de propuesta.",
  },
  {
    version: "4.29.0",
    date: "2026-03-07",
    type: "minor",
    title: "Sección de mercancía contextual en detalle de cotización",
    description: "El detalle de cotización ahora muestra una Card de mercancía que se adapta al modo de transporte: información general para todos, tabla de contenedor para FCL, tabla de dimensiones con cálculo de volumen para LCL, y tabla de dimensiones con peso volumétrico para Aéreo.",
  },
  {
    version: "4.28.0",
    date: "2026-03-07",
    type: "minor",
    title: "Detalle completo de cotización con conceptos de venta",
    description: "Página de detalle de cotización con datos generales, mercancía (peso, volumen, piezas), tablas independientes de conceptos USD y MXN con subtotales, IVA y total. Incluye botones para cambiar estado (Enviar, Confirmar, Rechazar, Aceptar), convertir prospecto a cliente y resumen de totales en ambas monedas.",
  },
  {
    version: "4.27.0",
    date: "2026-03-07",
    type: "minor",
    title: "Tabla de cotizaciones con filtros y búsqueda",
    description: "Nueva vista de listado de cotizaciones con búsqueda por texto, filtros por estado y modo de transporte, paginación y acceso al detalle. Cada fila muestra folio, cliente, modo, tipo, ruta, estado con badge de color y fecha de creación.",
  },
  {
    version: "4.26.0",
    date: "2026-03-07",
    type: "minor",
    title: "Conceptos de Venta en cotización (USD y MXN)",
    description: "Sección de conceptos de venta dividida en USD y MXN con campos de descripción, cantidad, precio unitario, total y dropdown de unidad de medida. Totales automáticos por moneda con subtotal, IVA (solo MXN) y total. IVA de 16% aplicado automáticamente a MXN.",
  },
  {
    version: "4.25.0",
    date: "2026-03-07",
    type: "minor",
    title: "Sección de ruta dinámica en cotización",
    description: "Nueva sección de Ruta en el formulario de cotización que se adapta al modo de transporte. Marítimo muestra puertos con autocompletado y selector de tipo de embarque (FCL/LCL). Aéreo muestra aeropuertos. Terrestre muestra ciudades. Multimodal combina puertos y ciudades.",
  },
  {
    version: "4.24.0",
    date: "2026-03-07",
    type: "minor",
    title: "Formulario de nueva cotización con datos generales y mercancía",
    description: "Nuevo formulario de cotización con secciones de datos generales (cliente/prospecto, modo, tipo, incoterm, moneda, operador) y mercancía (descripción, peso, volumen, piezas). Folio auto-generado con formato COT-YYYY-NNNN.",
  },
  {
    version: "4.23.0",
    date: "2026-03-07",
    type: "minor",
    title: "Tabla de cotizaciones y esquema de base de datos",
    description: "Nueva tabla cotizaciones en la BD con 30+ campos. Enums estado_cotizacion y tipo_servicio_maritimo. Tabla cotizacion_costos para costos internos P&L. RLS habilitado. Vista inicial con listado paginado, búsqueda y filtros por estado/modo.",
  },
  {
    version: "4.22.0",
    date: "2026-03-07",
    type: "minor",
    title: "Utilidades financieras centralizadas",
    description: "Creado src/lib/financialUtils.ts con funciones de cálculo de IVA, subtotales, márgenes y conversión de moneda. src/lib/profitUtils.tsx con badge de profit y cálculo de totales P&L. Eliminación de math inline disperso en componentes.",
  },
  {
    version: "4.21.1",
    date: "2026-03-07",
    type: "patch",
    title: "Auditoría completa de math inline",
    description: "Auditoría completa de math inline: useConceptosForm ahora envuelve subtotalVenta/totalCosto/utilidadEstimada en useMemo con calcularUtilidad. useCotizacionWizardForm usa calcularIVA/calcularTotalConIVA. EmbarqueDetalle envuelve reduces en useMemo antes de early returns. Reportes usa convertirAMXN y calcularMargen centralizados. profitUtils migrado a tokens semánticos (success/warning/destructive). Todas las funciones de financialUtils y profitUtils con return types estrictos.",
  },
  {
    version: "4.21.0",
    date: "2026-03-07",
    type: "minor",
    title: "Refactorización de formularios de embarque con React Hook Form",
    description: "Migrado useEmbarqueForm a react-hook-form (useForm/FormProvider). StepDatosGenerales, StepDatosRuta y StepCostosPrecios ahora usan useFormContext eliminando ~40 props de prop drilling. Inputs de texto usan register() (no controlados) para evitar re-renders innecesarios. NuevoEmbarque y EditarEmbarque simplificados como orquestadores de UI.",
  },
  {
    version: "4.20.0",
    date: "2026-03-07",
    type: "minor",
    title: "Refactorización de NuevaCotizacion — hook useCotizacionWizardForm",
    description: "Extraído todo el estado (~30 useState), lógica de navegación, validación, persistencia y cálculos del wizard de cotizaciones al hook useCotizacionWizardForm. NuevaCotizacion.tsx reducido de 577 a ~220 líneas como orquestador puro de UI. Cálculos envueltos en useMemo y acciones en useCallback.",
  },
  {
    version: "4.19.0",
    date: "2026-03-07",
    type: "minor",
    title: "Centralización de cálculos financieros",
    description: "Tipo estricto Moneda y función convertirAUSD agregados a financialUtils.ts. Interface TotalesPL y return type explícito en profitUtils.tsx. Inline math de márgenes y utilidad reemplazado en useDashboardData, StepCostosPrecios y SeccionCostosInternosPLUnificado con funciones centralizadas. Totales en StepCostosPrecios envueltos en useMemo.",
  },
  {
    version: "4.18.0",
    date: "2026-03-07",
    type: "minor",
    title: "Unificación de TablaConceptos y SeccionCostosInternosPL",
    description: "TablaConceptosUSD y TablaConceptosMXN consolidados en TablaConceptosGenerico con prop moneda. SeccionCostosInternosPL y SeccionCostosInternosPLLocal unificados en SeccionCostosInternosPLUnificado con prop tipo ('detalle'|'local'). Extraído ResumenPL como componente compartido. Eliminados 4 archivos redundantes.",
  },
  {
    version: "4.17.0",
    date: "2026-03-07",
    type: "minor",
    title: "Refactorización masiva del proyecto",
    description: "useEmbarques.ts separado en useEmbarqueQueries, useEmbarqueMutations y useEmbarqueUtils con barrel re-export. EmbarqueDetalle.tsx refactorizado extrayendo DialogDuplicarEmbarque y DialogEliminarEmbarque. Configuracion.tsx modularizado en 7 tabs independientes (TabEmpresa, TabTiposCambio, TabCotizaciones, TabFacturacion, TabEmbarques, TabAlertas, TabPuertos). Creado financialUtils.ts con funciones centralizadas de IVA, subtotales, márgenes y conversión de moneda. Constantes ESTADOS_EMBARQUE, MODOS_TRANSPORTE y ESTADOS_ACTIVOS unificadas en embarqueConstants.ts.",
  },
  {
    version: "4.16.1",
    date: "2026-03-07",
    type: "patch",
    title: "Refactorización completa del Dashboard",
    description: "Se extrajo la lógica de datos a useDashboardData hook y se crearon 5 sub-componentes (DashboardStatusCards, AlertasDemoraCard, ProximosArribosCard, ProfitTable, EmbarquesActivosTable). Se reemplazaron colores HSL hardcodeados por tokens semánticos del design system.",
  },
  {
    version: "4.16.0",
    date: "2026-03-06",
    type: "minor",
    title: "Rediseño completo del Dashboard",
    description: "Nuevo dashboard estilo command center con resumen por estado (Confirmado, En Tránsito, En Aduana, Entregado) con filtrado interactivo, alertas de demora en aduana, próximos arribos en 7 días, tabla de profit USD por embarque con margen, y lista de embarques activos filtrable. Se eliminaron secciones de facturas, gastos, gráfica Recharts y bitácora.",
  },
  {
    version: "4.15.7",
    date: "2026-03-06",
    type: "minor",
    title: "Tipo de operación Cross Trade en cotizaciones",
    description: "Se agrega la opción 'Cross Trade' al dropdown de tipo de operación en datos generales de cotización.",
  },
  {
    version: "4.15.6",
    date: "2026-03-06",
    type: "patch",
    title: "Cantidad decimal en P&L",
    description: "El campo de cantidad en la sección de costos P&L ahora acepta valores decimales con punto.",
  },
  {
    version: "4.15.5",
    date: "2026-03-06",
    type: "patch",
    title: "Permiso de eliminación de embarques para operadores",
    description: "El equipo operativo (rol operador) ahora puede eliminar embarques con la misma doble confirmación de seguridad que los administradores.",
  },
  {
    version: "4.15.4",
    date: "2026-03-06",
    type: "minor",
    title: "Estado automático para embarques marítimos",
    description: "Los embarques marítimos ahora calculan su estado automáticamente según ETD/ETA: Confirmado (antes de ETD), En Tránsito (entre ETD y ETA), En Aduana (después de ETA). Se agregan los estados En Aduana, Entregado y Cancelado al enum. Estado inicial cambiado de Cotización a Confirmado.",
  },
  {
    version: "4.15.3",
    date: "2026-03-06",
    type: "patch",
    title: "Centralizar constantes de cotización",
    description: "Se crea src/data/cotizacionConstants.ts con CONCEPTOS_COSTO_USD, CONCEPTOS_COSTO_MXN y CONCEPTOS_CON_IVA_USD. Los componentes SeccionCostosInternosPLLocal, SeccionConceptosVentaCotizacion y NuevaCotizacion ahora importan desde este archivo centralizado.",
  },
  {
    version: "4.15.2",
    date: "2026-03-06",
    type: "patch",
    title: "Columna Unidad y IVA condicional en PDF de cotización",
    description: "Se agrega la columna 'Unidad' en las tablas de conceptos USD y MXN del PDF. Los conceptos USD con IVA ahora muestran columnas de Subtotal e IVA condicionalmente. Se actualiza el texto del pie a 'Los cargos en destino incluyen IVA'.",
  },
  {
    version: "4.15.1",
    date: "2026-03-06",
    type: "patch",
    title: "Duplicar embarque conserva expediente del origen",
    description: "Al duplicar un embarque, las copias ahora conservan el mismo número de expediente del embarque origen en lugar de generar uno nuevo.",
  },
  {
    version: "4.15.0",
    date: "2026-03-06",
    type: "minor",
    title: "Eliminar Embarque (solo Admin)",
    description: "Nuevo botón para eliminar embarques de forma permanente, disponible exclusivamente para administradores. Incluye doble confirmación de seguridad y eliminación en cascada de todos los registros relacionados (documentos, costos, conceptos de venta, notas y facturas). La acción queda registrada en la bitácora.",
  },
  {
    version: "4.14.0",
    date: "2026-03-06",
    type: "minor",
    title: "Duplicar Embarque",
    description: "Nueva funcionalidad para duplicar un embarque existente creando 1 a 10 copias con contenedores independientes. Copia automáticamente cliente, BL, naviera, ruta, fechas, conceptos de venta y costos internos. Accesible desde el detalle del embarque para admin y operador.",
  },
  {
    version: "4.13.0",
    date: "2026-03-06",
    type: "minor",
    title: "Refactorización: utilidades P&L, componentes extraídos y helpers consolidados",
    description: "Se extrajo profitBadge, calcularTotalesPL y rentabilidadGlobal a src/lib/profitUtils.tsx eliminando duplicación en 3 archivos. Se creó PasoResumenCotizacion.tsx y SeccionMercanciaCotizacionDetalle.tsx como componentes independientes. Se consolidaron helpers USD/MXN en funciones parametrizadas. NuevaCotizacion.tsx se redujo ~120 líneas y CotizacionDetalle.tsx ~130 líneas.",
  },
  {
    version: "4.12.0",
    date: "2026-03-06",
    type: "minor",
    title: "Botón eliminar cotización (solo admin)",
    description: "Se agregó una columna de acciones en la tabla de cotizaciones con botón de eliminar visible únicamente para administradores. Incluye confirmación con AlertDialog antes de proceder.",
  },
  {
    version: "4.11.2",
    date: "2026-03-06",
    type: "patch",
    title: "Corregir pre-llenado Paso 2 → Paso 3 en wizard de cotización",
    description: "El pre-llenado del Paso 3 ahora se ejecuta directamente al avanzar desde el Paso 2, eliminando la dependencia del useEffect que causaba problemas de sincronización. Se removió la prop redundante onCostosChange.",
  },
  {
    version: "4.11.1",
    date: "2026-03-06",
    type: "patch",
    title: "Corregir validación Paso 3 → Paso 4 en wizard de cotización",
    description: "La validación del Paso 3 ahora filtra conceptos con descripción vacía en lugar de rechazarlos. Solo se guardan en la base de datos los conceptos válidos. Se requiere al menos un concepto con descripción para avanzar.",
  },
  {
    version: "4.11.0",
    date: "2026-03-05",
    type: "minor",
    title: "Guardado progresivo por paso en wizard de cotización",
    description: "El wizard de nueva cotización ahora guarda en la base de datos en cada paso: Paso 1 crea/actualiza la cotización, Paso 2 guarda costos internos, Paso 3 actualiza conceptos de venta y Paso 4 finaliza como Borrador. Si ocurre un error en cualquier paso, no avanza al siguiente.",
  },
  {
    version: "4.10.6",
    date: "2026-03-05",
    type: "patch",
    title: "Corregir pre-llenado IVA del Paso 3 desde Paso 2",
    description: "Se agregó callback onCostosChange en SeccionCostosInternosPLLocal para sincronizar estado con el wizard. El pre-llenado del Paso 3 ahora aplica IVA automático solo a conceptos USD específicos (Handling, Desconsolidación, Revalidación, Demoras, Cargos en Destino, Release) y siempre IVA para MXN.",
  },
  {
    version: "4.10.5",
    date: "2026-03-05",
    type: "patch",
    title: "Actualizar catálogos y lógica de IVA en Cotización Cliente",
    description: "Se actualizaron los catálogos de conceptos USD (16 opciones) y MXN (3 opciones) en la sección Cotización Cliente. Se amplió CONCEPTOS_CON_IVA para incluir Demoras, Cargos en Destino y Release. Al seleccionar un concepto con IVA, aplica_iva se activa automáticamente.",
  },
  {
    version: "4.10.4",
    date: "2026-03-05",
    type: "patch",
    title: "Actualizar catálogos de conceptos en Costos & P&L",
    description: "Se reemplazaron los catálogos de conceptos USD y MXN en el wizard de cotización. USD ahora incluye 16 opciones (Cargos en Origen, Costos Portuarios, Consolidación, Seguro, Recolección, Modificación de BL, Flete Marítimo/Aéreo/Terrestre, Handling, Desconsolidación, Revalidación, Demoras, Cargos en Destino, Release, Otro). MXN se simplificó a 3 opciones (Entrega Nacional, Honorarios de Despacho Aduanal, Otro).",
  },
  {
    version: "4.10.3",
    date: "2026-03-05",
    type: "patch",
    title: "Agregar 'Cargos en Destino' al catálogo USD",
    description: "Se añadió la opción 'Cargos en Destino' al dropdown de conceptos en USD dentro del wizard de nueva cotización (SeccionCostosInternosPLLocal).",
  },
  {
    version: "4.10.2",
    date: "2026-03-05",
    type: "patch",
    title: "Botón eliminar documentos en embarque",
    description: "Se agregó un botón 'Eliminar' en la pestaña de documentos del detalle de embarque. Permite borrar el archivo adjunto de Storage y regresar el estado del documento a 'Pendiente' para subir uno nuevo. La acción queda registrada en la bitácora.",
  },
  {
    version: "4.10.1",
    date: "2026-03-05",
    type: "patch",
    title: "Layout de dos líneas y catálogo de conceptos en Costos P&L",
    description: "Rediseño del componente SeccionCostosInternosPLLocal: cada fila se muestra en dos líneas (concepto/proveedor/unidad + cantidad/costo/venta/profit). El campo Concepto ahora es un Select con catálogo predefinido por moneda (USD/MXN). Se eliminó la tabla apretada en favor de un layout espacioso sin scroll horizontal.",
  },
  {
    version: "4.10.0",
    date: "2026-03-05",
    type: "minor",
    title: "Wizard de 4 pasos en Nueva Cotización",
    description: "Rediseño de NuevaCotizacion como wizard con 4 pasos: Datos Generales, Costos & P&L (con SeccionCostosInternosPLLocal), Cotización Cliente (pre-llenado automático desde costos) y Resumen con P&L y datos de operación. Incluye campo Número de Embarques y navegación con StepIndicator.",
  },
  {
    version: "4.9.5",
    date: "2026-03-05",
    type: "minor",
    title: "Botón Generar Embarques y card de embarques vinculados",
    description: "En CotizacionDetalle se agrega botón para convertir cotización aceptada en embarques con diálogo de confirmación, y una card que lista los embarques generados con links navegables.",
  },
  {
    version: "4.9.4",
    date: "2026-03-05",
    type: "minor",
    title: "Hook para convertir cotización en embarques",
    description: "Nuevo hook useConvertirCotizacionAEmbarques que crea automáticamente embarques a partir de una cotización según num_contenedores, mapeando costos por unidad_medida (Contenedor, BL, W/M) y actualizando el estado a Convertida.",
  },
  {
    version: "4.9.3",
    date: "2026-03-05",
    type: "patch",
    title: "Migración de esquema: contenedores, cotización-embarque y P&L en costos",
    description: "Se agregó num_contenedores a cotizaciones, cotizacion_id a embarques, y columnas de precio_venta, precio_total, profit, porcentaje_profit y unidad_medida a cotizacion_costos (con columnas generadas).",
  },
  {
    version: "4.9.2",
    date: "2026-03-05",
    type: "patch",
    title: "Corrección de inputs numéricos en conceptos de cotización",
    description: "Los campos de cantidad y precio unitario en conceptos USD y MXN ahora limpian el 0 inicial al hacer clic y validan correctamente el formato numérico/decimal.",
  },
  {
    version: "4.9.1",
    date: "2026-03-05",
    type: "patch",
    title: "Campo Agente en Datos de Ruta marítimo",
    description: "Nuevo campo de texto libre 'Agente' en la sección marítima de Datos de Ruta, junto al campo Naviera. Disponible en creación y edición de embarques.",
  },
  {
    version: "4.9.0",
    date: "2026-03-04",
    type: "minor",
    title: "Catálogo de puertos configurable",
    description: "Los puertos de origen/destino en cotizaciones y embarques ahora se administran desde Configuración → Puertos. Se pueden agregar, desactivar y eliminar puertos. La tabla 'puertos' en la base de datos reemplaza el catálogo estático anterior.",
  },
  {
    version: "4.8.5",
    date: "2026-03-04",
    type: "patch",
    title: "Formato de moneda mexicana en todos los campos de dinero",
    description: "Reemplazados todos los formatos manuales de dinero con formatCurrency() usando Intl.NumberFormat('es-MX') en StepCostosPrecios, SeccionConceptosVentaCotizacion, CotizacionDetalle y cotizacionPdf. Separadores de miles y decimales consistentes en toda la app.",
  },
  {
    version: "4.8.4",
    date: "2026-03-04",
    type: "patch",
    title: "Refactorización: duplicados, sub-componentes y nombres",
    description: "Fase 1: Eliminado useClientesForSelect duplicado de useEmbarques, fmt local reemplazado por formatCurrency, CONCEPTOS_CON_IVA consolidado, calcularPL muerta eliminada, import Input no usado removido. Fase 2: Extraídos TablaConceptosUSD, TablaConceptosMXN, ResumenTotalesCotizacion y DialogConvertirProspecto de CotizacionDetalle (~488→~300 líneas). Fase 3: Variables crípticas renombradas (qc→queryClient, totUSD→totalesUSD, totMXN→totalesMXN).",
  },
  {
    version: "4.8.3",
    date: "2026-03-04",
    type: "patch",
    title: "P&L siempre calcula profit sin IVA",
    description: "Corregido el módulo de Costos Internos P&L para que todos los cálculos de profit usen subtotales sin IVA. La columna Venta muestra el valor neto con etiqueta visual '+ IVA' como referencia.",
  },
  {
    version: "4.8.2",
    date: "2026-03-04",
    type: "minor",
    title: "IVA condicional en conceptos USD",
    description: "Toggle switch de IVA 16% para conceptos Handling, Desconsolidación y Revalidación en la tabla USD de cotizaciones. Footer dinámico con desglose de subtotal, IVA y total cuando aplica.",
  },
  {
    version: "4.8.1",
    date: "2026-03-04",
    type: "patch",
    title: "Nuevos conceptos en catálogos de venta",
    description: "Se agregan Revalidación, Handling, Desconsolidación y Entrega Nacional a los dropdowns de conceptos USD y MXN en cotizaciones.",
  },
  {
    version: "4.8.0",
    date: "2026-03-04",
    type: "minor",
    title: "Unidad de Medida en conceptos de venta",
    description: "Nuevo campo dropdown 'Unidad de Medida' en ambas tablas de conceptos (USD y MXN) con opciones: BL, W/M, Documento, Contenedor, Kilo, Embarque. Visible también en el detalle de cotización.",
  },
  {
    version: "4.7.0",
    date: "2026-03-04",
    type: "minor",
    title: "Sección de Costos Internos P&L por moneda",
    description: "Nuevo componente SeccionCostosInternosPL con tablas separadas USD y MXN, pre-poblado automático desde conceptos de venta, cálculo de profit y % por fila, resumen colapsable con totales por moneda. Visible solo para admin y operador.",
  },
  {
    version: "4.6.0",
    date: "2026-03-04",
    type: "minor",
    title: "Reestructuración de costos internos de cotización",
    description: "Nueva tabla cotizacion_costos con campos de concepto, proveedor, unidad, cantidad, costo unitario y moneda. CRUD completo con hook dedicado useCotizacionCostos. Cards de resumen por moneda con totales calculados.",
  },
  {
    version: "4.5.0",
    date: "2026-03-04",
    type: "minor",
    title: "Agregar contacto desde detalle de cliente",
    description: "Nuevo botón y diálogo para agregar contactos (Proveedor, Exportador o Importador) directamente desde la página de detalle del cliente. El contacto se registra en bitácora.",
  },
  {
    version: "4.4.0",
    date: "2026-03-04",
    type: "minor",
    title: "Búsqueda global (⌘+K)",
    description: "Nuevo buscador global accesible desde cualquier página con el shortcut ⌘+K (o Ctrl+K). Busca en embarques, clientes, proveedores y facturas simultáneamente.",
  },
  {
    version: "4.3.0",
    date: "2026-03-03",
    type: "minor",
    title: "Navegación lateral con secciones colapsables",
    description: "Sidebar actualizado a ShadCN sidebar component con secciones colapsables para cada módulo, subniveles jerárquicos, y estilos consistentes con el design system.",
  },
  {
    version: "4.2.1",
    date: "2026-03-03",
    type: "patch",
    title: "Dropdown de conceptos en cotizaciones",
    description: "Se reemplazó el campo de texto libre 'Descripción' por un dropdown 'Concepto' con 8 opciones estandarizadas del catálogo (Flete Marítimo, Embalaje, Coordinación de Recolección, Seguro de Carga, Manejo, Demoras, Cargos en Destino, Cargos en Origen) en la sección de conceptos de venta de cotizaciones.",
  },
  {
    version: "4.2.0",
    date: "2026-03-03",
    type: "minor",
    title: "Mejora visual UI/UX integral",
    description: "Rediseño visual en 17 archivos sin cambios funcionales. Tablas con header uppercase tracking-wide y fondo sutil. KPI cards con borde izquierdo por categoría. Badges más compactos. Header global con shadow-sm y tipografía mejorada. Login con logo eLogistix y fondo gradiente. Filtros con gap-4 consistente. SearchInput con fondo sutil. Scrollbar personalizado. Tipografía con antialiased y font-feature-settings. Subtítulos descriptivos en todas las páginas.",
  },
  {
    version: "4.1.0",
    date: "2026-03-03",
    type: "minor",
    title: "Módulo de Configuración centralizado",
    description: "Nueva página /configuracion accesible solo para admins con 6 secciones: Datos de la Empresa, Tipos de Cambio por Defecto, Cotizaciones, Facturación, Embarques y Alertas del Dashboard. Tabla configuracion en BD con pares clave-valor por categoría, hook useConfiguracion con cache de 5 min, y useConfigValue para consumir valores individuales desde cualquier componente.",
  },
  {
    version: "4.0.0",
    date: "2026-03-02",
    type: "major",
    title: "Refactorización integral — Fases 1-4",
    description: "Fase 1: Eliminación de propiedad muerta 'iva' en tipos e inicializaciones, y funciones vacías isStep1Valid/isStep2Valid. Fase 2: Hook centralizado useEmbarqueForm con ~35 estados, handleMsdsUpload y builders de payload, eliminando ~200 líneas duplicadas entre NuevoEmbarque y EditarEmbarque. Fase 3: Componente DocumentChecklist reutilizable, usado en Clientes y NuevoProveedorDialog. Fase 4: NuevaCotizacion descompuesta en SeccionDestinatario, SeccionDatosGeneralesCotizacion, SeccionRutaCotizacion y SeccionConceptosVentaCotizacion.",
  },
];
