/**
 * StyleSheet centralizado para todos los documentos @react-pdf/renderer.
 * Mantén los colores y tipografías alineados a la marca (Primary #1B2B4B,
 * Accent #2563EB) en lugar de duplicar valores en cada Document.
 */
import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
  primary: "#0F4C81",
  primaryDark: "#1B2B4B",
  accent: "#2563EB",
  ink: "#1A1A2E",
  muted: "#555555",
  mutedLight: "#777777",
  border: "#DDDDDD",
  zebra: "#F8FAFC",
  badgeBg: "#E0E7FF",
  badgeFg: "#3730A3",
  warningBg: "#FEF3C7",
  warningBorder: "#D97706",
  warningFg: "#92400E",
  infoBg: "#DBEAFE",
  infoFg: "#1E3A8A",
} as const;

/** Fuentes built-in (sin Font.register: 0 KB de fonts adicionales). */
export const FONTS = {
  regular: "Helvetica",
  bold: "Helvetica-Bold",
  oblique: "Helvetica-Oblique",
} as const;

export const styles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 48,
    paddingHorizontal: 32,
    fontSize: 10,
    fontFamily: FONTS.regular,
    color: COLORS.ink,
    lineHeight: 1.4,
  },
  // Header
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 3,
    borderBottomColor: COLORS.primary,
    paddingBottom: 12,
    marginBottom: 16,
  },
  h1: { fontSize: 18, fontFamily: FONTS.bold, color: COLORS.primary },
  h1Xl: { fontSize: 26, fontFamily: FONTS.bold, color: COLORS.primary, letterSpacing: 2 },
  numero: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.muted, marginTop: 4 },
  meta: { alignItems: "flex-end", fontSize: 9, color: COLORS.muted },
  metaLine: { marginTop: 3 },
  badge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: COLORS.badgeBg,
    color: COLORS.badgeFg,
    fontSize: 8,
    fontFamily: FONTS.bold,
  },
  badgeWarning: { backgroundColor: COLORS.warningBg, color: COLORS.warningFg },
  badgeInfo: { backgroundColor: COLORS.infoBg, color: COLORS.infoFg },
  // Headings
  h3: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingBottom: 3,
    marginTop: 14,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  h4: { fontSize: 10, fontFamily: FONTS.bold, color: COLORS.ink, marginTop: 10, marginBottom: 4 },
  paragraph: { marginTop: 4, marginBottom: 4 },
  // Key/Value grid (Flexbox: 4 columnas, wrap)
  gridRow: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -4 },
  gridCell4: { width: "25%", paddingHorizontal: 4, marginBottom: 6 },
  gridCell3: { width: "33.33%", paddingHorizontal: 4, marginBottom: 6 },
  gridCell2: { width: "50%", paddingHorizontal: 4, marginBottom: 6 },
  gridCellFull: { width: "100%", paddingHorizontal: 4, marginBottom: 6 },
  label: { fontSize: 8, color: COLORS.mutedLight },
  value: { fontSize: 10, fontFamily: FONTS.bold },
  // Tabla
  table: { marginTop: 4, borderTopWidth: 1, borderTopColor: COLORS.border },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.zebra,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
    minHeight: 18,
  },
  th: {
    paddingVertical: 5,
    paddingHorizontal: 6,
    fontSize: 9,
    fontFamily: FONTS.bold,
    color: COLORS.ink,
  },
  td: { paddingVertical: 4, paddingHorizontal: 6, fontSize: 9 },
  cellDesc: { flexGrow: 1, flexShrink: 1, flexBasis: 0 },
  cellNum: { width: 60, textAlign: "right" },
  cellNumWide: { width: 75, textAlign: "right" },
  cellQty: { width: 35, textAlign: "right" },
  // Resumen / Totales
  totalBox: {
    marginTop: 14,
    padding: 10,
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: 6,
  },
  totalLine: { fontSize: 11, fontFamily: FONTS.bold, color: COLORS.primary, marginVertical: 2, textAlign: "right" },
  totalNote: { fontSize: 8, color: COLORS.mutedLight, marginTop: 4, textAlign: "right" },
  subtotalBlock: { marginTop: 6, alignItems: "flex-end" },
  subtotalLine: { fontSize: 10, marginVertical: 1 },
  subtotalEmphasis: {
    fontSize: 12,
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    borderTopWidth: 1.5,
    borderTopColor: COLORS.primary,
    paddingTop: 3,
    marginTop: 3,
  },
  // KPIs
  kpiRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 6, marginBottom: 10, marginHorizontal: -3 },
  kpiCard: {
    width: "25%",
    paddingHorizontal: 3,
  },
  kpiInner: {
    backgroundColor: COLORS.zebra,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    padding: 8,
  },
  kpiLabel: { fontSize: 7, color: COLORS.muted, textTransform: "uppercase" },
  kpiValue: { fontSize: 13, fontFamily: FONTS.bold, marginTop: 3, color: COLORS.primaryDark },
  // Notas / avisos
  notesBox: { marginTop: 8, padding: 8, backgroundColor: COLORS.zebra, borderRadius: 4 },
  warningBox: {
    marginTop: 18,
    padding: 10,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.warningBorder,
    backgroundColor: COLORS.warningBg,
    borderRadius: 5,
    color: COLORS.warningFg,
    fontFamily: FONTS.bold,
    fontSize: 10,
    textAlign: "center",
  },
  containerBlock: {
    backgroundColor: COLORS.zebra,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginTop: 12,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    fontSize: 10,
  },
  // Footer fijo
  footer: {
    position: "absolute",
    bottom: 16,
    left: 32,
    right: 32,
    textAlign: "center",
    fontSize: 8,
    color: COLORS.mutedLight,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.border,
    paddingTop: 6,
  },
  pageNumber: { fontSize: 8, color: COLORS.mutedLight, marginTop: 2 },
});
