/** Captura → aprobación → pago del ID creado aquí. Sin borrados ni barridos. */
import { randomUUID } from "node:crypto";
import { expect, test } from "../fixtures/testBase";
import { internalCreds, loginAs } from "../fixtures/auth";
import { supabaseRest } from "../fixtures/api";
import { requireFixture } from "../fixtures/requireFixture";
import { attachFiscalRecords } from "../fixtures/fiscal";

const PROVEEDOR_ID = process.env.E2E_PROVEEDOR_ID ?? "";
const EMBARQUE_ID = process.env.E2E_EMBARQUE_PARA_CXP_ID ?? "";
const COSTO_ID = process.env.E2E_CONCEPTO_CXP_ID ?? "";
const CATEGORIA_ID = process.env.E2E_CATEGORIA_CXP_ID ?? "";

test.describe("Flujo 12 — CXP captura + aprobación + pago", () => {
  requireFixture([PROVEEDOR_ID, EMBARQUE_ID, COSTO_ID, CATEGORIA_ID].every(Boolean), "E2E_PROVEEDOR_ID / EMBARQUE_PARA_CXP_ID / CONCEPTO_CXP_ID / CATEGORIA_CXP_ID requeridos (semilla nueva MXN)");

  test("captura y paga exclusivamente su factura de maniobras", async ({ page }, info) => {
    await loginAs(page, internalCreds());
    const rest = supabaseRest(page);
    const [proveedor] = await rest.select("proveedores", { id: PROVEEDOR_ID, deleted_at: "is.null" }, "id,nombre,organization_id");
    const [embarque] = await rest.select("embarques", { id: EMBARQUE_ID, deleted_at: "is.null" }, "id,expediente,organization_id");
    const [cost] = await rest.select("conceptos_costo", { id: COSTO_ID, deleted_at: "is.null" }, "id,concepto,monto,moneda,proveedor_id,embarque_id,organization_id");
    const [category] = await rest.select("presupuesto_categorias", { id: CATEGORIA_ID }, "id,nombre,organization_id");
    expect(proveedor).toBeTruthy();
    expect(embarque).toBeTruthy();
    expect(category?.organization_id).toBe(proveedor.organization_id);
    expect(cost).toMatchObject({ id: COSTO_ID, proveedor_id: PROVEEDOR_ID, embarque_id: EMBARQUE_ID, moneda: "MXN", organization_id: proveedor.organization_id });
    expect(Number(cost.monto)).toBeGreaterThanOrEqual(1000);
    expect(embarque.organization_id).toBe(proveedor.organization_id);
    const folio = "MZN-" + randomUUID().slice(0, 8);
    await page.goto("/compras/por-capturar");
    await page.getByRole("button", { name: /capturar factura|nueva factura/i }).click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await dialog.getByRole("radio", { name: /capturar a mano/i }).click();
    await dialog.getByRole("button", { name: "Agregar concepto", exact: true }).click();
    await dialog.getByLabel("Descripción del concepto", { exact: true }).fill("Maniobras de desconsolidación en Manzanillo");
    await dialog.getByLabel("Cantidad", { exact: true }).fill("1");
    await dialog.getByLabel("Precio unitario", { exact: true }).fill("1000");
    await dialog.getByLabel("IVA del concepto", { exact: true }).fill("160");
    await dialog.getByRole("button", { name: "Continuar", exact: true }).click();
    await dialog.getByRole("combobox", { name: "Selecciona proveedor", exact: true }).click();
    await page.getByRole("option", { name: String(proveedor.nombre), exact: true }).click();
    await dialog.locator("#factura-prov-folio").fill(folio);
    await dialog.getByLabel("Subtotal", { exact: true }).fill("1000");
    await dialog.getByLabel("IVA", { exact: true }).fill("160");
    await dialog.getByRole("combobox", { name: "Selecciona la categoría contable de esta factura", exact: true }).click();
    await page.getByRole("option", { name: String(category.nombre), exact: true }).click();
    await dialog.getByRole("button", { name: "Continuar", exact: true }).click();
    await dialog.getByLabel("Filtrar conceptos por texto", { exact: true }).fill(String(embarque.expediente));
    const vinculo = dialog.getByRole("checkbox", { name: "Vincular " + cost.concepto, exact: true });
    await expect(vinculo, "un costo inequívoco de la semilla").toHaveCount(1);
    await vinculo.check();
    await dialog.getByLabel("Importe aplicado al concepto " + cost.concepto + " en MXN", { exact: true }).fill("1000");
    const createdResponse = page.waitForResponse(r => r.url().endsWith("/rpc/crear_factura_proveedor_vinculada_rpc") && r.request().method() === "POST");
    await dialog.getByRole("button", { name: "Guardar factura", exact: true }).click();
    const response = await createdResponse;
    expect(response.ok()).toBe(true);
    expect(response.request().postDataJSON().p_lineas).toEqual([{ concepto_costo_id: COSTO_ID, descripcion: cost.concepto, monto: 1000 }]);
    const factura = await response.json() as { id: string; folio_interno: string };
    expect(factura.id).toMatch(/^[0-9a-f-]{36}$/i);
    expect(factura.folio_interno).toMatch(/^FP-\d{6}$/);
    await attachFiscalRecords(info, { facturaId: factura.id, folioProveedor: folio, costId: COSTO_ID });
    const [own] = await rest.select("proveedor_facturas", { id: factura.id }, "proveedor_id,folio_proveedor,total,moneda");
    expect(own).toMatchObject({ proveedor_id: PROVEEDOR_ID, folio_proveedor: folio, moneda: "MXN" });
    expect(Number(own.total)).toBe(1160);
    await page.goto("/compras/facturas/" + factura.id);
    await page.getByRole("button", { name: "Aprobar factura", exact: true }).click();
    await page.getByRole("dialog").getByRole("button", { name: "Sí, aprobar", exact: true }).click();
    await expect.poll(async () => (await rest.select("proveedor_facturas", { id: factura.id }, "estado_aprobacion"))[0]?.estado_aprobacion).toBe("aprobada");
    await page.getByRole("button", { name: "Registrar pago", exact: true }).click();
    const payment = page.getByRole("dialog");
    await payment.locator("#pago-prov-monto").fill("1160");
    await payment.locator("label").filter({ hasText: /^Método$/ }).locator("..").getByRole("combobox").click();
    await page.getByRole("option", { name: "Efectivo", exact: true }).click();
    await payment.locator("#pago-prov-referencia").fill("REC-" + folio);
    const paid = page.waitForResponse(r => r.url().endsWith("/rpc/registrar_pago_proveedor_atomico") && r.request().method() === "POST");
    await payment.getByRole("button", { name: "Registrar pago", exact: true }).click();
    const paidResponse = await paid;
    expect(paidResponse.ok()).toBe(true);
    expect(paidResponse.request().postDataJSON().p_factura_id).toBe(factura.id);
    await expect.poll(async () => {
      const pagos = await rest.select("pagos_proveedor", { proveedor_factura_id: factura.id, deleted_at: "is.null" }, "id,monto,moneda");
      return pagos.length === 1 && Number(pagos[0].monto) === 1160 && pagos[0].moneda === "MXN";
    }).toBe(true);
    await expect(page.getByText("Pagada", { exact: true }).first()).toBeVisible();
    await attachFiscalRecords(info, { facturaId: factura.id, pagos: await rest.select("pagos_proveedor", { proveedor_factura_id: factura.id }, "id") });
  });
});
