import type { ChangelogEntry } from "../../changelogData";

export const chunk0: ChangelogEntry[] = [
  {
    version: "4.46.1",
    date: "2026-03-12",
    type: "patch",
    title: "Tendencia de cargas usa ETD en vez de fecha de creación",
    description: "La gráfica de tendencia y KPIs del Dashboard de Operaciones ahora agrupan las cargas por fecha de zarpe (ETD) en lugar de fecha de captura en el sistema. Etiquetas actualizadas a 'Por ETD'.",
  },
  {
    version: "4.46.0",
    date: "2026-03-11",
    type: "minor",
    title: "Dashboard de Operaciones completo",
    description: "Nuevo dashboard con KPIs globales, ranking de operadores por profit, tabla expandible con clientes y mini gráficas, tendencia de cargas creadas vs llegadas con filtro por operador, y barra de balance.",
  },
  {
    version: "4.45.0",
    date: "2026-03-11",
    type: "minor",
    title: "Sección colapsable Dashboards y página Operaciones",
    description: "El menú lateral ahora agrupa Dashboard Principal y el nuevo Dashboard de Operaciones en una sección colapsable 'Dashboards'. Se eliminó Reportes del menú y se agregó un separador visual.",
  },
  {
    version: "4.44.0",
    date: "2026-03-11",
    type: "minor",
    title: "Eliminar proveedores (solo administradores)",
    description: "Los administradores pueden eliminar proveedores desde su detalle, con doble confirmación de seguridad y registro en bitácora.",
  },
  {
    version: "4.43.1",
    date: "2026-03-11",
    type: "patch",
    title: "Mercancía general muestra todos los campos sin condición de modo",
    description: "Tipo de Unidad, Peso, Volumen y Piezas se muestran siempre en la sección de mercancía general, independientemente del modo de transporte.",
  },
  {
    version: "4.43.0",
    date: "2026-03-11",
    type: "minor",
    title: "Editar cotizaciones en estado Borrador",
    description: "Los operadores y administradores pueden editar cotizaciones cuando están en estado Borrador. Se reutiliza el wizard de 4 pasos con los datos pre-llenados desde la cotización guardada.",
  },
  {
    version: "4.42.0",
    date: "2026-03-11",
    type: "minor",
    title: "Campo 'Tipo de Unidad' para modo Terrestre en cotizaciones",
    description: "Al seleccionar modo Terrestre, se ocultan Peso, Volumen y Piezas y se muestra un campo de texto libre 'Tipo de Unidad' (Ej. Trailer, Caja seca, Plataforma, Rabón).",
  },
  {
    version: "4.41.0",
    date: "2026-03-11",
    type: "minor",
    title: "Operadores pueden eliminar cotizaciones",
    description: "Los usuarios con rol operador ahora pueden eliminar cotizaciones. Se implementó doble confirmación para mayor seguridad.",
  },
  {
    version: "4.40.0",
    date: "2026-03-11",
    type: "minor",
    title: "Agregar incoterm 'N/A'",
    description: "Se añadió la opción 'N/A' al dropdown de incoterm en cotizaciones y embarques.",
  },
  {
    version: "4.39.0",
    date: "2026-03-11",
    type: "minor",
    title: "Agregar tipo de operación 'Intra USA'",
    description: "Se añadió la opción 'Intra USA' al dropdown de tipo de operación en cotizaciones y embarques.",
  },
  {
    version: "4.38.1",
    date: "2026-03-11",
    type: "patch",
    title: "Simplificar etiqueta de contenedores en cotización",
    description: "Se cambió el texto 'Número de contenedores/Embarques' a 'Número de contenedores' en el formulario de nueva cotización.",
  },
  {
    version: "4.38.0",
    date: "2026-03-11",
    type: "minor",
    title: "Filtro por operador en tablero de embarques",
    description: "Se agregó un dropdown para filtrar embarques por operador asignado en la vista principal.",
  },
  {
    version: "4.37.5",
    date: "2026-03-11",
    type: "patch",
    title: "Agregar tipo de contenedor 20' GP",
    description: "Se añadió la opción 20' GP a todos los dropdowns de tipo de contenedor en embarques y cotizaciones.",
  },
  {
    version: "4.37.4",
    date: "2026-03-11",
    type: "patch",
    title: "Formato legible de timestamp en Notas y Actividad",
    description: "Las fechas en la pestaña Notas y Actividad del embarque ahora muestran formato DD/MM/YYYY, HH:mm localizado (es-MX) en lugar del formato ISO crudo.",
  },
  {
    version: "4.37.3",
    date: "2026-03-10",
    type: "patch",
    title: "Unificar catálogo de conceptos embarques ↔ cotizaciones",
    description: "CATALOGO_CONCEPTOS en embarqueConstants.ts ahora contiene los mismos 18 conceptos usados en cotizaciones, eliminando discrepancias entre módulos.",
  },
  {
    version: "4.37.2",
    date: "2026-03-10",
    type: "patch",
    title: "Limpieza: eliminar componente legacy de costos internos",
    description: "Se removió SeccionCostosInternosCotizacion (no utilizado) reemplazado por SeccionCostosInternosPLUnificado.",
  },
  {
    version: "4.37.1",
    date: "2026-03-10",
    type: "patch",
    title: "Fix setValue en vinculación de cotización y soporte Cross Trade",
    description: "Corregido el problema donde los campos controlados (Select, Combobox) no se actualizaban al vincular/desvincular una cotización. Se agregó 'Cross Trade' al listado de tipos de operación en embarques.",
  },
  {
    version: "4.37.0",
    date: "2026-03-10",
    type: "minor",
    title: "Vincular cotización existente al crear embarque",
    description: "Al crear un nuevo embarque se puede vincular opcionalmente una cotización con estado 'Aceptada'. Se pre-llenan los campos del formulario y al guardar la cotización cambia a 'Embarcada'.",
  },
  {
    version: "4.36.7",
    date: "2026-03-10",
    type: "patch",
    title: "Corrección de datos: COT-2026-0007 a Aceptada",
    description: "Se corrigió el estado de la cotización COT-2026-0007 que quedó como 'Embarcada' sin embarques activos, revirtiéndola a 'Aceptada'.",
  },
  {
    version: "4.36.6",
    date: "2026-03-10",
    type: "patch",
    title: "Revertir cotización al eliminar embarque vinculado",
    description: "Al eliminar un embarque que tiene cotización vinculada, si no quedan más embarques asociados a esa cotización, el estado se revierte automáticamente a 'Aceptada'.",
  },
  {
    version: "4.36.5",
    date: "2026-03-10",
    type: "patch",
    title: "Políticas RLS permisivas para eliminar embarques",
    description: "Se agregaron políticas DELETE permisivas en 6 tablas (embarques, conceptos_venta, conceptos_costo, documentos_embarque, notas_embarque, facturas) para que la eliminación en cascada funcione correctamente para roles admin y operador.",
  },
  {
    version: "4.36.4",
    date: "2026-03-10",
    type: "minor",
    title: "Eliminar embarques desde la lista",
    description: "Se agregó botón de eliminar por fila en la lista de embarques, visible en hover para roles admin y operador, con flujo de doble confirmación y registro en bitácora.",
  },
  {
    version: "4.36.3",
    date: "2026-03-10",
    type: "patch",
    title: "Estado 'Embarcada' en cotizaciones al generar embarques",
    description: "Al convertir una cotización en embarques, el estado ahora cambia a 'Embarcada' en lugar de 'Convertida'. Se agregó el filtro y badge con color índigo para el nuevo estado.",
  },
  {
    version: "4.36.2",
    date: "2026-03-10",
    type: "patch",
    title: "Barra de progreso de facturación en resumen del mes siguiente",
    description: "Se agregó una barra de progreso visual con porcentaje en la tarjeta de Facturados del resumen del mes siguiente. La barra cambia de color según el avance: verde (≥75%), amarillo (25-74%) y rojo (<25%).",
  },
  {
    version: "4.36.1",
    date: "2026-03-10",
    type: "patch",
    title: "Simplificar confirmación de eliminación en DocumentChecklist",
    description: "Se reemplazó el flujo de doble confirmación por un solo diálogo directo al eliminar archivos adjuntos, corrigiendo el bug donde la segunda confirmación no ejecutaba la eliminación.",
  },
];
