import type { ChangelogEntry } from "../../changelogData";

export const chunk1: ChangelogEntry[] = [
  {
    version: "4.36.0",
    date: "2026-03-10",
    type: "minor",
    title: "Profit filtrado por mes + Tabla de embarques mes siguiente con facturación",
    description: "La tabla de Profit USD ahora muestra solo embarques con arribo este mes. Se reemplazó la tabla de embarques activos por una vista del mes siguiente con resumen de facturación (venta, costo, profit, facturados vs pendientes) y columna de estado de facturación.",
  },
  {
    version: "4.35.0",
    date: "2026-03-09",
    type: "minor",
    title: "Línea de tiempo visual + Indicador de arribos y profit",
    description: "Se reemplazaron las tarjetas de estado del Dashboard por una línea de tiempo horizontal interactiva con 5 nodos (Confirmado → En Tránsito → Arribo → En Aduana → Entregado). Se agregó indicador compacto de arribos del mes con métricas de ya llegaron, en camino y profit USD proyectado.",
  },
  {
    version: "4.34.0",
    date: "2026-03-09",
    type: "minor",
    title: "Tarjeta 'Arribos este mes' en Dashboard",
    description: "Se agregó una tarjeta informativa al final de la fila de estados del Dashboard que muestra el conteo de embarques con ETA dentro del mes en curso. Estilo consistente con las tarjetas existentes, barra cyan decorativa.",
  },
  {
    version: "4.33.1",
    date: "2026-03-09",
    type: "patch",
    title: "Corregir registro duplicado de logins en bitácora",
    description: "El evento SIGNED_IN de autenticación se disparaba en cada refresh de token y recarga de página, generando miles de registros falsos de login. Ahora se usa un ref para registrar solo el primer login real por sesión del componente.",
  },
  {
    version: "4.33.0",
    date: "2026-03-09",
    type: "minor",
    title: "Mejoras completas en la Bitácora de Actividad",
    description: "Se filtran logins por defecto con toggle para incluirlos. Se corrigieron nombres de acciones inconsistentes (crear cotización, editar_cliente, cambiar_estado). Se agregó tracking para facturas. Se añadió módulo Cotizaciones a filtros y rutas de navegación. Nuevos íconos para agregar_nota y eliminar_documento.",
  },
  {
    version: "4.32.2",
    date: "2026-03-09",
    type: "patch",
    title: "Corregir eliminación de documentos en embarques",
    description: "El botón Eliminar en el detalle del embarque ahora muestra un diálogo de confirmación antes de proceder. La función de eliminación ahora borra el registro completo de la base de datos y el archivo de Storage, en lugar de solo limpiar el campo.",
  },
  {
    version: "4.32.1",
    date: "2026-03-09",
    type: "patch",
    title: "Eliminar archivos adjuntos con doble confirmación",
    description: "Los operadores pueden eliminar archivos adjuntos en el paso de Documentos Requeridos al crear un embarque. Incluye doble confirmación para evitar borrados accidentales.",
  },
  {
    version: "4.32.0",
    date: "2026-03-09",
    type: "minor",
    title: "Nuevo sistema de estados de embarques",
    description: "7 estados en orden: Confirmado → En Tránsito → Arribo → En Aduana → Entregado → EIR → Cerrado. Cálculo automático solo para importaciones marítimas. Arribo reemplaza la detección automática post-ETA. Nuevos colores semánticos por estado.",
  },
  {
    version: "4.31.0",
    date: "2026-03-09",
    type: "minor",
    title: "Dashboard completo de Reportes",
    description: "Expansión mayor con filtro de período, 4 nuevas secciones (Panorama General, Operaciones, Ventas, Rentabilidad) y métricas avanzadas.",
  },
  {
    version: "4.30.5",
    date: "2026-03-07",
    type: "patch",
    title: "Page break en PDF de cotización",
    description: "Se agregó un salto de página en el PDF generado de cotización para separar los datos generales y mercancía (página 1) de los conceptos de venta, resumen y notas (página 2).",
  },
  {
    version: "4.30.4",
    date: "2026-03-07",
    type: "patch",
    title: "Formato de fecha legible en tabla de Cotizaciones",
    description: "La columna Fecha ahora muestra día/mes/año y hora en formato es-MX (ej. 05/03/2026, 14:35) en lugar del timestamp crudo.",
  },
  {
    version: "4.30.3",
    date: "2026-03-07",
    type: "patch",
    title: "Desglose correcto de totales en PDF de cotización",
    description: "Se corrigió el bloque de resumen del PDF para mostrar subtotal, IVA y total por separado en USD y MXN, con visualización condicional según los conceptos existentes.",
  },
  {
    version: "4.30.2",
    date: "2026-03-07",
    type: "patch",
    title: "Corrección de nombres de puerto duplicados en tablas de embarques",
    description: "Se mejoró la lógica de extracción del nombre corto de puertos en la tabla de Embarques Activos del Dashboard y en el listado principal de Embarques para manejar correctamente datos guardados con el formato anterior.",
  },
  {
    version: "4.30.1",
    date: "2026-03-07",
    type: "patch",
    title: "Corrección de nombre duplicado en selector de puertos",
    description: "Se ajustó la función shortName para extraer solo el nombre del puerto sin repetir cuando el valor ya viene en formato 'Nombre - Ciudad, País'.",
  },
  {
    version: "4.30.0",
    date: "2026-03-07",
    type: "minor",
    title: "Generar PDF de cotización",
    description: "Nuevo botón en CotizacionDetalle para generar un PDF profesional con header de empresa, datos generales, mercancía (general, FCL, LCL, aérea con dimensiones), tablas de conceptos USD y MXN, resumen de totales, notas y sello de propuesta.",
  },
  {
    version: "4.29.0",
    date: "2026-03-07",
    type: "minor",
    title: "Sección de mercancía contextual en detalle de cotización",
    description: "El detalle de cotización ahora muestra una Card de mercancía que se adapta al modo de transporte: información general para todos, tabla de contenedor para FCL, tabla de dimensiones con cálculo de volumen para LCL, y tabla de dimensiones con peso volumétrico para Aéreo.",
  },
  {
    version: "4.28.0",
    date: "2026-03-07",
    type: "minor",
    title: "Detalle completo de cotización con conceptos de venta",
    description: "Página de detalle de cotización con datos generales, mercancía (peso, volumen, piezas), tablas independientes de conceptos USD y MXN con subtotales, IVA y total. Incluye botones para cambiar estado (Enviar, Confirmar, Rechazar, Aceptar), convertir prospecto a cliente y resumen de totales en ambas monedas.",
  },
  {
    version: "4.27.0",
    date: "2026-03-07",
    type: "minor",
    title: "Tabla de cotizaciones con filtros y búsqueda",
    description: "Nueva vista de listado de cotizaciones con búsqueda por texto, filtros por estado y modo de transporte, paginación y acceso al detalle. Cada fila muestra folio, cliente, modo, tipo, ruta, estado con badge de color y fecha de creación.",
  },
  {
    version: "4.26.0",
    date: "2026-03-07",
    type: "minor",
    title: "Conceptos de Venta en cotización (USD y MXN)",
    description: "Sección de conceptos de venta dividida en USD y MXN con campos de descripción, cantidad, precio unitario, total y dropdown de unidad de medida. Totales automáticos por moneda con subtotal, IVA (solo MXN) y total. IVA de 16% aplicado automáticamente a MXN.",
  },
  {
    version: "4.25.0",
    date: "2026-03-07",
    type: "minor",
    title: "Sección de ruta dinámica en cotización",
    description: "Nueva sección de Ruta en el formulario de cotización que se adapta al modo de transporte. Marítimo muestra puertos con autocompletado y selector de tipo de embarque (FCL/LCL). Aéreo muestra aeropuertos. Terrestre muestra ciudades. Multimodal combina puertos y ciudades.",
  },
  {
    version: "4.24.0",
    date: "2026-03-07",
    type: "minor",
    title: "Formulario de nueva cotización con datos generales y mercancía",
    description: "Nuevo formulario de cotización con secciones de datos generales (cliente/prospecto, modo, tipo, incoterm, moneda, operador) y mercancía (descripción, peso, volumen, piezas). Folio auto-generado con formato COT-YYYY-NNNN.",
  },
  {
    version: "4.23.0",
    date: "2026-03-07",
    type: "minor",
    title: "Tabla de cotizaciones y esquema de base de datos",
    description: "Nueva tabla cotizaciones en la BD con 30+ campos. Enums estado_cotizacion y tipo_servicio_maritimo. Tabla cotizacion_costos para costos internos P&L. RLS habilitado. Vista inicial con listado paginado, búsqueda y filtros por estado/modo.",
  },
  {
    version: "4.22.0",
    date: "2026-03-07",
    type: "minor",
    title: "Utilidades financieras centralizadas",
    description: "Creado src/lib/financialUtils.ts con funciones de cálculo de IVA, subtotales, márgenes y conversión de moneda. src/lib/profitUtils.tsx con badge de profit y cálculo de totales P&L. Eliminación de math inline disperso en componentes.",
  },
  {
    version: "4.21.1",
    date: "2026-03-07",
    type: "patch",
    title: "Auditoría completa de math inline",
    description: "Auditoría completa de math inline: useConceptosForm ahora envuelve subtotalVenta/totalCosto/utilidadEstimada en useMemo con calcularUtilidad. useCotizacionWizardForm usa calcularIVA/calcularTotalConIVA. EmbarqueDetalle envuelve reduces en useMemo antes de early returns. Reportes usa convertirAMXN y calcularMargen centralizados. profitUtils migrado a tokens semánticos (success/warning/destructive). Todas las funciones de financialUtils y profitUtils con return types estrictos.",
  },
  {
    version: "4.21.0",
    date: "2026-03-07",
    type: "minor",
    title: "Refactorización de formularios de embarque con React Hook Form",
    description: "Migrado useEmbarqueForm a react-hook-form (useForm/FormProvider). StepDatosGenerales, StepDatosRuta y StepCostosPrecios ahora usan useFormContext eliminando ~40 props de prop drilling. Inputs de texto usan register() (no controlados) para evitar re-renders innecesarios. NuevoEmbarque y EditarEmbarque simplificados como orquestadores de UI.",
  },
];
