import type { ChangelogEntry } from "../../changelogData";

export const chunk2: ChangelogEntry[] = [
  {
    version: "4.20.0",
    date: "2026-03-07",
    type: "minor",
    title: "Refactorización de NuevaCotizacion — hook useCotizacionWizardForm",
    description: "Extraído todo el estado (~30 useState), lógica de navegación, validación, persistencia y cálculos del wizard de cotizaciones al hook useCotizacionWizardForm. NuevaCotizacion.tsx reducido de 577 a ~220 líneas como orquestador puro de UI. Cálculos envueltos en useMemo y acciones en useCallback.",
  },
  {
    version: "4.19.0",
    date: "2026-03-07",
    type: "minor",
    title: "Centralización de cálculos financieros",
    description: "Tipo estricto Moneda y función convertirAUSD agregados a financialUtils.ts. Interface TotalesPL y return type explícito en profitUtils.tsx. Inline math de márgenes y utilidad reemplazado en useDashboardData, StepCostosPrecios y SeccionCostosInternosPLUnificado con funciones centralizadas. Totales en StepCostosPrecios envueltos en useMemo.",
  },
  {
    version: "4.18.0",
    date: "2026-03-07",
    type: "minor",
    title: "Unificación de TablaConceptos y SeccionCostosInternosPL",
    description: "TablaConceptosUSD y TablaConceptosMXN consolidados en TablaConceptosGenerico con prop moneda. SeccionCostosInternosPL y SeccionCostosInternosPLLocal unificados en SeccionCostosInternosPLUnificado con prop tipo ('detalle'|'local'). Extraído ResumenPL como componente compartido. Eliminados 4 archivos redundantes.",
  },
  {
    version: "4.17.0",
    date: "2026-03-07",
    type: "minor",
    title: "Refactorización masiva del proyecto",
    description: "useEmbarques.ts separado en useEmbarqueQueries, useEmbarqueMutations y useEmbarqueUtils con barrel re-export. EmbarqueDetalle.tsx refactorizado extrayendo DialogDuplicarEmbarque y DialogEliminarEmbarque. Configuracion.tsx modularizado en 7 tabs independientes (TabEmpresa, TabTiposCambio, TabCotizaciones, TabFacturacion, TabEmbarques, TabAlertas, TabPuertos). Creado financialUtils.ts con funciones centralizadas de IVA, subtotales, márgenes y conversión de moneda. Constantes ESTADOS_EMBARQUE, MODOS_TRANSPORTE y ESTADOS_ACTIVOS unificadas en embarqueConstants.ts.",
  },
  {
    version: "4.16.1",
    date: "2026-03-07",
    type: "patch",
    title: "Refactorización completa del Dashboard",
    description: "Se extrajo la lógica de datos a useDashboardData hook y se crearon 5 sub-componentes (DashboardStatusCards, AlertasDemoraCard, ProximosArribosCard, ProfitTable, EmbarquesActivosTable). Se reemplazaron colores HSL hardcodeados por tokens semánticos del design system.",
  },
  {
    version: "4.16.0",
    date: "2026-03-06",
    type: "minor",
    title: "Rediseño completo del Dashboard",
    description: "Nuevo dashboard estilo command center con resumen por estado (Confirmado, En Tránsito, En Aduana, Entregado) con filtrado interactivo, alertas de demora en aduana, próximos arribos en 7 días, tabla de profit USD por embarque con margen, y lista de embarques activos filtrable. Se eliminaron secciones de facturas, gastos, gráfica Recharts y bitácora.",
  },
  {
    version: "4.15.7",
    date: "2026-03-06",
    type: "minor",
    title: "Tipo de operación Cross Trade en cotizaciones",
    description: "Se agrega la opción 'Cross Trade' al dropdown de tipo de operación en datos generales de cotización.",
  },
  {
    version: "4.15.6",
    date: "2026-03-06",
    type: "patch",
    title: "Cantidad decimal en P&L",
    description: "El campo de cantidad en la sección de costos P&L ahora acepta valores decimales con punto.",
  },
  {
    version: "4.15.5",
    date: "2026-03-06",
    type: "patch",
    title: "Permiso de eliminación de embarques para operadores",
    description: "El equipo operativo (rol operador) ahora puede eliminar embarques con la misma doble confirmación de seguridad que los administradores.",
  },
  {
    version: "4.15.4",
    date: "2026-03-06",
    type: "minor",
    title: "Estado automático para embarques marítimos",
    description: "Los embarques marítimos ahora calculan su estado automáticamente según ETD/ETA: Confirmado (antes de ETD), En Tránsito (entre ETD y ETA), En Aduana (después de ETA). Se agregan los estados En Aduana, Entregado y Cancelado al enum. Estado inicial cambiado de Cotización a Confirmado.",
  },
  {
    version: "4.15.3",
    date: "2026-03-06",
    type: "patch",
    title: "Centralizar constantes de cotización",
    description: "Se crea src/data/cotizacionConstants.ts con CONCEPTOS_COSTO_USD, CONCEPTOS_COSTO_MXN y CONCEPTOS_CON_IVA_USD. Los componentes SeccionCostosInternosPLLocal, SeccionConceptosVentaCotizacion y NuevaCotizacion ahora importan desde este archivo centralizado.",
  },
  {
    version: "4.15.2",
    date: "2026-03-06",
    type: "patch",
    title: "Columna Unidad y IVA condicional en PDF de cotización",
    description: "Se agrega la columna 'Unidad' en las tablas de conceptos USD y MXN del PDF. Los conceptos USD con IVA ahora muestran columnas de Subtotal e IVA condicionalmente. Se actualiza el texto del pie a 'Los cargos en destino incluyen IVA'.",
  },
  {
    version: "4.15.1",
    date: "2026-03-06",
    type: "patch",
    title: "Duplicar embarque conserva expediente del origen",
    description: "Al duplicar un embarque, las copias ahora conservan el mismo número de expediente del embarque origen en lugar de generar uno nuevo.",
  },
  {
    version: "4.15.0",
    date: "2026-03-06",
    type: "minor",
    title: "Eliminar Embarque (solo Admin)",
    description: "Nuevo botón para eliminar embarques de forma permanente, disponible exclusivamente para administradores. Incluye doble confirmación de seguridad y eliminación en cascada de todos los registros relacionados (documentos, costos, conceptos de venta, notas y facturas). La acción queda registrada en la bitácora.",
  },
  {
    version: "4.14.0",
    date: "2026-03-06",
    type: "minor",
    title: "Duplicar Embarque",
    description: "Nueva funcionalidad para duplicar un embarque existente creando 1 a 10 copias con contenedores independientes. Copia automáticamente cliente, BL, naviera, ruta, fechas, conceptos de venta y costos internos. Accesible desde el detalle del embarque para admin y operador.",
  },
  {
    version: "4.13.0",
    date: "2026-03-06",
    type: "minor",
    title: "Refactorización: utilidades P&L, componentes extraídos y helpers consolidados",
    description: "Se extrajo profitBadge, calcularTotalesPL y rentabilidadGlobal a src/lib/profitUtils.tsx eliminando duplicación en 3 archivos. Se creó PasoResumenCotizacion.tsx y SeccionMercanciaCotizacionDetalle.tsx como componentes independientes. Se consolidaron helpers USD/MXN en funciones parametrizadas. NuevaCotizacion.tsx se redujo ~120 líneas y CotizacionDetalle.tsx ~130 líneas.",
  },
  {
    version: "4.12.0",
    date: "2026-03-06",
    type: "minor",
    title: "Botón eliminar cotización (solo admin)",
    description: "Se agregó una columna de acciones en la tabla de cotizaciones con botón de eliminar visible únicamente para administradores. Incluye confirmación con AlertDialog antes de proceder.",
  },
  {
    version: "4.11.2",
    date: "2026-03-06",
    type: "patch",
    title: "Corregir pre-llenado Paso 2 → Paso 3 en wizard de cotización",
    description: "El pre-llenado del Paso 3 ahora se ejecuta directamente al avanzar desde el Paso 2, eliminando la dependencia del useEffect que causaba problemas de sincronización. Se removió la prop redundante onCostosChange.",
  },
  {
    version: "4.11.1",
    date: "2026-03-06",
    type: "patch",
    title: "Corregir validación Paso 3 → Paso 4 en wizard de cotización",
    description: "La validación del Paso 3 ahora filtra conceptos con descripción vacía en lugar de rechazarlos. Solo se guardan en la base de datos los conceptos válidos. Se requiere al menos un concepto con descripción para avanzar.",
  },
  {
    version: "4.11.0",
    date: "2026-03-05",
    type: "minor",
    title: "Guardado progresivo por paso en wizard de cotización",
    description: "El wizard de nueva cotización ahora guarda en la base de datos en cada paso: Paso 1 crea/actualiza la cotización, Paso 2 guarda costos internos, Paso 3 actualiza conceptos de venta y Paso 4 finaliza como Borrador. Si ocurre un error en cualquier paso, no avanza al siguiente.",
  },
  {
    version: "4.10.6",
    date: "2026-03-05",
    type: "patch",
    title: "Corregir pre-llenado IVA del Paso 3 desde Paso 2",
    description: "Se agregó callback onCostosChange en SeccionCostosInternosPLLocal para sincronizar estado con el wizard. El pre-llenado del Paso 3 ahora aplica IVA automático solo a conceptos USD específicos (Handling, Desconsolidación, Revalidación, Demoras, Cargos en Destino, Release) y siempre IVA para MXN.",
  },
  {
    version: "4.10.5",
    date: "2026-03-05",
    type: "patch",
    title: "Actualizar catálogos y lógica de IVA en Cotización Cliente",
    description: "Se actualizaron los catálogos de conceptos USD (16 opciones) y MXN (3 opciones) en la sección Cotización Cliente. Se amplió CONCEPTOS_CON_IVA para incluir Demoras, Cargos en Destino y Release. Al seleccionar un concepto con IVA, aplica_iva se activa automáticamente.",
  },
  {
    version: "4.10.4",
    date: "2026-03-05",
    type: "patch",
    title: "Actualizar catálogos de conceptos en Costos & P&L",
    description: "Se reemplazaron los catálogos de conceptos USD y MXN en el wizard de cotización. USD ahora incluye 16 opciones (Cargos en Origen, Costos Portuarios, Consolidación, Seguro, Recolección, Modificación de BL, Flete Marítimo/Aéreo/Terrestre, Handling, Desconsolidación, Revalidación, Demoras, Cargos en Destino, Release, Otro). MXN se simplificó a 3 opciones (Entrega Nacional, Honorarios de Despacho Aduanal, Otro).",
  },
  {
    version: "4.10.3",
    date: "2026-03-05",
    type: "patch",
    title: "Agregar 'Cargos en Destino' al catálogo USD",
    description: "Se añadió la opción 'Cargos en Destino' al dropdown de conceptos en USD dentro del wizard de nueva cotización (SeccionCostosInternosPLLocal).",
  },
  {
    version: "4.10.2",
    date: "2026-03-05",
    type: "patch",
    title: "Botón eliminar documentos en embarque",
    description: "Se agregó un botón 'Eliminar' en la pestaña de documentos del detalle de embarque. Permite borrar el archivo adjunto de Storage y regresar el estado del documento a 'Pendiente' para subir uno nuevo. La acción queda registrada en la bitácora.",
  },
];
