import type { ChangelogEntry } from "../../../changelogData";

export const chunk3: ChangelogEntry[] = [
  {
    version: "4.10.1",
    date: "2026-03-05",
    type: "patch",
    title: "Layout de dos líneas y catálogo de conceptos en Costos P&L",
    description: "Rediseño del componente SeccionCostosInternosPLLocal: cada fila se muestra en dos líneas (concepto/proveedor/unidad + cantidad/costo/venta/profit). El campo Concepto ahora es un Select con catálogo predefinido por moneda (USD/MXN). Se eliminó la tabla apretada en favor de un layout espacioso sin scroll horizontal.",
  },
  {
    version: "4.10.0",
    date: "2026-03-05",
    type: "minor",
    title: "Wizard de 4 pasos en Nueva Cotización",
    description: "Rediseño de NuevaCotizacion como wizard con 4 pasos: Datos Generales, Costos & P&L (con SeccionCostosInternosPLLocal), Cotización Cliente (pre-llenado automático desde costos) y Resumen con P&L y datos de operación. Incluye campo Número de Embarques y navegación con StepIndicator.",
  },
  {
    version: "4.9.5",
    date: "2026-03-05",
    type: "minor",
    title: "Botón Generar Embarques y card de embarques vinculados",
    description: "En CotizacionDetalle se agrega botón para convertir cotización aceptada en embarques con diálogo de confirmación, y una card que lista los embarques generados con links navegables.",
  },
  {
    version: "4.9.4",
    date: "2026-03-05",
    type: "minor",
    title: "Hook para convertir cotización en embarques",
    description: "Nuevo hook useConvertirCotizacionAEmbarques que crea automáticamente embarques a partir de una cotización según num_contenedores, mapeando costos por unidad_medida (Contenedor, BL, W/M) y actualizando el estado a Convertida.",
  },
  {
    version: "4.9.3",
    date: "2026-03-05",
    type: "patch",
    title: "Migración de esquema: contenedores, cotización-embarque y P&L en costos",
    description: "Se agregó num_contenedores a cotizaciones, cotizacion_id a embarques, y columnas de precio_venta, precio_total, profit, porcentaje_profit y unidad_medida a cotizacion_costos (con columnas generadas).",
  },
  {
    version: "4.9.2",
    date: "2026-03-05",
    type: "patch",
    title: "Corrección de inputs numéricos en conceptos de cotización",
    description: "Los campos de cantidad y precio unitario en conceptos USD y MXN ahora limpian el 0 inicial al hacer clic y validan correctamente el formato numérico/decimal.",
  },
  {
    version: "4.9.1",
    date: "2026-03-05",
    type: "patch",
    title: "Campo Agente en Datos de Ruta marítimo",
    description: "Nuevo campo de texto libre 'Agente' en la sección marítima de Datos de Ruta, junto al campo Naviera. Disponible en creación y edición de embarques.",
  },
  {
    version: "4.9.0",
    date: "2026-03-04",
    type: "minor",
    title: "Catálogo de puertos configurable",
    description: "Los puertos de origen/destino en cotizaciones y embarques ahora se administran desde Configuración → Puertos. Se pueden agregar, desactivar y eliminar puertos. La tabla 'puertos' en la base de datos reemplaza el catálogo estático anterior.",
  },
  {
    version: "4.8.5",
    date: "2026-03-04",
    type: "patch",
    title: "Formato de moneda mexicana en todos los campos de dinero",
    description: "Reemplazados todos los formatos manuales de dinero con formatCurrency() usando Intl.NumberFormat('es-MX') en StepCostosPrecios, SeccionConceptosVentaCotizacion, CotizacionDetalle y cotizacionPdf. Separadores de miles y decimales consistentes en toda la app.",
  },
  {
    version: "4.8.4",
    date: "2026-03-04",
    type: "patch",
    title: "Refactorización: duplicados, sub-componentes y nombres",
    description: "Fase 1: Eliminado useClientesForSelect duplicado de useEmbarques, fmt local reemplazado por formatCurrency, CONCEPTOS_CON_IVA consolidado, calcularPL muerta eliminada, import Input no usado removido. Fase 2: Extraídos TablaConceptosUSD, TablaConceptosMXN, ResumenTotalesCotizacion y DialogConvertirProspecto de CotizacionDetalle (~488→~300 líneas). Fase 3: Variables crípticas renombradas (qc→queryClient, totUSD→totalesUSD, totMXN→totalesMXN).",
  },
  {
    version: "4.8.3",
    date: "2026-03-04",
    type: "patch",
    title: "P&L siempre calcula profit sin IVA",
    description: "Corregido el módulo de Costos Internos P&L para que todos los cálculos de profit usen subtotales sin IVA. La columna Venta muestra el valor neto con etiqueta visual '+ IVA' como referencia.",
  },
  {
    version: "4.8.2",
    date: "2026-03-04",
    type: "minor",
    title: "IVA condicional en conceptos USD",
    description: "Toggle switch de IVA 16% para conceptos Handling, Desconsolidación y Revalidación en la tabla USD de cotizaciones. Footer dinámico con desglose de subtotal, IVA y total cuando aplica.",
  },
  {
    version: "4.8.1",
    date: "2026-03-04",
    type: "patch",
    title: "Nuevos conceptos en catálogos de venta",
    description: "Se agregan Revalidación, Handling, Desconsolidación y Entrega Nacional a los dropdowns de conceptos USD y MXN en cotizaciones.",
  },
  {
    version: "4.8.0",
    date: "2026-03-04",
    type: "minor",
    title: "Unidad de Medida en conceptos de venta",
    description: "Nuevo campo dropdown 'Unidad de Medida' en ambas tablas de conceptos (USD y MXN) con opciones: BL, W/M, Documento, Contenedor, Kilo, Embarque. Visible también en el detalle de cotización.",
  },
  {
    version: "4.7.0",
    date: "2026-03-04",
    type: "minor",
    title: "Sección de Costos Internos P&L por moneda",
    description: "Nuevo componente SeccionCostosInternosPL con tablas separadas USD y MXN, pre-poblado automático desde conceptos de venta, cálculo de profit y % por fila, resumen colapsable con totales por moneda. Visible solo para admin y operador.",
  },
  {
    version: "4.6.0",
    date: "2026-03-04",
    type: "minor",
    title: "Reestructuración de costos internos de cotización",
    description: "Nueva tabla cotizacion_costos con campos de concepto, proveedor, unidad, cantidad, costo unitario y moneda. CRUD completo con hook dedicado useCotizacionCostos. Cards de resumen por moneda con totales calculados.",
  },
  {
    version: "4.5.0",
    date: "2026-03-04",
    type: "minor",
    title: "Agregar contacto desde detalle de cliente",
    description: "Nuevo botón y diálogo para agregar contactos (Proveedor, Exportador o Importador) directamente desde la página de detalle del cliente. El contacto se registra en bitácora.",
  },
  {
    version: "4.4.0",
    date: "2026-03-04",
    type: "minor",
    title: "Búsqueda global (⌘+K)",
    description: "Nuevo buscador global accesible desde cualquier página con el shortcut ⌘+K (o Ctrl+K). Busca en embarques, clientes, proveedores y facturas simultáneamente.",
  },
  {
    version: "4.3.0",
    date: "2026-03-03",
    type: "minor",
    title: "Navegación lateral con secciones colapsables",
    description: "Sidebar actualizado a ShadCN sidebar component con secciones colapsables para cada módulo, subniveles jerárquicos, y estilos consistentes con el design system.",
  },
  {
    version: "4.2.1",
    date: "2026-03-03",
    type: "patch",
    title: "Dropdown de conceptos en cotizaciones",
    description: "Se reemplazó el campo de texto libre 'Descripción' por un dropdown 'Concepto' con 8 opciones estandarizadas del catálogo (Flete Marítimo, Embalaje, Coordinación de Recolección, Seguro de Carga, Manejo, Demoras, Cargos en Destino, Cargos en Origen) en la sección de conceptos de venta de cotizaciones.",
  },
  {
    version: "4.2.0",
    date: "2026-03-03",
    type: "minor",
    title: "Mejora visual UI/UX integral",
    description: "Rediseño visual en 17 archivos sin cambios funcionales. Tablas con header uppercase tracking-wide y fondo sutil. KPI cards con borde izquierdo por categoría. Badges más compactos. Header global con shadow-sm y tipografía mejorada. Login con logo eLogistix y fondo gradiente. Filtros con gap-4 consistente. SearchInput con fondo sutil. Scrollbar personalizado. Tipografía con antialiased y font-feature-settings. Subtítulos descriptivos en todas las páginas.",
  },
  {
    version: "4.1.0",
    date: "2026-03-03",
    type: "minor",
    title: "Módulo de Configuración centralizado",
    description: "Nueva página /configuracion accesible solo para admins con 6 secciones: Datos de la Empresa, Tipos de Cambio por Defecto, Cotizaciones, Facturación, Embarques y Alertas del Dashboard. Tabla configuracion en BD con pares clave-valor por categoría, hook useConfiguracion con cache de 5 min, y useConfigValue para consumir valores individuales desde cualquier componente.",
  },
  {
    version: "4.0.0",
    date: "2026-03-02",
    type: "major",
    title: "Refactorización integral — Fases 1-4",
    description: "Fase 1: Eliminación de propiedad muerta 'iva' en tipos e inicializaciones, y funciones vacías isStep1Valid/isStep2Valid. Fase 2: Hook centralizado useEmbarqueForm con ~35 estados, handleMsdsUpload y builders de payload, eliminando ~200 líneas duplicadas entre NuevoEmbarque y EditarEmbarque. Fase 3: Componente DocumentChecklist reutilizable, usado en Clientes y NuevoProveedorDialog. Fase 4: NuevaCotizacion descompuesta en SeccionDestinatario, SeccionDatosGeneralesCotizacion, SeccionRutaCotizacion y SeccionConceptosVentaCotizacion.",
  },
];
